doc/self-hosted/index.md
fix port number in the quick start guide
=> fix port number

scripts/webpack.general.config.js
HappyPack requires a positive integer for threads. And when the number of cpu is 1, it is calculated 1 - 1 = 0. Now a minimal value will be 1.
=> Fixes calculate num of cpu threads for HappyPack

doc/self-hosted/index.md, packages/server/src/cli.ts
Add `--password=123456` CLI argument to use fix password instead of random.
@kylecarbs Currently I'm on Windows so I can't test it but I hope the code is correct. Maybe could you try it?
=> Implement #4 - fix password via CLI

packages/server/src/cli.ts
Issue:
https://github.com/codercom/code-server/issues/26
Changes:
Swap out the password generator for a native NodeJS CSPRNG method
https://nodejs.org/dist/latest-v10.x/docs/api/crypto.html#crypto_crypto_randombytes_size_callback
Test Environment:
OS: Mac OS High Sierra (10.13.6)
Browser: Google Chrome 72.0.3626.109 (Official Build) (64-bit)
(Result: Pass! Compile was successful and everything functions as expected)
Caveats: 
None that I can think of. Although this did lead me to discover another issue. The input component has no error states for an incorrect password. (I'll open a new issue for this and style it to match what we currently have on our hosted services)
UPDATE: other issue is now here https://github.com/codercom/code-server/issues/55
=> Generate secure passwords, resolves issue #26

packages/app/browser/src/app.html
Currently this checkbox does nothing. Neither does "helper text" provide any useful context at this time. We can remove them for now.
=> Remove unused markup from password page

.dockerignore, Dockerfile, README.md, packages/runner/src/runner.ts, scripts/build.sh
=> Add Dockerfile and some cleanup

README.md
The existing command errors out with 
```
docker: invalid publish opts format (should be name=value but got 'localhost:8443:8443').
```
it needs to explicitly use an IP and not a hostname.
=> update example docker command port bind options

.github/CODEOWNERS, Dockerfile
Closes #84
Closes #83
Thanks @xMrWhite, @frol and @sr229.
=> Dockerfile: cleanup and add en_US.UTF-8 locale

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/extension_bug.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
- Simplify the user by opening an issue (giving direction)
- Mark issue label
- Markdown lint
=> Improve github issue template

packages/server/src/cli.ts, packages/server/src/constants.ts
Data files (`dataDir`) and log files (`logDir`) were defaulting to a hidden dir (`.code-server/`) in the base of the user's home directory, based on their OS. This did not conform with the [XDG standards](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#basics), which help make these kinds of paths predictable and organized.
Fixes https://github.com/codercom/code-server/issues/15
=> Adhere to XDG base directory spec for dataDir and logDir

packages/ide/src/fill/client.ts
This is the critical piece to let you serve code-server proxied under a
path.  Otherwise if you proxy e.g. `/editor/` thru to
`http://localhost:8000`, everything works fine except the websocket
connection is still opened to `/`
=> open websocket on same path as page

packages/server/package.json, packages/server/src/server.ts, packages/server/yarn.lock
As the current implementation of password checking uses `===` to check equality, it is susceptible to timing attacks - see [this article](https://snyk.io/blog/node-js-timing-attack-ccc-ctf/) for more information.
This PR uses [`safe-compare`](https://github.com/Bruce17/safe-compare) to compare passwords without the possibility of a timing attack.
(Note that I could not test this change, as I was unable to successfully build the project. Please confirm that this change does not break anything before merging it!)
=> Use a timing-safe equality check for passwords

README.md
Cannot mount data directory at the moment, we need to make code-server
override all binaries in there instead of reusing and will wait
until the new Dockerfile is pushed before removing the default
entrypoint from README.md
=> Reverts parts of my last PR

build/tasks.ts
=> Clone exact vscode release branch when build task

packages/app/browser/src/app.html, packages/app/browser/src/app.scss, packages/app/browser/src/app.ts
Issue:
On initial welcome/login screen of binary, no error message is displayed in the event of an incorrect password. (See https://github.com/codercom/code-server/issues/55)
Changes:
Adds simple logic and styling for error display. Currently is of identical styling/design to the `coder.com` login page.
Test Environment:
OS: Mac OS High Sierra (10.13.6)
Browser: Google Chrome 72.0.3626.109 (Official Build) (64-bit)
(Result: Pass! Compile was successful and everything functions as expected)
Caveats:
None that I can think of at the moment. (I mean, the error message is hard coded. But this page has only one input and the page only has one purpose and does exactly one thing. So I don't know that this is necessarily a bad thing)
=> Add error message for incorrect password. Fix issue #55

Dockerfile
Also improves installation of runtime deps.
Closes #221
Closes #230
Closes #203
=> Dockerfile: include git

doc/admin/install/digitalocean.md
-p80 doesn't work, as -p isn't a variable, This adds a space that does just that.
No
=> Fixing broken syntax in the run command

doc/admin/install/aws.md, doc/admin/install/digitalocean.md, doc/admin/install/google_cloud.md
Security links were broken in the cloud setup guides.
No.
=> Fix security links in cloud setup guides

deployment/aws/deployment.yaml, deployment/deployment.yaml
Fixes #60 by adding support for Kubernetes. This deploys code-server, Contour for ingress controller, and Cert Manager for Let's Encrypt certificates, with persistent storage with AWS EBS volumes. Also, I left the Dockerfile I used for golang development. If there's a public push of this somewhere it would be great to document how you can create base images with the right tooling up front. 
This is also somewhat opiononated in that it's using AWS EBS volumes, but can be adapted for many use cases. I wasn't sure how that might get organized within the repo. 
Signed-off-by: Steve Sloka <slokas@vmware.com>
#60 
// cc @jbeda
=> Add support for Kubernetes 

doc/self-hosted/index.md
should add one line `proxy_set_header Accept-Encoding gzip; `  or you may get a  `Cannot GET /` error.
=> update nginx config to avoid  `Cannot GET /` error.

README.md
Some people might think this is a catch-all for every VS Code need in the browser, I'm just informing them that only the open source extensions can be used (i.e. no VS Live Share, etc.)
Nope.
=> Add note about extensions needing to be OSS

packages/vscode/src/workbench.ts
Adding a folder to a workspace results in a failure to reload the workspace. This was due to the workspace URI being invalid. The scheme (https://tools.ietf.org/html/rfc3986#section-3.1) for the URI was actually the path to the workspace configuration file, so the URI would always fail to parse upon workspace initialization.
This PR will ensure that the configuration path is actually defined as a valid `file://` URI, instead of simply casting it.
Fixes https://github.com/codercom/code-server/issues/309
=> Ensure workspace configPath is a valid URI object

packages/protocol/src/browser/modules/fs.ts, packages/protocol/src/common/proxy.ts, packages/protocol/src/node/modules/fs.ts, packages/server/src/vscode/bootstrapFork.ts
I benchmarked using `stat` across 10k files, with the current batch settings it seems to result in around a 1.5-1.9 increase in speed when ran locally. 
I'm not sure what the optimal batch size and timeout are, but I played around with how responsive the terminal felt and went with something that seemed reasonable. During load the terminal is much more responsive, but we might be able to further improve.
**Edit**: It looks like the remaining lag on the terminal during load is due to either the client parsing all the messages sent back to it from all the batched calls or the server stringifying all those messages (probably some of both). I suppose the only way to make it better is to somehow make `JSON.parse` and `JSON.stringify` asynchronous and low-priority for messages that don't need …
=> Watcher and initial load performance improvements

README.md
The discord badge wasn't at a high enough quality. This changes it to a version by Shields. I've also linked our MIT license.
#27 
#360
=> Add higher quality Discord badge and add a link to the license badge.

packages/protocol/src/browser/client.ts, packages/protocol/src/browser/modules/child_process.ts, packages/protocol/src/browser/modules/fs.ts, packages/protocol/src/browser/modules/net.ts, packages/protocol/src/browser/modules/node-pty.ts, packages/protocol/src/browser/modules/spdlog.ts, packages/protocol/src/browser/modules/stream.ts, packages/protocol/src/common/proxy.ts, packages/protocol/src/node/server.ts, packages/vscode/src/workbench.ts, scripts/vscode.patch
We already reconnect the web socket when it drops but we also need to restart/reconnect services that started before the disconnection.
This PR will do that for the following:
Won't be in this PR:
- Shared process
Other:
=> Handle disconnects

package.json, scripts/webpack.client.config.js, yarn.lock
Cookie's are not sent with url's in -webkit-mask so we
embed the svg's directly in the css.
=> Fix icons on safari when using cookie authentication

packages/vscode/src/workbench.ts
I'm not sure if this is the best way to handle it, but this creates the backup workspace file. It's mostly just to prevent the errors from appearing when the backup workspace file doesn't exist or is invalid since we're not actually using this anywhere (but we probably should).
There is also the history service that would probably be good to add, and maybe some others. It's possible we might want to try to include from `app` instead of `workbench.main` but I believe we tried that before and it didn't go super well. It's possible we just need to go through and make sure everything provided there is re-implemented on our side.
- Fixes #399
- Fixes #332
=> Initialize backup service

packages/protocol/src/browser/client.ts, packages/protocol/src/common/connection.ts, packages/protocol/src/node/server.ts, packages/protocol/src/proto/client.proto, packages/protocol/src/proto/client_pb.d.ts, packages/protocol/src/proto/client_pb.js, packages/server/package.json, packages/server/src/cli.ts, packages/server/src/vscode/sharedProcess.ts, packages/server/yarn.lock, packages/vscode/src/fill/environmentService.ts, packages/vscode/src/fill/paths.ts
Mirrors vscode CLI options `--user-data-dir` and `--extensions-dir`.
Allows inheriting local VS Code configuration (eg. `--user-data-dir ~/.config/User --extensions-dir ~/.vscode/extensions`).
=> Add flags for customizing user data dir and extensions dir

Dockerfile, README.md
- Adds dumb-init so closes #407, closes #361, closes #383
- User mode docker so closes #192, closes #65
- Uses latest docker ubuntu instead of 18.10 which is the rolling tag so
closes #404
Thanks to @RichardMcSorley and @sr229
=> Significantly improve the Dockerfile

doc/self-hosted/index.md
`code server -o` will just create/open the file/folder called **server**
No
=> Fix typo: doc/self-hosted/index.md

Dockerfile
This ensures a emptydir volume if the user forgot to mount. This allows OpenShift compatibility and solves
Docker issues.
This fixes #459 and #469 partially
=> [GH-459] explicitly create a volume and set permission for project dir

scripts/webpack.client.config.js
Fixes issue #510.
Fixed by disabling caching for all `*.html` files in service worker definition for Workbox.
- Chrome 75.0.3768.0
- macOS 10.14.4
- Docker 2.0.0.3. 
- installed PWA
Ran using `docker run -it -p 127.0.0.1:8443:8443 -v "$HOME/projects:/home/coder/projects" codercom/code-server --allow-http` then served with valid cert using `ngrok http 8443`.
=> Fix password sign in with service-worker

packages/logger/package.json, packages/logger/src/extender.test.ts, packages/logger/src/extender.ts, packages/logger/src/logger.ts
Adds `logger.extend(<Extender>)` API along with GCP stackdriver extender.
=> Add GCP logging extender

packages/server/src/cli.ts, packages/server/src/vscode/bootstrapFork.ts, packages/vscode/src/fill/environmentService.ts, packages/vscode/webpack.bootstrap.config.js, scripts/vscode.patch
Opted to just run VS Code's CLI with a small modification to ensure it always only does extension management. Not sure if this is the best way. We could directly import the file but then there were Typescript errors that I wasn't sure how to solve cleanly.
Also wasn't sure how to make Commander accept variadic options for an option. Maybe it's not possible?
=> Add flag to install an extension from the command line

packages/ide/src/client.ts
Control W closes the browser window instantly without respect for unsaved work. This shows a prompt asking if you want to leave.
#53
=> Add confirmation for closing window

build/tasks.ts, packages/app/browser/src/app.ts, packages/app/browser/webpack.config.js, packages/dns/webpack.config.js, packages/server/src/cli.ts, packages/server/src/server.ts, packages/server/webpack.config.js, packages/vscode/webpack.bootstrap.config.js, packages/web/src/index.html, packages/web/webpack.config.js, scripts/webpack.client.config.js, scripts/webpack.general.config.js
=> Make assets unique

packages/vscode/src/vscode.scss, scripts/vscode.patch
=> Hide titlebar controls and fix menubar toggle

packages/server/src/cli.ts
Allows code-server to bind on a unix socket. Fixes https://github.com/codercom/code-server/issues/561
=> Add --socket flag

packages/vscode/src/fill/vscodeTextmate.ts
Removes the need to read each grammar from the FS on each load. Results in significantly faster syntax highlighting. 
Fixes https://github.com/codercom/code-server/issues/18.
=> Include grammars in bundle

packages/server/src/cli.ts
Shows link for HTTPS or HTTP based on flags used on running. Let users know if telemetry is disabled.
n/a
=> Offer https/http url based on schema

scripts/vscode.patch
Fixes markdown preview from stealing focus away from the editor while typing
fixes #543
=> Fix markdown preview focus

packages/ide/src/fill/electron.ts, packages/protocol/README.md, packages/protocol/src/browser/client.ts, packages/protocol/src/browser/modules/child_process.ts, packages/protocol/src/browser/modules/fs.ts, packages/protocol/src/browser/modules/net.ts, packages/protocol/src/browser/modules/node-pty.ts, packages/protocol/src/browser/modules/spdlog.ts, packages/protocol/src/browser/modules/stream.ts, packages/protocol/src/browser/modules/trash.ts, packages/protocol/src/common/proxy.ts, packages/protocol/src/common/util.ts, packages/protocol/src/node/modules/child_process.ts, packages/protocol/src/node/modules/fs.ts, packages/protocol/src/node/modules/net.ts, packages/protocol/src/node/modules/node-pty.ts, packages/protocol/src/node/modules/spdlog.ts, packages/protocol/src/node/modules/stream.ts, packages/protocol/src/node/server.ts, packages/protocol/test/child_process.test.ts, packages/protocol/test/fs.test.ts
=> Fix coping and moving files around using the file tree

packages/vscode/src/fill/menuRegistry.ts
The "reveal in finder/explorer" option has no utility in the browser and causes a page to reload to invoke. This PR simply removes the option from the context menu to avoid mistakenly causing a refresh/confusion.
fixes #576
=> Remove reveal in finder

packages/server/src/cli.ts, packages/server/src/vscode/sharedProcess.ts
Currently there is no easy way to run `code-server` if disto's "stock" `libstdc++` package is too old because `code-server`  does not respect `LD_LIBRARY_PATH` on Linux.
Even if I set `LD_LIBRARY_PATH` I get this error:
```
...
INFO  Starting shared process [1/5]...
WARN  stderr {"data":"/export/home/fedor.kalugin/cli-linux-x64: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /export/home/fedor.kalugin/cli-linux-x64)\n/export/home/fedor.kalugin/cli-linux-x64: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required
by /export/home/fedor.kalugin/cli-linux-x64)\n/export/home/fedor.kalugin/cli-linux-x64: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found
(required by /export/home/fedor.kalugin/cli-linux-x64)\n"}
INFO  Starting shared process [2/5]... …
```
=> Respect LD_LIBRARY_PATH when forking on Linux

doc/admin/install/aws.md, doc/admin/install/digitalocean.md, doc/admin/install/google_cloud.md
=> Remove broken links

packages/protocol/src/browser/client.ts, packages/protocol/src/common/connection.ts, packages/protocol/src/node/server.ts, packages/protocol/src/proto/client.proto, packages/protocol/src/proto/client_pb.d.ts, packages/protocol/src/proto/client_pb.js, packages/protocol/test/server.test.ts, packages/server/src/cli.ts, packages/server/src/vscode/sharedProcess.ts, packages/vscode/src/fill/environmentService.ts, packages/vscode/src/fill/paths.ts, scripts/vscode.patch
=> Extra extensions directories

build/tasks.ts, scripts/build.sh
Should fix the version flag not reporting correctly as well as enable
the service worker and prevent the 404 hmr requests again.
Fixes #699.
=> Set NODE_ENV and VERSION when building

packages/server/src/cli.ts
When using port 0 on code-server, instead of printing the randomly generated port it will print URLs with port 0. This fixes that by getting the port from the server when printing the URL.
There are also some logging consistency changes in there as well, as HTTP messages were being printed even if sockets were being used.
Closes #779.
=> Use port from server.address() when printing the URL

README.md
This is a doc change to provide way to debug golang code using Go extension w/ code-server. Additional option is required when launch the code-server image.
#725
=> Update READE to add know issue for golang debug

doc/admin/install/aws.md, doc/admin/install/digitalocean.md, doc/admin/install/google_cloud.md
In url specified by `wget`, there are unnecessary `-`s.
Unsure.
=> Fix typos in wget url

doc/self-hosted/index.md
Fixes the screenshot URL in the self-hosted documentation.
=> Fix self-hosted documentation screenshot URL

packages/web/src/index.html, scripts/webpack.client.config.js
This addresses #670 by making the service worker register at the base of the mount. I also changed it so that workbox is hosted from local and not a CDN. This helps simplify CSP issues that pop up when mounting as part of a larger site. There are still quite a few other ones once we start talking plugins but this is a start.
Closes #670.
Note: this was originally opened in #722 by @geiseri but blocked by inactive user and no PGP signature.
=> Fix service worker path

scripts/webpack.client.config.js
I run code-server behind an authenticating Kubernetes Ingress which sets a cookie after a successful login is performed. Since this cookie is not set when fetching the manifest, the fetch fails and gets redirected to the authentication page, breaking code-server completely.
Adding this attribute to the link tag causes browsers to fetch the manifest including cookies previously set. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link for more information.
#822
=> Add `use-credentials` to fetch manifest with cookies

doc/quickstart.md
Add init docs so people have an idea what to do when starting up a service.
Resolves GH-947
=> [doc/quickstart] add init docs

doc/examples/kubernetes.aws.yaml, doc/examples/kubernetes.yaml
Signed-off-by: yeya24 <yb532204897@gmail.com>
Update image tag to v2
=> update image tag to v2 in yaml

doc/quickstart.md
This is the same PR but with some fixes for v2.
=> [doc/quickstart] use version from GH-379

src/node/server.ts
Fixes #1050.
@antofthy this will touch `~/.local/share/code-server/heartbeat` (or wherever the user data directory is located) once a minute as long as there is an active browser connection. No need to review the code (although I would welcome it if you feel like it) but I'm pinging you to verify this'll work out for your use case.
=> Add heartbeat file

Dockerfile
Fixes #1188 
Fixes issue with permissions mounting in directories in the container. Folders are generated by root causing issues when the container user "coder" wants to create sub-folders. This fix solves it, at least on Crostini (ChromeOS)
=> Update Dockerfile to fix EACCES issue on mount

.drone.yml, .travis.yml, Dockerfile
This will migrate code-server to Drone CI which allows ARMv7 and ARM64 builds. This is currently being tested on my LKGR repo so don't merge it yet
closes #1258 
closes #35
=> Drone CI migration

README.md
The build instructions on `README.md` referred to the wrong place to find the VS Code Version.
=> Reflect new location of vscodeVersion

src/media/manifest.json
Improves usability by making use of fullscreen when installed as pwa.
=> Updates manifest.json

.drone.yml, scripts/ci.bash
The cron script doesn't work anymore with the new release architectures, it's a good time to switch to uploading automatically.
Don't know if there's an easy way to test it without creating a tag?
=> Automatically push releases to GCS

doc/FAQ.md
dear owners,
this is a simple copy-editing pull request. The issue regards verb-agreement. In cases like this the past-participle, run, is the correct form. Thank you for your time, and thank you for your superb application.
all best,
Dr. Matthew Jeffrey Abrams
=> verb agreement typo in FAQ

ci/vscode.patch, src/node/app/update.ts, test/update.test.ts
Rename the old directory with a timestamp before moving the new directory into place.
Also has a minor fix for a notification saying the update failed when it didn't (`isLatest`
won't be true since that version is still technically the older version).
Fixes #1483 .
=> Back up old directory when updating

ci/vscode.patch
=> Send report issues to code-server repo

doc/FAQ.md, package.json, src/browser/pages/home.html, src/node/app/api.ts, src/node/app/dashboard.ts, src/node/app/login.ts, src/node/app/proxy.ts, src/node/app/update.ts, src/node/app/vscode.ts, src/node/cli.ts, src/node/entry.ts, src/node/http.ts, test/cli.test.ts, yarn.lock
This PR adds the ability to proxy HTTP ports through code-server.
To do this, you pass a domain on the command line. For example:
```
code-server --proxy-domain coder.com --proxy-domain test.coder.com
```
Domains can be in the format `coder.com` or `*.coder.com` and the flag can be repeated to add as many domains as you want.
When code-server encounters `[number].[domain]` in the host header it'll proxy to the port indicated by `[number]` if `[domain]` matches one of the provided proxy domains. For example, going to `8080.coder.com` in this example would proxy code-server to itself.
When authenticating the cookie will be set against the highest-level proxy. So in this example if you logged in at `8080.test.coder.com` the cookie would be set against `coder.com` since that's the highest …
=> HTTP proxy

ci/code-server.sh
=> Fix code-server.sh script on macOS

.eslintrc.yaml, doc/FAQ.md, package.json, src/node/app/login.ts, yarn.lock
=> Add basic rate limiting to login endpoint

.gitignore, ci/release-image/Dockerfile, ci/release.sh, src/node/cli.ts, src/node/entry.ts, test/cli.test.ts
=> Deprecate --host and --port in favour of --bind-addr

ci/vscode.patch, yarn.lock
Also remove some unused imports that were causing build errors (they
were left over from the fix that allowed installing any extension kind).
=> Remove transformer file

README.md
Apple calls the OS currently macOS.
=> fix macOS spelling

src/node/entry.ts
=> Unset $PASSWORD after grabbing it

.eslintrc.yaml, ci/README.md, ci/build/code-server.service, ci/build/nfpm.yaml, ci/dev/vscode.patch, ci/steps/publish-npm.sh, doc/FAQ.md, package.json, src/browser/pages/login.html, src/node/app/login.ts, src/node/cli.ts, src/node/entry.ts, src/node/http.ts, src/node/settings.ts, src/node/util.ts, test/cli.test.ts, yarn.lock
=> Add support for a YAML config file

.github/workflows/ci.yaml, README.md, ci/README.md, ci/container/arm64/Dockerfile, ci/container/arm64/README.md, ci/dev/lint.sh
Closes https://github.com/cdr/code-server/issues/1656
=> Downgrade CI to Debian 8 for glibc 2.19

.github/issue_template.md, .github/workflows/ci.yaml, .gitignore, ci/steps/publish-npm.sh, ci/steps/release-static.sh, ci/steps/release.sh
=> Workaround for GH Actions stripping permissions

ci/dev/vscode.patch, src/node/app/static.ts, src/node/app/vscode.ts, src/node/util.ts
Fixes #1659
Fixes #1642
I tested:
The strat is to convert the path on the server end instead of on the browser end since the latter ends up using the browser's OS.
=> Fix paths from Windows client to non-Windows server

README.md, ci/README.md, ci/build/build-release.sh, ci/build/npm-postinstall.sh, ci/build/release-github-draft.sh, doc/guide.md, package.json
This release fixes bugs introduced with the release of v3.3.0
- We've reverted to VS Code 1.45.1 due to bugs in 1.46 #1667
- Accessing code-server from a web browser on Windows has been fixed #1642
- Search in project has been fixed #1665
- The glibc requirement on static releases has been lowered to v2.19 #1656
=> Release v3.3.1

src/node/cli.ts, src/node/entry.ts, test/cli.test.ts
=> Allow user-data-dir and extension-dir in config.yaml

doc/FAQ.md, doc/guide.md
=> Add blank screen problem with iPad to FAQ

doc/FAQ.md, doc/guide.md
=> Improve clarity in guide and fix typo in FAQ

ci/build/build-packages.sh, ci/build/build-static-release.sh
Only for linux amd64 users which is the majority of our userbase.
Closes #1664
=> Make automatic updates on v3.2.0 work again

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/extension-request.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/issue_template.md
=> Add issue template for extension request

.github/issue_template.md, README.md, ci/build/release-github-assets.sh, doc/FAQ.md
=> More questions in the FAQ

ci/dev/vscode.patch
=> Always create globalStorageHome

README.md, doc/guide.md, doc/install.md, install.sh
Closes #1803
Updates #1802
cc @zathras777
=> Add FreeBSD support to install script

doc/FAQ.md
Few typos found in the doc/FAQ.md were fixed.
=> fix typos in doc/FAQ.md

ci/dev/vscode.patch
=> Initialize config and use correct settings path

ci/dev/vscode.patch
For some reason it only affects the extension host socket (something to
do with passing it via IPC?) but I changed both just to be sure.
Fixes #1795.
=> Fix connections sticking around indefinitely

ci/dev/vscode.patch
Pretty straightforward update.
- Refactor `readFileStream` in file system provider to use VS Code's instead of copying the code.
- Update fix that allows any extension to be installed since that area was refactored in 1.47.0.
- Update location of Firefox scm viewlet fix (it was moved to another file).
- Remove csp fix since it's included in 1.47.0.
=> Update VS Code to 1.47.0

ci/dev/vscode.patch, src/browser/pages/vscode.html
=> Update to VS Code 1.47.2

doc/guide.md
Added Nginx instructions for people who prefer to use this instead of Caddy
See for example issue #770
=> Add Nginx instructions to guide

doc/guide.md
Made it a full alternative to caddy, just so we don't ever have to explain how to configure Nginx again.
=> doc/guide: Improve nginx docs

src/node/app/vscode.ts, src/node/settings.ts
Provide a way for the shell script running in the docker container to get the url query.
=> feat: persist route query to local

src/common/util.ts, src/node/entry.ts, src/node/http.ts
Adds a str param to `common/util::plural` for pluralizing a string.
Applies plural to entry.ts.
No linked issued; update is sufficiently minor.
=> Update 'plural' common util

src/common/emitter.ts, src/common/types.ts
Adds a reusable Callback type that is applied to emitter.ts for improved readability/simplicity. Issue not linked because the change is minor.
=> Add Callback type

.eslintrc.yaml, ci/build/build-code-server.sh, ci/dev/watch.ts, src/browser/pages/login.html, src/browser/pages/login.ts, src/browser/pages/vscode.html, src/browser/pages/vscode.ts, src/node/cli.ts, src/node/http.ts, src/node/settings.ts, src/node/util.ts, test/socket.test.ts, test/util.test.ts, tsconfig.json
A few changes that (I hope) improve the developing experience a little.
=> qol changes

doc/guide.md
=> instanceIp --> username@instanceIp

.github/ISSUE_TEMPLATE/config.yml, .github/issue_template.md, doc/FAQ.md
=> Switch from subreddit to GitHub discussions for support

ci/dev/vscode.patch
No patch updates this time except it seems a newline was added to the `package.json`.
=> Update to VS Code 1.48.2

ci/images/centos7/Dockerfile, ci/images/debian8/Dockerfile, ci/steps/release-packages.sh
See #1894
See #1892
See #1810
See #1904
=> Ship with node 12

doc/CONTRIBUTING.md
Much easier for users to use our CI scripts instead of each individual
yarn step.
=> doc: Simplify build process docs

ci/dev/vscode.patch, src/node/cli.ts
Fixes #1744
Updates #1981
Branched off https://github.com/cdr/code-server/pull/1779
=> Add proposed API flag

src/browser/serviceWorker.ts
We need the handler to be recognized as a PWA but we can just let the
original offline browser message show instead of our own message.
See #1925 and #1979.
=> Remove custom offline text

ci/build/code-server-user.service, ci/build/nfpm.yaml, doc/guide.md, doc/install.md, install.sh
systemd's user units are buggy on certain versions
and do not linger by default.
Closes #1771
Closes #1673
Closes #1882
Closes #1861
See #1903
=> Bundle systemd system unit

ci/dev/vscode.patch, src/node/cli.ts, src/node/entry.ts
Add initial support for opening files / folders in running code-server instance.
Capabilities:
- Open an existing/new file(s) in running instance
```shell
$ code-server --reuse-window --open-in foo.txt
$ code-server -oi foo.txt -r
```
- Open an existing folder in a new window
```shell
$ code-server --new-window --open-in path/to/project
$ code-server -oi path/to/project -n
```
Current limitations:
- unable to open a file in a new window, only folders
- unable to use addMode feature
- others...
#164
=> Allow opening files, folders, and workspaces in existing code-server from CLI

ci/build/clean.sh, ci/release-image/Dockerfile, ci/release-image/entrypoint.sh, ci/steps/release-packages.sh
Needs to be reflected in the documentation and the dockerhub description
now.
Closes #881
cc @avaidyam
=> docker: Allow passing $DOCKER_USER to set the username in the container

package.json, src/node/cli.ts, src/node/entry.ts
- Always launch into the existing instance if there is a socket
- VS Code sets this variable when the socket is created so if this is set it should mean the socket exists
- Unset for `yarn watch` so you can still develop code-server inside code-server
- Otherwise it would just send to the socket instead of launching
- Avoid the config info line when sending to an existing instance
=> Remove open-in flag

ci/dev/vscode.patch
Confirmed that it fixes https://github.com/rust-analyzer/rust-analyzer/issues/5892 (reported in https://github.com/cdr/code-server/issues/2021).
=> Patch VS Code to wait for storage write

ci/release-image/Dockerfile, ci/release-image/entrypoint.sh, doc/install.md
We do not try renaming $HOME anymore as there is no good way
to do it.
We also only try to convert if the user hasn't been changed.
Finally I added usage to the docker docs in install.md
Closes #2056
=> docker: Fix $DOCKER_USER

ci/build/build-release.sh
```
KEEP_MODULES=1 ./ci/steps/release.sh && node ./release --auth=none
```
Can be ran to build & test a release quickly.
=> Allow building release without deleting existing node_modules

ci/dev/vscode.patch
I didn't have to make any changes except add a new file to the `coder.js` build script.
Might fix #1015 but I don't have any means of testing it.
=> Update VS code to 1.49.3

src/node/cli.ts, src/node/http.ts
- Port 80 didn't work with bind-addr
- [::] didn't work
=> HTTP server listen fixes

ci/dev/vscode.patch
=> Patch VS Code to avoid deleting extension dependencies

src/node/plugin.ts
- Still loads all plugins from the `plugins` directory as before
- But now `PLUGIN_DIR` will set that directory instead of being used to specify an individual plugin
- This is the directory I envision being used for distributing code-server with plugins or where plugins would be placed for running instances of code-server in production by users
- `PLUGIN_DIRS` can be used to set multiple individual plugins if you don't want to move them into a single directory
- Really only intended for development
Lemme know if we wanna change this up, this is just based off the VS Code plugin structure (except they use command line flags and not environment variables).
Closes #2122.
=> Add variables to better customize plugin directories

src/node/cli.ts, src/node/coder-cloud.ts, src/node/entry.ts
As discussed, the team believes `--link` to be more succinct while still expressive.
=> cloud: Rename --coder-bind to --link

install.sh
Updates #1729
To fully close that issue see the various TODOs.
=> install.sh: Allow installing directly onto a remote host

src/node/plugin.ts
I neglected to realize that "".split(":") is an array with "" in it.
=> Filter blank plugin directories

ci/build/test-standalone-release.sh, ci/dev/vscode.patch, src/node/cli.ts, src/node/entry.ts, src/node/socket.ts, src/node/util.ts, src/node/wrapper.ts, test/cli.test.ts
Closes #2036 
Refactored the wrapper a little bit as well so we don't have to do all the socket checking stuff in both the parent and the child.
=> Make opening in an existing instance work outside code-server

ci/dev/vscode.patch, src/browser/pages/vscode.html, src/browser/pages/vscode.ts
Planning on making a 3.6.1 release with this.
=> Update VS Code to 1.50.0

README.md, ci/release-image/Dockerfile, ci/release-image/entrypoint.sh
=> Remove unnecessary whoami

ci/release-image/entrypoint.sh
If do not update the UID within the passwd database to match whatever
uid the container is being ran as, then sudo will not work when renaming
the user to match $DOCKER_USER as it will complain about the current
user being non-existent.
Updates #2213
=> release-image: Remap UID within the image before handling $DOCKER_USER

install.sh
Closes #1729
Last TODO left on that issue. I removed making remote installation on a non internet connected instance work as I don't think that's a very common use case and if it is, manual installation isn't hard anyway. It'll require lots of churn and make the install script quite abstract and hard to understand.
=> install.sh: Allow customizing remote shell for remote installation

README.md, doc/CONTRIBUTING.md
The first in a series of edits to the code-server docs.
Changes include copy edits and basic structural reorg to README.md, CONTRIBUTING.md for clarity. All feedback regarding changes welcome.
~If it's not a problem, I'd like to move contributing to the root level a la other open-source projects.~
=> Docs copyedits: README.md + CONTRIBUTING.md

ci/build/build-release.sh, ci/dev/vscode.patch, src/node/app/vscode.ts, src/node/http.ts
So far the only way I've been able to reproduce the initial connection failure is to spawn 10+ tabs at a time. What I saw was that sometimes the initial message from the client doesn't make it to `onControlMessage` callback which causes the handshake to hang. I don't know yet why that is but for now I've made it so both ends will initiate the handshake so no matter what order or when they start listening everything should be fine.
So far with this I haven't seen any connection failures due to incomplete handshakes (although when I spawn too many windows my browser seems to just not make websocket connections in the first place, but that results in different errors than the reported ones).
=> Experimental initial connection fix

ci/dev/fmt.sh, doc/FAQ.md, doc/guide.md, doc/ipad.md, src/node/cli.ts, src/node/entry.ts, src/node/util.ts, test/socket.test.ts
=> Fix self signed certificate for iPad

.github/ISSUE_TEMPLATE/config.yml
adds Slack link to GitHub issues template, as suggested by @wbobeirne
=> add Slack link to issue template

ci/dev/vscode.patch, src/node/routes/static.ts
=> Fix 404 webviews and tar endpoint

src/node/routes/static.ts
I removed this under the impression the default was to allow it anywhere
but that's not the case. Since the service worker was already registered
in my browser I never got the error during testing.
=> Fix service worker not loading 

src/node/entry.ts, src/node/vscode.ts, src/node/wrapper.ts
This is to fix #2316.
Previously we only deleted `PASSWORD` in the child process but now it's deleted in the parent (which I think is good since that means it'll be hidden from the VS Code CLI spawn as well and anything else we might spawn from the parent in the future). 
But as a consequence the child no longer has access to `PASSWORD` and can't use it when parsing the arguments. This PR fixes that by passing the arguments from the parent to the child.
As a bonus this means we only have to do the parsing once, including if it gets restarted via a SIGUSR1.
Since it was getting a little convoluted with all the if statements I split out the child and parent process wrappers which I think makes it all a little more clear. Also was able to re-use `onMessage` from the VS Code wrapper.
=> Separate process wrappers and pass arguments

ci/build/release-github-draft.sh, ci/dev/vscode.patch, doc/install.md, src/node/routes/update.ts, src/node/update.ts
=> vscode: Show notification when upgrade is available

ci/dev/vscode.patch
Previously anything that wasn't "log" such as "warn" would end up doing
`logger[logger.warn]`. Would have caught this if I hadn't used `any`...
Fixes #2364.
=> Fix exthost error and warn logging

ci/dev/vscode.patch
Issue this PR solves: #1791
On a connection loss, the client attempts to reconnect up to twice in the background before displaying the reconnection pop-up.
=> Implement background reconnection

doc/npm.md
I have not tested this myself, but I am pretty sure you don't need the full Xcode installed to build native node modules, just the command line tools. https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md#solutions
=> Remove the "install Xcode" bit

doc/FAQ.md
Previously, the _How do I debub issues with code-server?_ section of FAQ was referencing `~/.local/share/code-server/logs`. For the more recent verions of code-server, it appears this log directory was renamed to `~/.local/share/code-server/coder-logs`
=> Add coder-log path to FAQ's 'How do I debug...' section

doc/guide.md
I found it so simple and beautiful to use a different method to get VS Code on my iPad running
=> Update guide.md for iPad simple setup

doc/triage.md
=> doc: Describe issue triaging

doc/guide.md, src/node/cli.ts, src/node/entry.ts, src/node/http.ts, src/node/routes/login.ts, test/cli.test.ts
=> Add hashedPassword config

.tours/contributing.tour, .tours/start-development.tour
The [CodeTour](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour) extension for VS Code gives users an interactive walkthrough of a codebase.
When the repo is first cloned (and the CodeTour extension is installed), a dialog appears with the option to start a tour.
Tours can be viewed, edited, and "recorded" with the extension, or through editing the `.tour` file. I have created a a basic tour, but would love input from @code-asher and others on what areas of codebase to point new contributors to.
Since code-server is well-documented, perhaps this can be used as a way to show people what files are important. CodeTours can also prompt users to [execute shell commands](https://user-images.githubusercontent.com/116461/78858896-91912600-79e2-11ea-8002-196c12273ebc.gif). …
=> Add CodeTour

README.md, src/node/cli.ts
Looks like
```
-r --reuse-window         Force to open a file or folder in an already opened window.
-vvv --verbose              Enable verbose logging.
--link                 (beta) Securely bind code-server via Coder Cloud with the passed name. You'll get a URL like
https://myname.coder-cloud.com at which you can easily access your code-server instance.
Authorization is done via GitHub.
```
Based on commits by @JammSpread in #2405
Closes #2396
=> cli: Show beta flags in help output

doc/FAQ.md
=> FAQ.md: Add mention of hashedPassword

src/node/routes/index.ts
Sometimes I start with auth but then disable. Now I can just reload the
login page in my browser to be greeted with code-server.
=> routes: Redirect from /login when auth is disabled

install.sh
Update the install script to use `$ID_LIKE` where possible to detect similar distros.
Script now detects Amazon Linux as a .rpm-based distro; also de-duplicated checks for other distros.
Tested to work on:
- Alpine Linux, `ash`
- Amazon Linux, `bash`
- Arch Linux, `bash`
- Ubuntu, `dash`
Fixes #2343.
=> install.sh: Use $ID_LIKE to detect distro

ci/release-image/Dockerfile
Confused me in #2410, see #2455
debian:10 defaults to bash as $SHELL
=> release-image: Remove unnecessary call to chsh

ci/dev/reset-vscode.sh, package.json
This PR adds a new script to the root `package.json` called `vscode:clean` which resets `lib/vscode`. 
- add script to `./ci/dev/clean-vscode.sh`
- add script `vscode:clean` to `package.json` at root
Fixes N/A (no accompanying issue)
=> feat(local development): add vscode:clean script

doc/FAQ.md, doc/guide.md, src/node/cli.ts, src/node/entry.ts, src/node/http.ts, src/node/routes/login.ts, test/cli.test.ts
Capital letters in the CLI are evil.
cc @code-asher @JammSpread
=> cli: hashedPassword -> hashed-password 

ci/README.md, ci/build/build-code-server.sh, ci/build/clean.sh, ci/lib.sh, ci/steps/release-packages.sh, doc/npm.md, install.sh, lib/vscode/package.json, lib/vscode/src/typings/electron.d.ts, lib/vscode/yarn.lock
Updates #1826
Updates #1880
Updates #2320
Updates #2349
=> ci: Add support for FreeBSD to the build process

lib/vscode/extensions/github-authentication/src/githubServer.ts, src/common/util.ts, src/node/routes/static.ts, src/node/routes/vscode.ts
=> Fix GitHub auth

doc/CONTRIBUTING.md
This adds a minor detail to the updating VS Code section of the docs.
=> docs: add details to updating vscode section

ci/build/build-release.sh, ci/lib.sh
No open issue but see comments on #1883 and #2535.
=> Callback html

doc/FAQ.md
See also https://github.com/cdr/code-server/issues/2225#issuecomment-752687041
- Changed `echo` to `printf` to avoid newlines.
- Added an example to make it clear which `password` should be changed to `hashed-password`.
- Removed the double quotes from the sentence ``Of course replace `"thisismypassword"` with your actual password.`` to avoid potential confusion.
=> Small changes to the hashed-password FAQ

lib/vscode/src/vs/workbench/contrib/extensions/browser/extensionsViewlet.ts
Add a short message above the search box on the Extensions panel. This helps explain the extension divergence to the user.
If they click dismiss, it stores an item in localStorage to prevent the message from showing up on subsequent loads.
Builds off the work previously done by @cmoog in #2185 
And it uses the correct colors based on theme:
https://user-images.githubusercontent.com/3806031/104351495-b3b05b00-54c2-11eb-8c4a-fb0a4d90ac7e.MP4
Fixes #2132
=> feat(extensions): add helper header above extensions search

src/node/vscode.ts
Fixes VscodeProvider to correctly obey the ew parameter.
Based on changes by @rdbeach. See the previous commit.
=> vscode.ts: Fix close current folder

.gitignore, README.md, ci/README.md, ci/dev/postinstall.sh, ci/dev/test.sh, package.json, test/jest.config.js, test/package.json, test/tsconfig.json, test/yarn.lock, tsconfig.json, yarn.lock
This solution made possible thanks to @code-asher 
- refactor `jest` setup to play nicely with TS + `lib/vscode`
- add code coverage support
- add code coverage badge in readme
=> feat(testing): add code coverage

lib/vscode/src/vs/server/browser/client.ts
This event isn't sensitive, so it should be sent to all parent origins. Some situations may require running an iframe to code-server on a separate domain to the code-server instance, and they might want to listen to this event.
`window.location.origin` limited this event to only the same domain.
This does not change the iframe behavior in any other way. Iframes are still allowed by default unless explicitly blocked via response headers or another mechanism.
=> Send 'loaded' event to all parent origins

doc/ipad.md
Update the iPad docs with instructions on how to install the PWA.
See comment: https://github.com/cdr/code-server/issues/2586#issuecomment-767315912
=> doc/ipad.md: add install pwa

doc/ipad.md
This adds the `ctrl+c` workaround to the docs.
Related: #1343
=> doc/ipad.md: add ctrl c workaround

doc/guide.md
Caddy has new installation instructions for Debian.
Closes #2599
=> doc/guide.md: Update caddy install instructions

package.json, test/socket.test.ts, test/wtfnode.ts, yarn.lock
See my comments at
https://github.com/cdr/code-server/pull/2563#issuecomment-763394741
=> test: Switch from leaked-handles to wtfnode

src/node/proxy.ts, src/node/routes/index.ts, src/node/routes/pathProxy.ts, test/proxy.test.ts
=> Fix body proxying, redirect proxying and add tests 

ci/dev/fmt.sh, docs/CODE_OF_CONDUCT.md
As part of our effort to make the code-server community more inclusive, I'd like to propose adding a `CODE_OF_CONDUCT`
=> docs: add CODE_OF_CONDUCT.md

docs/FAQ.md, src/node/cli.ts, src/node/proxy.ts, src/node/routes/index.ts, src/node/routes/pathProxy.ts, test/proxy.test.ts
=> Add /absproxy to remove --proxy-path-passthrough

README.md, ci/README.md, ci/build/release-github-draft.sh, ci/helm-chart/Chart.yaml, ci/helm-chart/README.md, ci/helm-chart/values.yaml, docs/install.md, package.json
This PR is to generate a new release of `code-server` at v3.8.1
=> release: v3.8.1

test/package.json, test/util.test.ts, test/yarn.lock
This PR adds several unit tests for the `src/common/util` functions.
It increases our code coverage (Lines) from 46.88% to 49.53% (↑ 2.65%)
🟩 100% coverage for `src/common/util`
=> feat(testing): add unit tests for common/util

test/http.test.ts
This PR adds a few tests for `src/common/http`. Note: intentionally selected `add-unit-tests-constants` as the base since I branched off it.
It increases our code coverage (Lines) from 49.83% to 50.09% (↑ 0.0.26%).
🟩 100% Line coverage (last 100) for `src/node/http.ts`
=> feat(testing): add unit tests for src/common/http

README.md
Promote ease of adoption by placing the requirements in the README at the root folder level.
=> docs(README.md): update to include requirements

docs/FAQ.md
First pass on updating docs to indicate switch to Open-VSX.
Depends on #2659.
I'd appreciate any feedback!
=> docs: update FAQ with extension gallery info

package.json, src/node/constants.ts, test/constants.test.ts, test/http.test.ts, test/util.test.ts, yarn.lock
This PR refactors a few lines of code in `src/node/constants.ts` and adds a few unit tests to bring code coverage for the file to 100%.
- refactor `constants` and add `getPackageJson` function to make it easier to test
- add `@schemastore/package` to devDeps to get PackageJson type
- add unit tests for constants 
It increases our code coverage (Lines) from 49.53% to 50.09% (↑ 0.56%).
🟩 100% Line coverage (last 100) for `src/node/constants.ts`
TODOS
=> feat(testing): add unit tests for constants

docs/install.md, install.sh
From install.md, the path to install code-server on Linux Alpine is unclear.
#1430 recommends using the npm script, since the install script doesn't work.
=> docs: clarify Alpine install path in install.md

package.json, src/node/app.ts, yarn.lock
This adds the compression middleware with default settings. Fixes #2679. This greatly improves loading performance over my horrible internet!
**With compression:**
**Without compression:**
=> feat: use compression in express server

package.json, src/node/plugin.ts, test/plugin.test.ts
=> Allow plugins to register at the root

README.md, ci/README.md, ci/build/release-github-draft.sh, ci/helm-chart/Chart.yaml, ci/helm-chart/README.md, ci/helm-chart/values.yaml, docs/install.md, install.sh, package.json
This PR is to generate a new release of `code-server` at v3.8.1
And the Vim extension is working!!
=> release: v3.9.0

src/node/routes/health.ts, test/health.test.ts, test/httpserver.ts, test/test-plugin/src/index.ts
Was having problems with the healthz socket, turns out I forgot to `resume`. Added some tests while I was at it.
=> Fix healthz socket

lib/vscode/src/vs/workbench/contrib/extensions/browser/extensionsViewlet.ts, lib/vscode/src/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page.ts
When we moved the docs from `/doc` to `/docs` in #2669, I forgot to update this link.
This is the little helper shown in the Extensions panel, which links to our docs. This also fixes the links in the Welcome page.
Thank you to @kylecarbs @JammSpread @MarkAYoder for reporting these issues!
=> fix(vscode): update link in extensionsViewlet

lib/vscode/src/vs/server/node/channel.ts, lib/vscode/src/vs/workbench/contrib/terminal/node/terminalProcess.ts
Calling `this.process.dispose();` before `this.process.shutdown(true);` sets a flag `_isDisposed` to true.
This causes the `_kill()` procedure to exit early essentially making `this.process.shutdown(true)` a no op.
It's necessary to await on the shutdown because _kill() is an async function. Otherwise  `_isDisposed` will be set to true before actually killing the process regardless of the call order of `dispose` and `shutdown`.
Impact: Closing the session in the browser should now kill long running processes such as filesystem watchers or services started in the terminal.
=> Fix terminal process leak when closing the window.

docs/FAQ.md, docs/install.md
Adds an initial section in install.md for deploying code-server to app engines.
closes #2711,  #2686
=> docs(install): add Azure and Heroku

test/emitter.test.ts
This PR adds a few tests for `src/common/emitter.ts`.
It increases our code coverage (Lines) from 50.09% to 50.26% (↑ 0.17%).
🟩 100% Line coverage (last 100) for `src/common/emitter.ts` and also 100% coverage for `src/common`
=> feat(testing): add unit tests for emitter

src/browser/pages/login.css
Resolves: #2769 
Adds media queries and min body dimensions to the Sign In Page
- A typical "sm" breakpoint of 600px is used to toggle the sign in card to a column
- The min page dimensions are that of an iphone 5
=> fix: Responsive Sign In Page

ci/README.md, docs/FAQ.md
This PR updates the `ci` docs with steps for updating the homebrew package more easily using `brew bump-forumla-pr`.
TODOS
=> docs(ci): update release steps with homebrew bump

.github/workflows/ci.yaml, ci/build/test-standalone-release.sh
This PR fixes #2480 .
- add step to remove docker images on `linux-arm64` ci job (thanks to @code-asher for the tip, @vapurrmaid for the refactor!)
- add step to remove release-packages and test/videos on the `test` job 
- changes the extension used in `test:standalone-release`
I suggest changing the extension away from the Python because it's notorious for breaking in code-server. A theme extension changes less frequently and is much more reliable for testing.
=> fix(ci): add step to remove docker images on linux-arm64 

README.md
This PR adds a release shield to the `README`
=> docs(README): add release shield

README.md, ci/README.md
This PR:
- adds a shield linking to the docs
- updates the release steps in the `ci/README`
=> docs(README, ci): add docs shield with link to version docs

README.md, docs/install.md
I have been working on the [cdr/deploy-code-server](https://github.com/cdr/deploy-code-server) project which includes one-click buttons and guides to deploy code-server to a cloud provider, such as Linode or Heroku.
@jsjoeio and I have been discussing including parts of this in the code-server repo, as it is a great way to get started using it. It is only a few steps to get an environment that can be accessed from anywhere!
However, I think that we cannot simply add all of the docs and guides to this repo. Here's why:
- Certain providers (such as Heroku and Railway) require that some info lives in the base directory of the repository, such as the [heroku.yml](https://github.com/cdr/deploy-code-server/blob/main/heroku.yml) flle. This would mess up code-server's folder structure.
- Since …
=> add instructions for deploying to a cloud provider 

docs/npm.md, package.json
This PR fixes #2745 by adding extra information regarding Node.js requirements.
TODOS  
How I tested versions of node:
1. `nvm install 14`
2. `rm -rf node_modules`
3. `yarn`
4. `cd lib/vscode && npm rebuild`
5. `yarn watch`
6.  Navigate to localhost:8080 and see if code-server works
=> docs(npm): update node requirements

ci/dev/update-vscode.sh
This PR modifies the `update-vscode.sh` script and greatly improves it:
- add more comments
- get latest version of vscode from `package.json`
- force commit conflicted files
- add more detailed PR message in draft PR
Fixes #2787
=> dev(update-vscode.sh): get latest vscode version and force commit files

lib/vscode/yarn.lock, package.json, yarn.lock
Selectively upgrade only `tar` in `lib/vscode`, and then upgrade `stylelint` with `yarn upgrade-interactive`, and then add `node-forge` in resolutions.
Closes #2860.
=> chore: update vulnerable dependencies

.github/workflows/ci.yaml
* Run builds when changes are pushed to the main branch, or for pull
requests opened against the main branch. This is a subtle change
in behavior because, previously, builds would've run on pushes to
any branch, regardless if a pull request is open yet.
* Update to GitHub actions/checkout v2, which performs a shallow
clone by default, which should speed up the build.
Closes: #2559 (:crossed_fingers:)
--
I believe that this should work, since only one job receives secrets according to the workflow definition (unless there's an administrative setting somewhere for global secrets passed using environment variables). However, I think the only way to be certain is to merge this and then open a pull request from a fork. If this breaks things or doesn't work correctly, we can always revert and …
=> chore: run builds on pull requests

README.md, src/node/cli.ts, src/node/coder_cloud.ts
Corresponds with https://github.com/cdr/cloud-agent/pull/12
=> rename references of "coder could"

.github/dependabot.yml
This PR fixes #2898.
- @jawnsy is already a member @cdr/code-server-reviewers so he will see these PRs regardless but it also lets anyone else come in and review without them having to manually review him.
- no need to assign them all to @jawnsy - there are too many 😛
=> fix: remove reviewers/assignees for dependabot

lib/vscode/src/vs/server/common/cookie.ts, lib/vscode/src/vs/workbench/browser/parts/titlebar/menubarControl.ts, src/node/routes/login.ts, test/e2e/logout.test.ts
This adds a new option to the Application Menu called Log out. It deletes the code-server cookie and logs a user out.
Fixes #778
=> feat(lib/vscode): add log out to application menu

package.json, yarn.lock
This PR changes the upgrades for `ts-node` to bug fixes only.
We're doing this because when dependabot opened #2919 it broke local development. We didn't catch it because all the tests were passing.
=> fix(dev-deps): limit ts-node upgrades

install.sh
This PR fixes two links in the install.sh.
=> fix: use main instead of version in install.sh

ci/lib.sh
This PR refactors `lib.sh` to catch and report an error getting the get_artifacts_url.
It was noticed while working on a release in #2953.
=> refactor: add check for artifacts url in lib.sh

ci/lib.sh
This PR refactors get_artifacts_url in lib.sh to work of the version branch instead of the head sha.
=> refactor: change get_artifacts_url in lib.sh

src/node/routes/vscode.ts
I have no idea if this fixes https://github.com/cdr/code-server/issues/2975 since I don't have a way to test.
TODOS
=> Don't send permessage-deflate header if not supported

.github/dependabot.yml
This PR tells dependabot to ignore version updates for @types/node 14.x. 
Related:
- https://github.com/cdr/code-server/pull/2989#issuecomment-809551319
=> chore(dev-deps): add ignore block to dependabot config for @types/node

package.json, src/node/wrapper.ts, yarn.lock
This PR fixes how we spawn a child_process and bumps `ts-node`.
(H/T to @cspotcode for identifying this after we opened an issue in `ts-node`)
Related:
- https://github.com/TypeStrong/ts-node/issues/1283#issuecomment-807704228
- Reverts https://github.com/cdr/code-server/pull/2962
- https://github.com/cdr/code-server/pull/2965
=> fix(dev-deps): update ts-node and spawn

.github/ranger.yml, docs/FAQ.md
This PR helps automate how we handle extension request issues. It also updates the docs for installing OpenVSX extensions via the command line.
TODOS
=> feat(ranger): add action for extension-request

package.json, yarn.lock
This PR bumps `@types/node` to `12.20.7`
Tested locally using `node 12.20.2` and everything works as expected.
Related:
- https://github.com/cdr/code-server/pull/3011
=> chore(dev-deps): bump @types/node to 12.20.7

.github/workflows/publish.yaml, ci/steps/brew-bump.sh
This PR adds a new job to the `publish` workflow to automatically bump the code-server version on homebrew.
It failed because `3.9.3` isn't out yet, but I think it *should* work.
=> feat(ci): add homebrew job to publish workflow

.github/dependabot.yml
This PR limits updates to `xdg-basedir` due to breaking changes (ESM). 
Related:
- https://github.com/cdr/code-server/pull/3034#issuecomment-813718574
=> chore(deps): limit xdg-basedir updates

docs/install.md
This PR updates the `install.md` docs with a workaround for the search issue on Android. 
H/T to @yozman for posting their solution: https://github.com/cdr/code-server/issues/1730#issuecomment-721515979
Fixes #1730
=> docs(install): add Termux workaround for search

.github/ranger.yml
This PR fixes a couple syntax issues in the `ranger.yml` configuration and adjusts the close time to 2 days instead of 3.
I thought we could define our own custom actions but I don't think that's the case after re-reading [the docs](https://www.notion.so/Documentation-8d7627bb1f3c42b7b1820e8d6f157a57) and asking the maintainer why it wasn't working 😂.
=> fix: update ranger file

README.md, ci/build/release-prep.sh, ci/helm-chart/Chart.yaml, ci/helm-chart/README.md, ci/helm-chart/values.yaml, ci/lib.sh, docs/install.md, install.sh, lib/vscode/test/smoke/package.json, package.json
This PR is to generate a new release of `code-server` at `3.9.3`
https://user-images.githubusercontent.com/3806031/114092048-4bc5a280-986e-11eb-9798-7f430a873e4f.mov
=> release: 3.9.3

ci/images/debian10/Dockerfile
This PR uses `curl` to install `nfpm` instead of Go. 
See failed publish workflow: https://github.com/cdr/code-server/runs/2300619746?check_suite_focus=true#step:3:1110
NOTE: follow-up PR.
=> fix: use curl to install nfpm

.github/ranger.yml
This PR fixes a tiny typo in the Ranger config.
=> dev(ranger): fix typo

docs/FAQ.md
We use sysbox in Coder to do the same behavior and find it works for many development cases
=> add mention of sysbox

.github/ranger.yml
This removes and extra " in the `ranger.yaml` which should fix the issue of closing without a message (I think).
=> fix(dev): syntax in ranger

docs/SECURITY.md
This PR adds a security policy for how we handle vulnerabilities in code-server.
See ["Adding a security policy to your repository"](https://docs.github.com/en/code-security/security-advisories/adding-a-security-policy-to-your-repository) for more information.
=> docs: add security policy

package.json, yarn.lock
Upgrade parcel-bundler due to a transitive dependency on is-svg.
This resolves CVE-2021-28092.
This issue is not flagged by `audit-ci` or `yarn audit` for some reason, but both Dependabot Alerts and Trivy flag this. Yarn 
```shell-session
[coder@jawnsy-m code-server]$ yarn why is-svg
=> Found "is-svg@3.0.0"
info Reasons this module exists
- "parcel-bundler#cssnano#cssnano-preset-default#postcss-svgo" depends on it
- Hoisted from "parcel-bundler#cssnano#cssnano-preset-default#postcss-svgo#is-svg"
Done in 0.56s.
```
```shell-session
[coder@jawnsy-m code-server]$ trivy filesystem .
yarn.lock
=========
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)
+---------+------------------+----------+-------------------+---------------+---------------------------------------+
| LIBRARY | …
```
=> security: upgrade parcel-bundler from 1.12.4 to 1.12.5

lib/vscode/yarn.lock, yarn.lock
Probably a bit of a sledgehammer approach to the whole process; but should reduce duplicate dependencies and maybe save some small amount of space!
=> chore(deps): deduplicate deps in yarn.lock

ci/README.md, ci/build/release-github-assets.sh, ci/build/release-github-draft.sh, ci/build/release-prep.sh, ci/lib.sh
Notes -
In addition to moving our two `hub` calls to `gh`, I also replaced the `curl` calls that depend on `GITHUB_TOKEN` being set in `ci/lib.sh` with `gh api` calls instead; the benefit is that this also allows alternative auth (stored in `~/.config/gh/hosts.yml` instead of env).
Closes #2960.
=> chore(ci): migrate from hub to gh

.github/ranger.yml
I wish GitHub integrations would give us red squiggles in the file when we mess up the syntax. Oh, well!
=> chore(ranger): fix syntax for extension-request

lib/vscode/src/vs/base/parts/ipc/common/ipc.net.ts, lib/vscode/src/vs/server/entry.ts, lib/vscode/src/vs/server/node/connection.ts, lib/vscode/src/vs/server/node/protocol.ts, lib/vscode/src/vs/server/node/server.ts, src/node/routes/index.ts
More details in the commit messages.
=> Minor connections refactor

.github/workflows/ci.yaml, package.json, yarn.lock
This PR adds support to generate test coverage reports on PRs using @codecov 
- add `CODECOV_TOKEN` secret to project
- add `clover` to `coverageReporters` for unit tests (see `jest` key on `package.json`)
- add `codecov` as dev dependency
- add `coverage` script to `package.json`
- add ci step to run `yarn coverage`
todo
Fixes #3151
=> feat(testing): add codecov to generate test coverage reports

src/browser/register.ts, test/unit/register.test.ts, test/unit/util.test.ts
This PR adds two more tests to cover the last line for `src/browser/register.ts` which should be at 100% now. 
Interestingly - the output from Jest and what Codecov picks up are a little different 🤷‍♂️
=> feat(testing): add tests for registerServiceWorker

.github/ISSUE_TEMPLATE/bug-report.md, docs/FAQ.md
- Most people leave the logs out so add a section for them in the issue
template.
- Remove the VS Code logs because those get sent to stdout now and will
show up in our logs.
- Separate browser console and network.
=> Revamp debugging section

docs/guide.md
Simple example of serving from sub-path in Caddy
=> docs(guide.md): add `caddy` example for serving from sub-path

lib/vscode/build/yarn.lock, lib/vscode/yarn.lock
Update `devDependencies` with known CVEs.
They only process trusted data, so there is no need for us to release a security advisory; but cherry-pick updates for them nonetheless to satisfy tools like Trivy.
=> chore(deps): update dependencies with CVEs

README.md, ci/README.md, ci/build/release-prep.sh, package.json
This PR removes our previous workflow of adding a badge using a 3P package to using a dynamic one with codecov.
=> docs(readme): refactor to use codecov shield

src/node/constants.ts, src/node/socket.ts, src/node/util.ts, test/e2e/browser.test.ts, test/e2e/codeServer.test.ts, test/e2e/globalSetup.test.ts, test/e2e/login.test.ts, test/e2e/logout.test.ts, test/e2e/models/CodeServer.ts, test/e2e/openHelpAbout.test.ts, test/e2e/terminal.test.ts, test/unit/cli.test.ts, test/unit/constants.test.ts, test/unit/socket.test.ts, test/unit/update.test.ts, test/utils/constants.ts
This PR adds a test for the integrated terminal in code-server.
- add `CodeServer` class for simplifying testing (thank you @jawnsy for the [POM](https://playwright.dev/docs/pom/) tip!)
- add test for `CodeServer`
- add test for terminal
- fix `expect` in a couple e2e tests (I forgot `.toBe(true)`)
https://user-images.githubusercontent.com/3806031/115481505-97c6fe80-a201-11eb-9cba-4f4db09a28f8.mp4
=> feat(testing): add e2e tests for code-server and terminal

test/e2e/models/CodeServer.ts, test/e2e/terminal.test.ts
This PR fixes a flaky implementation of the `focusTerminal` method on the `CodeServer` model.  
This was caught after merging into https://github.com/cdr/code-server/pull/3169 `main` and the e2e tests failed [here](https://github.com/cdr/code-server/runs/2442992048?check_suite_focus=true#step:10:6883) 😅
Changes:
- refactor `reloadUntilEditorIsVisible` method. It wasn't waiting for code-server to fully load before reloading. before "Editor became visible after 11 reloads -> "Editor became visible after 1 reload"
- refactor `focusTerminal` method. 
The `should show the Integrated Terminal` only passed intermittently in Firefox:
```shell
✓ CodeServer should show the Integrated Terminal (20s)
x 3) CodeServer should show the Integrated Terminal (47s)
x 1) CodeServer should show the Integrated …
```
=> refactor(testing): fix flaky terminal test

.github/dependabot.yml
This PR tells dependabot to ignore 15.x updates to `@types/node`.
=> chore: ignore 15.x @types/node updates

.github/codeql-config.yml, .github/dependabot.yml, .github/workflows/codeql-analysis.yml
This PR adds code-scanning using CodeQL (by GitHub) to help automatically detect common vulnerability and coding errors.
Fixes #3176
=> feat(security): add code-scanning with CodeQL

ci/dev/fmt.sh, docs/MAINTAINING.md, test/unit/register.test.ts
Right now, the workflow looks a bit like this:
1. Issue comes in, assign to "triage" and ad relevant labels.
2. Once triaged is moved to next, it means we are working on it.
3. It may also get added to a version milestone if it will be out before that milestone is released.
We also have some work being added to the "On Deck" milestone. We would like to reduce any duplicate efforts and align ourselves with one process.
Use milestones instead of project boards (similar to how [vscode does it](https://github.com/microsoft/vscode/milestones)). 
Create the following milestones:
- "Backlog" -> Work not yet planned for a specific release.
- "On Deck" -> Work under consideration for upcoming milestones
- "Backlog Candidates" -> Work that is not yet accepted for the Backlog. We wait for the …
=> docs(maintaining): use milestones over boards

docs/FAQ.md
the real credit goes to @noahsbwilliams for discovering and sharing this in #2794. I figured it should mandate a FAQ entry since it is a known issue
=> docs(faq): add entry for accessing OSX folders

.eslintrc.yaml, package.json
This PR addresses forgotten work from when we migrated from `jest-playwright` to `playwright-test`.
=> fix(deps): remove eslint-plugin-jest-playwright

test/config.ts, test/e2e/terminal.test.ts, yarn.lock
This PR reduces the flakiness of the `terminal.test.ts` and testing overall by using 1 worker. It doesn't eliminate all flakiness but should reduce it.
- removes quotes from `echo` command in `terminal.test.ts`
- use 1 worker when running tests
- update `yarn.lock` (forgot to do so in https://github.com/cdr/code-server/pull/3260)
Running the `terminal.test.ts` 30 times locally (10 for each major browser) and it only failed once -> in chromium. 
It's failing because it's either not receiving the full `echo` command or hitting enter before it receives the full command. 
https://user-images.githubusercontent.com/3806031/116630124-8b305d80-a907-11eb-98bc-52ec97b808a9.mp4
I'm going to open up a separate PR to add an additional check for e2e tests to check the connection. …
=> fix(testing): reduce flakiness of terminal.test.ts and use 1 worker for e2e tests

.github/workflows/ci.yaml
This PR adds a new job to our CI called `trivy` which uses [`trivy-action`](https://github.com/aquasecurity/trivy-action) to scan our code and upload the Trivy scan results to the GitHub Security tab.
Fixes #3177
=> feat(ci): add trivy job for security

docs/MAINTAINING.md
This PR adds a short section about our triage process to the workflow section.
=> docs(maintaining): add triage to workflow

docs/MAINTAINING.md
This PR updates `MAINTAINING.md` with a section for "Versioning."
=> docs(maintaining): add versioning

ci/build/build-code-server.sh
Move to downloading from GitHub releases. :tada:
=> feat(ci/build): support arm64 for cloud-agent

docs/SECURITY.md
This PR updates the `SECURITY.md` policy with a list of the tools we use.
=> docs(security): add section for tools

src/node/cli.ts, src/node/constants.ts, src/node/entry.ts, src/node/main.ts, src/node/routes/vscode.ts, test/unit/cli.test.ts, test/unit/health.test.ts, test/unit/proxy.test.ts, test/utils/integration.ts
This is a workaround for https://github.com/cdr/code-server/issues/3014 until we figure it out (if it is indeed related which it might not be; the zlib errors could merely be side effects of a connection issue).
=> Add flag for toggling permessage-deflate

.github/workflows/ci.yaml
Move dependency audits from prebuild to their own jobs, so that an error does not affect the rest of the build/test process.
=> refactor(ci): split audit from prebuild

package.json, test/unit/constants.test.ts
This PR adds additional testing for `src/node/constants.ts`, specifically checking that both `commit` and `version` return the correct values when defined in and missing from `package.json`.
- update `coveragePathIgnorePatterns` to `/out` (so that we collect coverage for `src/node/routes`
- add tests for `src/node/constants.ts`
=> feat(testing): add test for src/node/constants.ts

test/e2e/terminal.test.ts, test/unit/constants.test.ts, test/unit/helpers.test.ts, test/unit/register.test.ts, test/unit/routes/health.test.ts, test/unit/routes/static.test.ts, test/unit/util.test.ts, test/utils/constants.ts, test/utils/helpers.ts, test/utils/integration.ts
Mostly just wanted to add a test for static auth.
=> Test static route

lib/vscode/package.json, lib/vscode/yarn.lock
`azure-storage` is deprecated, pulls in a vulnerable version of a dependency, and we don't use the build steps from VSCode that depend on it anyway.
=> chore(lib/vscode): remove gulp-azure-storage from deps

lib/vscode/src/vs/platform/extensionManagement/node/extensionsScanner.ts, lib/vscode/src/vs/server/node/server.ts
=> Make sure directories exist

lib/vscode/coder.js, lib/vscode/src/vs/platform/terminal/node/ptyService.ts, lib/vscode/src/vs/platform/terminal/node/terminalProcess.ts, lib/vscode/src/vs/server/node/channel.ts, lib/vscode/src/vs/server/node/server.ts
Most of this was a straightforward replacement of our code with theirs
but I also removed `getDefaultShellAndArgs` since it seems the reference
implementation no longer does that either.
Fixes #2276.
=> Use ptyHostService

ci/build/npm-postinstall.sh
Fixes the npm postinstall script, which is also used to download cloud-agent, to download based on the system architecture.
=> fix(build): download correct cloud-agent for arch

README.md, ci/build/release-github-assets.sh, ci/helm-chart/Chart.yaml, ci/helm-chart/README.md, ci/helm-chart/values.yaml, ci/lib.sh, docs/install.md, install.sh, package.json
This PR is to generate a new release of `code-server` at `$CODE_SERVER_VERSION_TO_UPDATE`
=> release: 3.10.0

ci/release-image/entrypoint.sh
Given that `sudo usermod --login "$DOCKER_USER" coder` and `sudo groupmod -n "$DOCKER_USER" coder` modify the container's disk it'll persist across restarts, but environment variables will be reset to whatever state they had at the end of `Dockerfile`. In this case, `$USER` is set to `coder`, so this branch will always be true.
By checking with the output of `whoami`, which gets it's information from `/etc/passwd`, we make sure to get the real logged user and not the one defined by $USER.
We also move `USER="$DOCKER_USER"` out of the branch, since we always want this to happen at entry-point. If we don't do this assignment, $USER will contain `coder` upon restart.
Fixes #2767.
=> Check the logged user instead of $USER

.github/dependabot.yml, CHANGELOG.md
Microsoft publishes updates to this action using the same scheme
as GitHub, where the v1 tag is updated to the latest release of
the 1.0 series. Therefore, we can manage updates manually.
=> chore: ignore updates to microsoft/playwright-github-action

CHANGELOG.md, ci/build/npm-postinstall.sh, ci/lib.sh
This ensures the link is correct. Should fix #3355.
=> Override existing asar symlink in postinstall

CHANGELOG.md, docs/install.md
=> docs(install): add raspberry pi section

CHANGELOG.md, docs/MAINTAINING.md
This PR updates `MAINTAINING.md` with "Merge Strategies" providing some recommendations.
=> docs(maintaining): add merge strategies section

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md, CHANGELOG.md, src/node/socket.ts, src/node/util.ts, test/unit/node/util.test.ts
This PR fixes this issue:
```shell
discarding socket connection: EACCES: permission denied, unlink '/tmp/code-server/tls-proxy'
```
by using the `xdgBasedir.runtime` path instead of `/tmp/code-server/tls-proxy`.
- update pr template to say default branch
- add `runtime` to `getEnvPaths`
- add test for `getEnvPaths`
- remove use of `tmpdir` in `socket.ts`
refactor: use paths.runtime in socket proxyPipe
Fixes #2200
=> fix(socket): use xdgBasedir.runtime instead of tmp

CHANGELOG.md, docs/MAINTAINING.md
This PR adds a section about pull requests and associating with milestones to `MAINTAINING.md`.
=> docs(maintaining): add pull requests section

.github/workflows/ci.yaml, CHANGELOG.md
This PR re-enables `trivy-scan-repo` now that it's been fixed upstream.
Reference: https://github.com/aquasecurity/trivy-action/issues/22#issuecomment-839948770
=> fix(ci): re-enable trivy-scan-repo

lib/vscode/src/vs/platform/remote/common/remoteAgentConnection.ts
This was added a long time ago but accidentally lost when we reverted
the retry changes to this file after one of the VS Code updates that
added their own retry (we reverted everything not realizing we had other
unrelated changes in here).
This is definitely one downside to the subtree over patches but I added 
a note to help ensure we notice the change in case something similar 
happens again.
=> Add socket type to websocket connection query (regression)

CHANGELOG.md, docs/CONTRIBUTING.md
This PR adds some note to `CONTRIBUTING.md` around clean commits.
=> docs(contributing): add commits section

.github/ISSUE_TEMPLATE/release.md, .github/PULL_REQUEST_TEMPLATE/release_template.md, CHANGELOG.md, ci/README.md, ci/build/release-prep.sh, docs/MAINTAINING.md
This a proposal to add process around releases with "Release Managers".
Summary: rotate which maintainer cuts a new release.
How it works now:
1. random maintainer cuts release
2. random maintainer creates new version milestone
3. random maintainer closes previous version milestone
How it will work with proposed approach:
1. introduces "release manager" role  to own release
2. release manager owns cutting release, creating new version milestone and creating an issue to track next release
- reinforces our philosophy -> each PR should have an issue attached (now releases will have issues)
- explicitly states who owns current release
- gives each maintainer an opportunity to own a release
- adds a couple extra steps to release process
- requires all maintainers to participate in release …
=> docs(maintaining): add process for release managers

docs/termux.md
See https://github.com/termux/termux-app#google-playstore-deprecated (#3395)
Fixes #3395
=> Termux on Play Store is deprecated; replaced with F-Droid link 

CHANGELOG.md, lib/vscode/src/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page.ts
This PR fixes the "Open Folder" link on the Welcome page. 
- update Welcome Page to use `openFolder`
https://user-images.githubusercontent.com/3806031/119185923-41312800-ba2c-11eb-8b70-7fd193ebe0a7.mov
Fixes #2921 
Related:
- #3427
- #3436
=> fix: use correct command to Open Folder on Welcome page

CHANGELOG.md, ci/steps/brew-bump.sh
This PR updates `brew-bump.sh` to ensure `cdrci/homebrew-core` is up-to-date before bumping the formula in the publish workflow.
- update `brew-bump.sh` script
todo
Fixes #3407
=> fix(ci): update brew-bump.sh to update remote first

CHANGELOG.md, README.md, ci/build/release-prep.sh, ci/helm-chart/Chart.yaml, ci/helm-chart/README.md, ci/helm-chart/values.yaml, install.sh, package.json
This PR is to generate a new release of `code-server` at `3.10.2`
https://user-images.githubusercontent.com/3806031/119207597-83ba2b00-ba53-11eb-83de-b15460971e07.mov
Fixes #3439
=> release: 3.10.2

.github/workflows/ci.yaml, package.json, yarn.lock
This PR temporarily disables `trivy-scan-image` due to an upstream issue. See: https://github.com/github/codeql-action/issues/528
There was a vulnerability found when CI ran. This is fixed as well:
- `browserslist`
Fixes #3459
=> fix(ci): disable trivy-scan-image

docs/FAQ.md
RE: https://github.com/pomerium/pomerium/pull/2223
=> docs: add Pomerium

CHANGELOG.md, docs/CONTRIBUTING.md
This PR fixes a sentence in Pull request section which was less understandable on the first go.
=> docs: fix confusing sentence in pull requests section

CHANGELOG.md, ci/dev/fmt.sh
This PR removes `CHANGELOG` from `fmt.sh` and removes the table of contents from `CHANGELOG`. 
Why?
It causes more headache than value. We don't need a table of contents in the `CHANGELOG` and we shouldn't make contributors run `yarn fmt` after updating the `CHANGELOG`.
=> fix: remove CHANGELOG from fmt.sh and remove toc from CHANGELOG

CHANGELOG.md, docs/MAINTAINING.md
This PR adds docs around `CHANGELOG`. 
Fixes #3412
=> docs(MAINTAINING): add information about CHANGELOG

docs/MAINTAINING.md
Pasted "Publishing A Release" in the 'MAINTAINING.md' file from line #98
=>  Pasted "Publishing A Release" in the 'MAINTAINING.md' file

.github/workflows/ci.yaml, .tours/start-development.tour, CHANGELOG.md, ci/build/npm-postinstall.sh, docs/CONTRIBUTING.md, docs/npm.md, package.json, yarn.lock
Closes #3458; updates node and adds some process notes.
=> chore: update node to v14

lib/vscode/src/vs/workbench/services/keybinding/browser/keyboardLayoutService.ts
This might be causing issues with the PWA showing a blank screen with
MacOS.
I've opted not to add a changelog item yet because it's untested whether this fixes the issue.
=> Catch getLayoutMap error

CHANGELOG.md, ci/README.md, docs/MAINTAINING.md
=> docs: move release process to MAINTAINING.md

.github/workflows/ci.yaml, ci/build/npm-postinstall.sh, ci/lib.sh
See https://github.com/actions/cache/blob/main/examples.md#node---yarn for an example. `restore-keys` will pull from an older set of dependencies in the cache, then update them and store them again, instead of starting from scratch.
This should bring us decent speed benefits for Dependabot PRs that update a few packages at a time.
=> feat(ci): add restore-keys for ci speedup

.github/workflows/publish.yaml, CHANGELOG.md, ci/steps/brew-bump.sh
This PR fixes the homebrew `brew-bump.sh` step which runs when we publish a new release.
When we publish a new release, we run a script to bump the formula for code-server on homebrew. The script works using `cdrci`'s GitHub token (secret in repo) so that the PR comes from them and not a maintainer.
The problem is `bump-formula-pr` uses the user's `homebrew-core` fork.
This means we need to ensure the fork is up-to-date.
To do that, we need to pull the remote and push the changes to the fork before running `bump-formula-pr`.
We tried to see if it would "just work" by pulling and pushing, but the push command asks for a username and password.
You can get around this with `--all`. We found this solution [here](https://serverfault.com/a/912788).
> This has the advantage that the password …
=> fix(publish): update cdrci fork in brew-bump.sh

CHANGELOG.md, docs/guide.md
This PR just converted the case format of 'Caddy'
- update `guide.md`
=> docs: format 'Caddy'

lib/vscode/package.json, lib/vscode/yarn.lock
Update to fix a security issue (older version depended on a sorely out of date ws 3.3!)
=> chore(deps): update chrome-remote-interface

.gitignore, CHANGELOG.md
`out*`  will cause these below files to be ignored: 
> 
> lib/vscode/src/vs/editor/contrib/documentSymbols/outlineModel.ts
lib/vscode/src/vs/editor/contrib/documentSymbols/test/
lib/vscode/src/vs/workbench/contrib/codeEditor/browser/outline/ lib/vscode/src/vs/workbench/contrib/notebook/browser/contrib/outline/
lib/vscode/src/vs/workbench/contrib/notebook/browser/view/output/
lib/vscode/src/vs/workbench/contrib/outline/
lib/vscode/src/vs/workbench/contrib/output/
lib/vscode/src/vs/workbench/services/outline/
lib/vscode/src/vs/workbench/services/output/
=> chore: update .gitignore

package.json, yarn.lock
This fixes a couple vulnerabilities introduced by `parcel`.
=> fix(dev-deps): parcel vunlerabilities

docs/FAQ.md
This PR fixes a minor mistake with the new hashed password section in docs, changes made to align the example with the correct placeholder text.
=> fix: placeholder password in hashed password example

ci/lib.sh
This is a one line fix, so adding a PR seems a lot (but will do if demanded).
This fix is only interesting for developers trying to use raspberry pi 4.
With this patch `yarn` passes. The general plan is to work through all issues in being able to build the code on a raspberry pi 4.
Next PR will concentrate on `yarn watch`.
Edit: 
Arch() will not either return the converted cpu type or raw “uname -m”
Fixes #3612
=> Allow code-server to identify raspberry pi 4 (armv7l)

docs/CONTRIBUTING.md
Node needs be v14.x not greater. If installing the standard version ‘brew install node’, both ‘yarn’ and ‘code-server’ (release version) complains.
Newest version is v16.x so we are pretty far behind.
=> docs: Update CONTRIBUTING.md

CHANGELOG.md, docs/CONTRIBUTING.md
=> docs(CONTRIBUTING): add section on testing

ci/build/build-release.sh, docs/README.md
As mentioned in https://github.com/cdr/code-server/pull/3582 we decided to move the README into /docs folder. 
Change on code-server docs:
On GitHub:
=> docs: move README to docs

.github/PULL_REQUEST_TEMPLATE.md, docs/MAINTAINING.md
This updates the `CHANGELOG` process after a discussion between the maintainers (see [comment](https://github.com/cdr/code-server/pull/3637#issuecomment-867179693)).
Moving forward from maintainers and contributors is to make the `CHANGELOG` _meaingful_ for code-server users. This will make the release notes more interesting and more useful as well.
=> docs(MAINTAINING): update changelog process

docs/termux.md
This PR updates the docs with a new workaround for the Android backspace issue (thanks to @Nefomemes)
Fixes #1141
=> docs(termux): add backspace workaround for android

src/browser/pages/vscode.ts, test/unit/browser/vscode.test.ts
This PR refactors a couple lines inside `src/browser/pages/vscode.ts` so that it's easier to maintain and test.
- add function `getNlsConfiguration`
- add tests
Fixes: N/A
=> refactor: add func and tests for getNlsConfiguration

.github/workflows/ci.yaml, ci/dev/test-e2e.sh, ci/dev/watch.ts, src/node/util.ts, test/e2e/baseFixture.ts, test/e2e/browser.test.ts, test/e2e/codeServer.test.ts, test/e2e/globalSetup.test.ts, test/e2e/login.test.ts, test/e2e/logout.test.ts, test/e2e/models/CodeServer.ts, test/e2e/openHelpAbout.test.ts, test/e2e/terminal.test.ts, test/playwright.config.ts, test/unit/node/util.test.ts, test/unit/util.test.ts, test/utils/constants.ts, test/utils/globalSetup.ts, test/utils/helpers.ts
I recommend reviewing by commit (and reading the commit messages).
Setting as a draft until I'm sure the tests pass in CI.
=> Parallel tests

docs/install.md
Links don't work on docs site unless they have md formatting. Fix is minor.
=> Fix broken link on docs site

.github/workflows/ci.yaml
This PR adds timeouts to CI jobs to prevent them from running longer than reasonable.
Case: Pre-build checks ran for [1h 51m today](https://github.com/cdr/code-server/actions/runs/987241200) because I didn't close an HTTP server in a unit test.
Fixes N/A
=> fix: add timeouts to CI jobs

src/node/util.ts, test/unit/node/util.test.ts
This PR adds an additional check to `isHashMatch` to check that the hash starts with a "$" to prevent us from calling `argon2.verify` if it doesn't.
It also throws an error if something goes wrong with the `.verify()` function.
**Why do we need to add this?**
The other day I noticed this error: `'TypeError: pchstr must contain a $ as first char\n'`
I believe it happens because we're still in between a migration from the old hashing function `sha256` to the new one `argon2`. And locally, I switch between the latest code-server and the development one. This means it may be calling the function to verify the hash expecting it to be a hash made with `argon2` and instead it's made with `sha256`. 
Once we release the newest version of code-server with the `argon2` algorithm, we don't want it to …
=> fix(isHashMatch): check that hash starts with $

src/node/http.ts, src/node/routes/login.ts, src/node/util.ts, test/unit/node/util.test.ts, test/unit/routes/login.test.ts
This PR fixes a security issue by sanitizing the `error.message` before sending it back to the client on a login failure.
- add function `escapeHtml` + tests
- fix: escape `error.message` before sending to client on login failure
Fixes #3382
=> fix: escape error.message on login failure

docs/guide.md
This PR updates the requirements in `guide.md` by adding a line about WebSockets.
We've had people in the past not enable WebSockets in their environment, leading to code-server not working.
Evidence
- https://github.com/cdr/code-server/discussions/3667#discussioncomment-934888
- https://github.com/cdr/code-server/discussions/3175#discussioncomment-640924
=> docs(guide): add WebSockets to requirements

docs/install.md
This PR adds a short section to `install.md` for troubleshooting node issues.
Fixes #1794
=> docs(install): add troubleshooting node issues

install.sh
This PR fixes the install script to work on Alpine 64-bit. Our `arch` function doesn't recognize 32-bit Alpine, which fallsback to `npm`/`yarn` install (which is why it works on 32-bit Alpine), but tries to use the standalone install for 64-bit, which doesn't work.
This fixes that.
Fixes #3421
Also, thank you to @b-trav for filing an issue about the broken links in `install.sh`!
=> fix: update install script for alpine

test/unit/emitter.test.ts
This adds a couple lines to hit 100% test coverage for `emitter.ts` by ensuring that our logic works when trying to `dispose` of a callback more than once. 
Fixes N/A
=> feat(test): try calling .dispose() x2 in emitter

test/browser/pages/login.test.ts
This PR adds a new test for `login.ts` to check our logic works when it doesn't find an element with the id "base".
Fixes N/A
=> feat(test): check login.ts when base missing

lib/vscode/src/vs/workbench/contrib/files/browser/explorerViewlet.ts
This PR fixes a bug with the "Open Folder" button not working as expected due to a "missing command". The fix is simply using the `openFolder` command instead of the `openFileFolder`. 
https://user-images.githubusercontent.com/3806031/124666970-9ea9f880-de63-11eb-8f45-c45c24ccde38.mov
Fixes #3457
=> fix: openFolder button on Explorer panel

package.json, test/package.json, test/yarn.lock, yarn.lock
This PR removes unused dependencies.
To do this, we use a tool called `depcheck`. Locally, I ran `npx depcheck --ignore-patterns=lib,dist,coverage,contrib` which gave the following output:
```text
Unused dependencies
* argon2
* env-paths
* node-fetch
* pem
* safe-buffer
* safe-compare
* tar-stream
* xdg-basedir
Unused devDependencies
* @types/pem
* @types/safe-compare
* @types/tar-stream
* @types/wtfnode
* audit-ci
* doctoc
* eslint-import-resolver-alias
* leaked-handles
* prettier-plugin-sh
* shellcheck
* stylelint
* stylelint-config-recommended
* wtfnode
Missing dependencies
* express-serve-static-core: ./typings/pluginapi.d.ts
```
Most of these are false-positives. I've identified the ones we no longer used and removed them as part of this PR. I've corrected this list and added more …
=> chore: remove unused dependencies

package.json
In https://github.com/cdr/code-server/pull/3729, I removed `eslint-import-resolver-alias` because I didn't think we used it but turns out we do to make importing code-server plugins in a test.
I don't fully understand exactly how it works, but it has to with aliasing a module (code-server itself as a module) in one of our tests. I tried putting it in the `test/package.json` but ESLint didn't like that.
=> revert: add eslint-import-resolver-alias as dependency

docs/guide.md
This adds a short note to the NGINX section of `guide.md` for how to configure the green section displayed in code-server's UI.
Fixes #3513
(thank you to @sestegra and @nakkaya for pointing this out!)
=> docs(guide): add note about configuration for NGINX

src/browser/pages/vscode.ts, test/unit/browser/vscode.test.ts
This PR adds more tests for `browser/pages/vscode.ts`.
Fixes N/A
The main purpose of this PR is to test this piece of code
```js
document.body.style.background = JSON.parse(localStorage.getItem("colorThemeData")!).colorMap["editor.background"]
```
This code grabs the `colorThemeData` from `localStorage` to get the editor background color based on the user's VSCode theme and then sets the background of the `body` to that color.
=> feat: add more tests for browser/pages/vscode

.github/dependabot.yml
This PR tells dependabot to ignore major updates for Node.
=> fix(dependabot): ignore major updates for node

docs/FAQ.md
This PR adds a short line item to the FAQ regarding password login limits.
Fixes #3226
=> docs(faq): add line about password login limits

docs/CONTRIBUTING.md, docs/FAQ.md, docs/MAINTAINING.md, docs/README.md, docs/SECURITY.md, docs/guide.md, docs/install.md, docs/ipad.md, docs/npm.md, docs/requirements.md, docs/termux.md, docs/triage.md, docs/upgrade.md
Edits, minor refactoring of code-server docs.
=> refactor(docs): clean up and restructure

src/node/util.ts, test/unit/node/util.test.ts
This PR adds an extra check to the `pathToFsPath` function to check that `uri.path` is indeed a string.
We do this because CodeQL believes there is currently type confusion through parameter tampering earlier up in the codebase where this is used. See security warning [here](https://github.com/cdr/code-server/security/code-scanning/51?query=ref%3Arefs%2Fheads%2Fmain).
Fixes #3750
=> fix: check uri.path is string in pathToFsPath

test/unit/browser/pages/login.test.ts, test/unit/browser/pages/vscode.test.ts, test/unit/browser/register.test.ts, test/unit/browser/serviceWorker.test.ts, test/unit/node/util.test.ts
I accidentally merged a PR that didn't have a file formatted correctly and it made CI on `main` fail. This fixes that but also clean ups some testing files to be better organized.
=> refactor: clean up testing files

ci/helm-chart/Chart.yaml, ci/helm-chart/README.md, ci/helm-chart/values.yaml, docs/README.md, docs/requirements.md, install.sh, package.json
This PR is to generate a new release of `code-server` at `v3.11.0`
=> chore(release): bump version to 3.11.0

ci/lib.sh, ci/steps/brew-bump.sh, ci/steps/publish-npm.sh, ci/steps/push-docker-manifest.sh
This also makes the publish steps idempotent so we can re-run the publish workflow.
=> Fix Docker push

package.json, yarn.lock
This PR updates `codecov` to `3.8.3` which should help with an issue we faced earlier: https://github.com/codecov/codecov-node/issues/324#issuecomment-866379405
=> chore: update codecov to 3.8.3

docs/guide.md
Fixes header on guides.md so that it reads "Accessing Web Services" instead of "Self signed certificates." Also updates in-text mention from "web service" to "web services."
=> chore: update guides.md header to Accessing Web Services

.github/codecov.yml, package.json
This PR updates the coverage threshold for codecov and Jest.
It changes the threshold to 60 for Jest meaning the unit tests must hit at least 60% coverage or it will fail.
It also turns off the patch requirement for codecov. We do this because sometimes PRs touch files in minor areas that have yet to be tested resulting in the patch requirement failing even if the author increased coverage in other areas. In the future, we can turn this back on.
It also changes the range to 40-70 meaning above 70% codecov will be green, less than 40 will be red and anything in between will approach green. We do this so the badge isn't read in the `README` and it's a reminder that we are indeed making progress on the code coverage increase.
Read more in the [codecov …
=> chore: update coverage thresholds

src/node/routes/vscode.ts, src/node/util.ts, test/unit/node/util.test.ts
This PR reverts some work done in https://github.com/cdr/code-server/pull/3751 to make `pathToFsPath` better.
=> refactor: only accept string in pathToFsPath

src/browser/pages/vscode.ts, test/unit/browser/pages/vscode.test.ts, test/unit/node/util.test.ts
This adds a new function called `registerRequireOnSelf` to `vscode.ts`. We do this so that we can extract this logic into a function, which makes it easier to test. 
https://user-images.githubusercontent.com/3806031/125342840-35fec800-e30a-11eb-99e0-7c9c11409e6a.mov
Fixes N/A
TODOs
=> feat: add registerRequireOnSelf on function

src/browser/register.ts, test/unit/browser/register.test.ts
3.10.2 had this folder, but it was removed in version 3.11.0
cc @jsjoeio
=> Fix "serviceWorker.js" path

docs/install.md
This PR adds an "Uninstall" section to the `install.md` docs. I decied to add this because I noticed a trend in GitHub Discusions where people have asked how to do this:
- https://github.com/cdr/code-server/discussions/3525
- https://github.com/cdr/code-server/discussions/3823
- https://github.com/cdr/code-server/discussions/1989
This does not cover all scenarios but it does cover the ones that have been asked about. I figured we can add more as it gets asked (issue/discussion drive development?).
=> docs(install): add uninstall instructions

src/node/proxy_agent.ts, test/unit/helpers.test.ts, test/unit/node/proxy_agent.test.ts, test/utils/helpers.ts
This PR adds tests for `shouldEnableProxy()` which is used in `proxy_agent.ts`.
Related:
- https://github.com/cdr/code-server/issues/3841
=> feat: add tests for shouldEnableProxy

docs/install.md
=> docs(install): Fix link to helm readme

test/unit/helpers.test.ts, test/unit/node/proxy.test.ts, test/utils/helpers.ts
This PR adds more tests for `proxy.ts`, specifically to test that our proxy handles error events appropriately.
Fixes N/A
P.S. huge shoutout to @vapurrmaid for pairing with me on this 🎉
=> feat: add more tests for proxy.ts

ci/lib.sh
This way workflows will still work even if there have been enough runs
to push the version branch run off the first page.
=> Query artifacts by branch name

package.json, test/package.json, test/yarn.lock, yarn.lock
This fixes a vulnerability from `tar`, which comes from `argon2`.
- https://www.npmjs.com/advisories/1770
- https://www.npmjs.com/advisories/1771
=> chore: bump tar with resolutions

lib/vscode/src/vs/workbench/api/common/shared/webview.ts, lib/vscode/src/vs/workbench/contrib/webview/browser/pre/service-worker.js
This PR patches `asWebviewUri` in `lib/vscode/src/vs/workbench/api/common/shared/webview.ts` to remove  the port number from the `authority` field used to create the URI.
For now, we found that removing the port fixes the issue (resources load as expected in webviews), but long-term, we want to understand how this is meant to be used (having the port in the URI authority field).
Related:
- https://github.com/cdr/code-server/discussions/3883
- https://excalidraw.com/#json=6022466832957440,nM6CH8Ga9F2AiLSzjJ55-A
Here is a video of an extension using a webview which loads both CSS and JS working.
https://user-images.githubusercontent.com/3806031/128255007-c342bf0f-f444-48be-84cd-fa8059995d33.mov
Fixes N/A
TODOS
=> fix(lib/vscode): patch authority in asWebviewUri

.github/workflows/ci.yaml
This action is no longer needed, see README for the action here: https://github.com/microsoft/playwright-github-action#%EF%B8%8F-you-dont-need-this-github-action-%EF%B8%8F
The suggested way to install OS deps for playwright is simply:
```
npx playwright install-deps
```
Reference: https://playwright.dev/docs/ci/#github-actions
=> chore(ci): replace playwright gh action

docs/README.md, docs/link.md, docs/manifest.json
link to --link docs from README to separate docs entry
=> docs: create link.md

ci/helm-chart/Chart.yaml, ci/helm-chart/README.md, ci/helm-chart/values.yaml, docs/README.md, docs/manifest.json, docs/requirements.md, install.sh, package.json
This PR is to generate a new release of `code-server` at `3.11.1`
Tested locally and everything seems to be working
https://user-images.githubusercontent.com/3806031/128562304-e28a2871-4217-437a-9056-ebd519c4ae9b.mov
=> release: 3.11.1

.github/workflows/ci.yaml, ci/build/arch-override.json, ci/build/build-packages.sh, ci/build/nfpm.yaml
Hopefully should cross-compile and work for armv7!
Fixes #1337.
=> feat(ci): armv7 cross builds

ci/build/build-release.sh
This PR removes the symlink to `node_modules.asar` when packaging up for `npm` because as of recently, npm no longer allows symbolic links in packages (we also don't need it).
On Friday, August 6th, we released 3.11.1. 
The npm workflow did not work as expected leading to 3.11.1 **not** being published on npm, Homebrew, or AUR. We did some investigation and came to the conclusion something changed on the npm side with regard to symlinks in packages.
We spoke to someone today, August 9th from GitHub who confirmed our theory. 
> Hi Joe! Saw your tweet about symlinks in npm packages. We did make some changes here recently. Can you drop me a line so that we can work through how to support you?
A few of the maintainers chatted and we came to the conclusion that we can remove this symlink. 
> …
=> fix(lib/vscode): remove symlink in npm package

docs/manifest.json
This PR updates the `manifest.json` to only include the latest version in the `versions` key.
Originally, I was going to go with Bruno's suggestion of `v3.11.*` to include all patches but as Jonathan noted, we really only need to support the latest version in the docs (we don't have that many changes between versions).
Plus, using the specific version like `v3.11.1` means it will auto-update with your `release-prep` script. Using `v3.11.*` would make it more difficult.
Fixes https://github.com/cdr/code-server/pull/3903#issuecomment-894609513
=> chore: fix docs version to only use latest

package.json, yarn.lock
This PR resolves a vulnerability with `path-parse`.
https://www.npmjs.com/advisories/1773
=> chore: fix path-parse vulnerability

ci/build/build-release.sh
This PR reverts https://github.com/cdr/code-server/pull/3935
We had a misunderstanding and didn't realize the symlink is needed in standalone releases (because it doesn't have a postinstall step). So we need to rethink our approach for removing the symlink for only the npm package.
=> Revert "Merge pull request #3935 from cdr/jsjoeio-rm-symlink"

docs/README.md
The link to the `--link` docs that relate to TLS is broken (404) as it is pointing to a previous release version whose docs are not available.
This PR updates the docs URL.
I've also run a search on the project to make sure no other links using that version where there and I haven't found any.
As an extra, I'd suggest using the `latest` path rather than a specific version
p.s. I've skipped creating an issue as per docs:
_Please create a GitHub Issue that includes context for issues that you see. **You can skip this if the proposed fix is minor.**_
=> fix(readme): tls docs path

.github/workflows/docs-preview.yaml
Add a new workflow to generate docs preview. It is the same workflow used by Coder docs with some minor changes.
=> chore: add docs preview workflow

ci/steps/publish-npm.sh
This PR modifies the `publish-npm.sh` to add an `.npmignore` with a line to exclude the symlink `node_modules.asar` in the npm release.
As you may have see in the [3.11.1 discussion](https://github.com/cdr/code-server/discussions/3920), we had a hiccup publishing the latest version to npm/Homebrew. This is because npm recently made a change to their package requirements, disallowing symlinks in packages.
Fortunately, we don't need the symlink in the npm package release of code-server. 
We originally thought we could remove the symlink all together, but after chatting with @code-asher, we realized we still need it for the standalone releases. 
We had two options to fix it:
1. copy `.gitignore` to the npm package before bundling up
2. add …
=> fix: add symlink to npmignore

docs/install.md, docs/npm.md
The user flow for our npm docs were slightly confusing to me. While there was a dedicated page for the npm prerequisites, the install command itself was on install.md. This PR moves all of the steps to npm.md.
Windows 10 instructions were also added to this PR since it benefits from the improved docs structure, as there are quite a few "gotchas" with installing on Windows, which have now been documented. It also links to #1397, to centralize issues & discussions around additional support for Windows.
=> improve npm/yarn install flow and add Windows 10 instructions

ci/helm-chart/values.yaml
=> chore: add example for parameter/value to Helm Values

docs/FAQ.md
=> docs: add how to change port

docs/guide.md
Special thanks to @abhinav1912 and @Blakeinstein for helping with this!
Fixes #3918
=> docs: add proxying a vue app

docs/npm.md
=> docs: add note about npm logging

docs/README.md, docs/requirements.md, install.sh
Fixes #3963 thanks to @galesky for the suggestion!
=> fix(docs): use latest instead of version in links

docs/npm.md
This PR fixes some typos/wording introduced in https://github.com/cdr/code-server/pull/4032
=> docs: fix typos and wording in npm

src/browser/pages/vscode.ts, test/package.json, test/unit/browser/pages/vscode.test.ts, test/yarn.lock
This PR adds full test coverage for  `src/browser/pages/vscode.ts`
Fixes #4052
=> feat(testing): add tests for src/browser/pages/vscode to hit 100% coverage

lib/vscode/package.json, lib/vscode/yarn.lock, package.json, test/package.json, test/yarn.lock, yarn.lock
This PR is based off of https://github.com/cdr/code-server/pull/4071 and fixes a `tar` vulnerability.
=> fix(security): tar vulnerability

docs/MAINTAINING.md
This PR adds a section called Documentation and Troubleshooting to explain how to troubleshoot doc issues in code-server. Inspired by https://github.com/cdr/code-server/pull/4060
Fixes N/A
Docs load up just fine in the preview
=> docs: add troubleshooting section for documentation

docs/guide.md, lib/vscode/package.json, lib/vscode/yarn.lock, package.json, test/package.json, test/yarn.lock, yarn.lock
#4042 broke our docs website, #4060 reverted the change.
> There are 2 problems in there. There are 4 back ticks at the end of one block. Changing the line “```output” to  “```console” should fix it
Thanks to @mterhar, I think we found the issue. 
We're working with @BrunoQuaresma to prevent issues like this in the future.
Related:
- https://github.com/cdr/code-server/pull/4042
- https://github.com/cdr/code-server/pull/4060
- https://github.com/cdr/code-server/discussions/4057
=> fix: revert revert and add ssh back into guide docs

ci/build/build-vscode.sh
=> #4113 compile extensions media

ci/build/build-release.sh
Currently, Windows default script-shell (cmd) fails to run the postinstall script.
This commit fixes the problem by running postinstall.sh explicitly with the default bash executable of the OS.
Related: #1397
=> fix: run postinstall script explicitly with bash

lib/vscode/src/vs/workbench/services/extensions/browser/extensionService.ts
This enables the `vscode.workspace.registerRemoteAuthorityResolver` API to be executed.
It's specifically scoped to the "coder-link" scheme at the moment to reduce external dependency on forking VS Code functionality.
The remote host doesn't resolve to an extension host like the API expects, but instead we only utilize the tunnel functionality.
=> Resolve remote authority to initialize tunnel API

ci/release-image/docker-bake.hcl
https://github.com/cdr/code-server/discussions/3920#discussioncomment-1281283
https://docs.docker.com/engine/reference/commandline/buildx_bake/
=> Push latest Docker tag along with version tag

lib/vscode/extensions/github-authentication/package.json, lib/vscode/extensions/github-authentication/yarn.lock, lib/vscode/package.json, lib/vscode/yarn.lock
This PR addresses various vulnerabilities, mainly under `lib/vscode` including:
- https://github.com/cdr/code-server/security/code-scanning/135?query=ref%3Arefs%2Fpull%2F4127%2Fmerge+ref%3Arefs%2Fpull%2F4127%2Fhead+ref%3Arefs%2Fheads%2Fjsjoeio-fix-screenshot
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-23406
Fixes #4126
H/T to @axelgobletbdr for bringing one of these to our attention!
=> fix(security): address dependency vulnerabilities

src/node/app.ts, test/unit/node/app.test.ts
This adds a couple tests for ensureAddress.
(Note: related to #4094. I still need to add more tests to complete the issue but will do so in separate PRs.)
=> feat: add tests for src/node/app.ts

lib/vscode/src/vs/workbench/api/common/shared/webview.ts
With #3895, we caused a regression where the Content-Security-Policy prevented
images in the previewer to not work due to the ports in the resource URI.
This modifies the CSP in the webview to make sure images are not blocked by CSP.
I assume once we upgrade VS Code, we will revert this change.
See notes here: https://github.com/cdr/code-server/issues/3936#issuecomment-916518450
Fixes #3936 #4098
Looks like this PR is a two-for-one!
=> fix(lib/vscode): update csp in webview to allow ports

src/node/util.ts
Fix potential ReDoS.
Reported by security researchers at huntr.dev and emailed to security@coder.com
Fixes N/A
=> fix(security): fix ReDoS in Regex

.github/codecov.yml
I thought I fixed this in a previous PR but I guess not. I can't seem to find it. Turns out, our codecov was technically invalid because we weren't using `patch: off` under `status`.
To prevent this in the future, validate the codecov:
```shell
cd .github && curl --data-binary @codecov.yml https://codecov.io/validate
```
Fixes N/A
=> fix(codecov): use status > patch correctly

test/e2e/logout.test.ts
The main purpose of this PR is to get the assets from CI so we can update code-server on Docker.
I've run e2e tests twice and they keep failing. Maybe we removed the Log out button when we updated VS Code? cc @TeffenEllis 
I'm going to disable those tests for now.
```shell
✓ terminal.test.ts:26:3 › [WebKit] Integrated Terminal should echo a string to a file (18s)
1) logout.test.ts:4:3 › [Firefox] logout should be able logout ===================================
page.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[aria-label="Application Menu"]"
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
5 |     // Recommended by Playwright for async …
```
=> fix: comment out broken e2e test

ci/dev/postinstall.sh, docs/MAINTAINING.md, vendor/package.json, vendor/yarn.lock
This PR addresses a regression introduced in our VS code fork. Previously, we [removed two dependencies](https://github.com/cdr/code-server/pull/2961) which required additional native packages, however they were included in the latest release. Rather than remove these and break the desktop build, we now mark them as optional: https://github.com/cdr/vscode/commit/07bcbc37952d1c0944f6325c89d49a74099b61e1
Fixes #4179
=> Make native-keymap and keytar optional dependencies

ci/build/arch-override.json, ci/build/build-lib.sh, ci/build/build-packages.sh, test/scripts/build-lib.bats
This adds tests for build-packages.sh, specifically 
This PR introduces a new file called `build-lib.sh` which extracts the `get_nfpm_arch()` function out of `build-packages.sh` so that it can be unit tested. I did this because if you `source build-packages.sh` it runs the `main` function. 
With this new approach, we can move individual functions related to the build process into `build-lib.sh` and unit test them. 
The inspiration for this came from some recent rockiness with the 3.12.0 release and our interest in stabilizing the build and release pipeline.
Fixes N/A
_Note: I would love if we could fully test all our scripts used in the build and release process. I also tossed around the idea of rewriting these scripts in JS/TS but that's a discussion for the future 😉_
=> feat: add test for get_nfpm_arch()

.github/workflows/ci.yaml
This PR upgrades the Ubuntu runner 16.04 -> 18.04 for the `package-linux-cross` job in CI.
4 days ago, CI was working as expected.
Yesterday, it stopped working. 
After talking to @jawnsy, he shared with me that GitHub's infrastructure discontinued ubuntu-16.04: https://github.com/actions/virtual-environments/pull/3862/files on September 20th 
Therefore, we have no other choice but to upgrade to 18.04.
Will this break anything? _it shouldn't_ (famous last words)
> Ubuntu 16.04 (Xenial Xerus) had glibc 2.23 and Ubuntu 18.04 (Bionic Beaver) has glibc 2.27, so I believe this may raise our minimum version requirement to 2.27: https://launchpad.net/ubuntu/+source/glibc
> It looks like that version was released in early 2018, so that should be fine: …
=> fix(ci): upgrade runner to ubuntu-18.04

src/node/cli.ts, test/unit/node/cli.test.ts
This PR adds more tests for `src/node/cli.ts`. Specifically, these functions: `shouldRunVsCodeCli` and `bindAddrFromArgs`
Fixes #4210
TODOS
=> feat: add tests for shouldRunVsCodeCli and bindAddrFromArgs

ci/build/build-release.sh
This reverts commit b32b4edf3d1167f87cb3f4aaf1acd3d5378cefb3.
We are reverting this because we found out that while this fixes the postinstall
on Windows, it breaks it on mac and other devices.  
See: https://github.com/cdr/code-server/issues/3874#issuecomment-925397980
This change came in #4116 came from @maxloh with the goal of: 
> Currently, Windows default script-shell (cmd) fails to run the postinstall script.
>
> This commit fixes the problem by running postinstall.sh explicitly with the default bash executable of the OS.
While that fixed the postinstall issue on Windows, it broke it for anyone installing with Homebrew since our formula does not depend on `bash`. Instead of modifying the formula, we are opting for reverting b32b4edf3d1167f87cb3f4aaf1acd3d5378cefb3 and using `sh` …
=> Revert "fix: run postinstall script explicitly with bash (#4116)"

docs/MAINTAINING.md
This PR updates the `MAINTAINING` docs, specifically:
- adds Team section with Onboarding and Offboardng sections
- adds notes around release platforms
- updates release instructions with step for naming version branch correctly
Fixes #3894
Fixes #4174
=> docs(MAINTAINING): update release section + add team section

package.json
=> fix(package.json): update node version requirements to >=14

package.json, test/package.json, test/yarn.lock, yarn.lock
This PR addresses CVE-2021-3807 Package: ansi-regex mentioned [here](https://github.com/cdr/code-server/pull/4236/checks?check_run_id=3705188051).
It also fixes tmpl (dependency used under `/test`) mentioned [here](https://github.com/cdr/code-server/security/code-scanning/150?query=ref%3Arefs%2Fpull%2F4251%2Fmerge+ref%3Arefs%2Fpull%2F4251%2Fhead+ref%3Arefs%2Fheads%2Fjsjoeio-fix-trivy).
Fixes N/A
=> chore(deps): upgrade ansi-regex to 5.0.1 and tmpl to 1.0.5

ci/helm-chart/templates/ingress.yaml
Hi. I found you use old version of Ingress in helm chart.
Ingress became GA in [Kubernetes v1.19](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#ingress-graduates-to-general-availability).
Output after v1.19
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: code-server
labels:
helm.sh/chart: code-server-1.0.3
app.kubernetes.io/name: code-server
app.kubernetes.io/instance: code-server
app.kubernetes.io/version: "3.12.0"
app.kubernetes.io/managed-by: Helm
spec:
rules:
- host: "code-server.example.loc"
http:
paths:
- path: /
backend:
service:
name: code-server
port: 
number: 8080
```
=> Use Ingress v1 from Kubernetes v1.19 in helm chart

.github/CODEOWNERS
This PR makes a minor update to `CODEOWNERS`.
Fixes https://github.com/cdr/code-server/pull/4244#issuecomment-928243088
=> fix: update CODEOWNERS for helm-chart

ci/steps/brew-bump.sh, ci/steps/steps-lib.sh, test/scripts/steps-lib.bats
This PR adds a lot of bash helper functions (+ tests) used in `brew-bump.sh` in order to ensure this script doesn't fail when publishing a release.
Fixes #3962
To test out the other parts of the script (specifically `GIT_ASKPASS`), here is what I did:
1. Create new Workspace on `https://master.cdr.dev/workspaces`
2. "log out" of git with:
```shell
git config --global --unset user.name
git config --global --unset user.email
git config --global --unset credential.helper
```
3.  Verify log out by trying to clone via HTTPS a private repo:
```shell
git clone https://github.com/jsjoeio/dip.chat-v2.git
```
4. Create script similar to `brew-bump.sh` and add `steps-lib.sh` to Workspace.
5. Make script executable `chmod +x test-brew.sh`
6. Run script: `VERSION="1.2.3" …
=> fix(brew-bump.sh): add checks and handle errors 

docs/ipad.md
=> iPad docs: add copy & paste known issue

ci/helm-chart/Chart.yaml
This PR bumps the helm-chart version 1.0.3 -> 1.0.5 to account for two patches/changes we made since we last bumped it:
- https://github.com/cdr/code-server/commit/5a36627aae7d8772f4190453dc8aae5da7e73104
- https://github.com/cdr/code-server/commit/1ffca5751c36235af686d13c788c8ace5bb0a117
Fixes #3794
cc @Matthew-Beckett @alexgorbatchev
=> chore(helm-chart): bump to 1.0.5

docs/CONTRIBUTING.md, docs/MAINTAINING.md
This PR adds more docs around our testing strategy including:
- new section in `MAINTAINING.md`
- new section for scripts in `CONTRIBUTING.md`
Fixes #4177
=> docs: update section around testing

src/node/main.ts, vendor/package.json, vendor/yarn.lock
This PR resolves an issue where our [marketplace modifications](https://github.com/cdr/vscode/commit/65b2462c212d415fbf521489307e58e5b691818b) are not applied to the CLI.
- Also fixes error logging from child process.
=> Fix marketplace in CLI

.github/workflows/ci.yaml, src/node/routes/index.ts, test/unit/node/routes/static.test.ts
This PR does a few things:
- fixes broken unit test
- reverts a CI change around testing made in https://github.com/cdr/code-server/pull/4010
- check if `vscode` exists before closing
Fixes N/A
=> fix: revert CI change + fix broken tests

src/node/wrapper.ts
Previously we use `inherit` in stdio param to spawn the http server process(or the child process), which will swallow the logs in child process and not be written to the `code-server-stdout.log`. Using `pipe` will fix this problem.
Fixes #
=> Fix: use pipe to spawn http server process to enable logs pipe to files

src/node/cli.ts, test/unit/node/cli.test.ts
This PR adds tests for `code-server/src/node/cli.ts` to cover lines 314,318.
Fixes N/A
#TestingMondays
=> feat(cli): add tests for password, hashed-password

.github/workflows/ci.yaml, src/node/cli.ts, src/node/util.ts, test/unit/node/cli.test.ts
This PR adds tests for `readSocketPath`.
Fixes N/A
=> feat(cli): add test for readSocketPath

.github/workflows/docker.yaml, .github/workflows/npm-brew.yaml
This PR updates the trigger event for both the "Publish on npm and brew" and the "Publish on Docker" release workflows so that they only run on `released` (instead of `published`).
In order for us to publish pre-releases _without_ triggering these workflows, this change needs to happen.
We learned this through the [GitHub Actions docs](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#release):
> Note: The prereleased type will not trigger for pre-releases published from draft releases, but the published type will trigger. If you want a workflow to run when stable and pre-releases publish, subscribe to published instead of released and prereleased.
Fixes N/A
Related https://github.com/cdr/code-server/issues/4264
=> refactor(ci): only run release workflows on released event

docs/CONTRIBUTING.md
This PR updates the `CONTRIBUTING.md`, specifically adding a section for Linux-related dependencies needed to develop code-server.
H/T to @bryphe-coder and @vapurrmaid for testing this out on Ubuntu-based dev environments and helping us improve the docs!
Fixes N/A
=> docs(contrib): update linux requirements

test/package.json, test/yarn.lock
This PR fixes a minor issue with `path-parse` in `test/yarn.lock`. 
Fixes #4279
=> chore(deps): upgrade path-parse in test/yarn.lock

.github/workflows/ci.yaml
It was causing version mismatch errors.
It might make more sense to have this in the postinstall but for now I
have foregone that as it would be installed in every step including
those that do not run e2e tests.
=> Avoid npx for Playwright dependencies

.github/workflows/ci.yaml, ci/dev/postinstall.sh, test/package.json, test/yarn.lock
This might be causing more Playwright issues.
=> Use frozen lockfile for test dependencies in CI

.github/workflows/ci.yaml, ci/dev/postinstall.sh, ci/helm-chart/values.yaml, test/package.json, test/yarn.lock
Fixes #4441 
- Drop duplicate PodSecurityContext usage
- Drop duplicate ServiceAccount usage
=> Drop duplicate Helm values from values.yaml

src/node/routes/errors.ts, test/unit/node/routes/errors.test.ts
Fixes #4355
Escapes HTML contained in error messages before rendering the error page.
=> Escape HTML from messages in error page

ci/helm-chart/templates/deployment.yaml
=> Fix helm chart for `extraConfigmapMounts`

docs/CONTRIBUTING.md
This PR updates `CONTRIBUTING.md` with our new development workflow. 
Fixes #4478
=> docs: update CONTRIBUTING with new flow

ci/dev/watch.ts
The "Starting watch-client" string no longer appears in the latest build
output.  We could look for "Finished compilation with" to avoid
restarting when other tasks restart (since they also include the name
i.e. "Finished compilation extensions with 0 errors") but I figure we
might as well restart code-server when any compilation task completes in
case other tasks include changes that need to be reloaded.
=> Fix watcher not restarting code-server on VS Code compilation

src/node/routes/index.ts
This causes / to always take precedence and on the VS Code side we would
see /vscode instead of / so the matching does not work correctly.
=> Fix /vscode route being shadowed by /

ci/dev/watch.ts, package.json, src/node/routes/vscode.ts, src/node/util.ts, yarn.lock
This PR addresses feedback listed in https://github.com/cdr/code-server/pull/4499#issuecomment-967292556
Previously, attempting to load VS Code before the compiler all files resulted in some cryptic errors. Our file watcher now detects when VS Code has truly finished compiling and appends a file our server can check for during development.
=> Watcher improvements

.github/codecov.yml
This adds a Slack webhook integration so we get notifications in our company Slack for coverage changes. 
Fixes N/A
=> chore(codecov): add slack webhook integration

src/node/routes/errors.ts, vendor/package.json, vendor/yarn.lock
Fixes #4521
Related: https://github.com/cdr/vscode/commit/a1d3f915454bb88e508c269a3c5bafb3cfa6f9f6
=> Fix issue where 404 errors are mistaken for server errors.

test/package.json, test/yarn.lock
This PR fixes the version of `json-schema` used in our `/test` directory to resolve a security vulnerability.
Fixes N/A
=> chore(deps): upgrade json-schema version to 0.4.0

test/unit/node/util.test.ts
This PR adds an additional test for the `onLine` util function to cover the scenario where the child.Process passed to the function is missing the `stdout` method. This adds code coverage for [this line](https://github.com/cdr/code-server/blob/main/src/node/util.ts#L36).
- ["If the child was spawned with stdio set to anything other than 'pipe', then subprocess.stdout will be null."](https://stackoverflow.com/a/46024006/3015595)
- [Child Process - subprocess stdout - Node.js docs](https://nodejs.org/api/child_process.html#child_process_subprocess_stdout)
- [Child Process - options `stdio` - Node.js docs](https://nodejs.org/api/child_process.html#child_process_options_stdio)
Fixes N/A
#TestingMondays
Blocked by https://github.com/cdr/code-server/pull/4543
=> feat: add test for onLine throw error

docs/README.md, docs/link.md, src/node/cli.ts
`code-server --link` has not been updated for a while, and some users have reported connection issues with it (see #2734)
While we will continue to host the --link servers, this PR adds a warning that we are not officially maintaining this version of --link. In the future, we will likely release an improved version, using a new architecture and codebase. However, there is no timeline for this.
=> chore: add deprecation notice for --link

src/common/http.ts, src/node/http.ts, src/node/main.ts, src/node/routes/login.ts, src/node/routes/logout.ts, src/node/routes/vscode.ts, src/node/util.ts, test/unit/common/http.test.ts, test/utils/globalSetup.ts, vendor/package.json, vendor/yarn.lock
This PR addresses several issues surrounding using reverse proxies with code-server. 
Fixed #4503
See https://github.com/cdr/vscode/commit/5e0c6f3b95ed032e62c49101ae502a46c62ef202
- Updated vscode args to match latest upstream.
- Fixed issues surrounding trailing slashes affecting base paths.
- Updated cookie names to better match upstream's usage, debuggability.
=> Proxy path fixes

docs/CONTRIBUTING.md, docs/MAINTAINING.md
This PR updates our docs around the VS Code fork and syncing with upstream.
Fixes #4533
=> docs: update sections around VS Code fork

ci/dev/watch.ts, src/node/util.ts
The watch script was reloading the web server after every extension
compilation which is not necessary plus VS Code will not even be ready
at that point anyway.
Instead restart when the main compilation is finished.  The string to
match with includes a "with" because otherwise it would match "Finished
compilation extensions" which is not the main compilation task where we
actually need to restart the web server.
I also replaced this.log with console.log because the former does not
include a newline and it appears we want newlines with all
these (otherwise the next log starts on the same line which looks odd).
I removed the cache clean as well because the cache is meant to stay
there to speed up builds.
=> Remove excessive reloading before VS Code is ready

src/node/entry.ts, vendor/package.json, vendor/yarn.lock
Also fixes https://github.com/cdr/code-server/issues/4322
=> Fix spawning code-server within code-server

ci/dev/watch.ts, package.json, src/browser/pages/login.html, src/common/util.ts, src/node/http.ts, src/node/routes/login.ts, src/node/routes/logout.ts, src/node/routes/vscode.ts, src/node/util.ts, test/unit/common/util.test.ts, test/unit/node/http.test.ts, vendor/package.json, vendor/yarn.lock, yarn.lock
Fixes https://github.com/cdr/code-server/issues/4503
=> Fix relative paths

src/node/cli.ts, src/node/main.ts, src/node/routes/vscode.ts, test/unit/node/cli.test.ts, test/unit/node/plugin.test.ts
The problem before was that the pop() caused the open in existing
instance functionality to break because the arguments no longer
contained the workspace or directory (files are left untouched).
We could simply remove the pop() but since `workspace` and `folder` are
not CLI arguments I think it makes sense to handle them in a separate
function which can be called at the point where they are needed.  This
also lets us de-duplicate some logic since we create these arguments in
two spots and lets us skip this logic when we do not need it.
The pop() is still avoided because manipulating a passed-in object
in-place seems like a risky move.  If we really need to do this we
should copy the positional argument array instead.
=> Add separate function for VS Code arguments

install.sh
Adding option --edge to install latest edge / preview version.
```bash
$ ./install.sh --edge true
```
```bash
$ ./install.sh --edge=true
```
=> adding option --edge to install latest edge / preview version

docs/ios.md
=> Added instructions to install it on iOSi

ci/build/release-github-assets.sh
This PR fixes our `release-github-assets` script. Now if you run it twice, it will overwrite the assets uploaded to a release draft (which is the behavior I believe it previously had).
This is okay to do since the script is run by a developer prepping a release and it is unlikely you would accidentally run this script twice without wanting to overwrite uploaded assets.
Fixes #4602
=> fix: add --clobber to release-github-assets script

docs/android.md, docs/manifest.json
This PR piggybacks off #4536 and makes a few minor changes.
=> docs: add section for Android

.editorconfig
I have been wondering why my editor is not defaulting to two spaces and
it is because indent_size was removed from the * block.
I am not sure why we would need a separate block for package.json and
yaml anyway since they use the same settings as the rest of our code.
I would revert the commit but this change was made in a larger commit
with a bunch of unrelated changes.
=> Revert .editorconfig

docs/install.md
This PR fixes two broken links for `install.sh`. 
Fixes #4545
=> docs: fix install.sh link

ci/build/build-release.sh, package.json, vendor/package.json, vendor/yarn.lock
This PR fixes the code-server version in "Help: About"
Fixes #4629
=> fix: add codeServerVersion to vscode/product.json

docs/ipad.md
Fixes a link to the iPad/iOS related issues that previously went into Nirvana (looks like the label was renamed).
=> docs(ipad): fix link to ios-ipad related issues

.github/workflows/docs-preview.yaml
This PR updates the `docs-preview.yaml` workflow to use an environment which should have the correct secrets for deploying a docs preview.
Fixes #4027
=> fix(ci): add environment to docs-preview

CHANGELOG.md, src/node/cli.ts, test/unit/node/cli.test.ts, vendor/package.json, vendor/yarn.lock
Fixes #4598
Fixes #4620
Fixes #4600
=> chore: update vscode

docs/MAINTAINING.md
=> docs: fix a typo in MAINTAINING.md

test/unit/node/settings.test.ts
This PR adds additional tests for `node/settings.ts` to ensure we log warnings when expected.
The `SettingsProvider` provides the application with access to the settings for code-server. This is then added to all routes under `req.settings` so they can easily access it. We're adding tests to ensure that our logger does indeed log warnings when something goes wrong.
Fixes N/A
#TestingMondays
=> feat: add tests for node/settings.ts

docs/guide.md
=> docs: fix a typo in guide.md

ci/steps/brew-bump.sh
This PR uses `is_env_var_set` correctly.
Fixes #4686
=> fix: reverse logic in brew-bump env fns

package.json, yarn.lock
This PR upgrades `follow-redirects` based on a vulnerability report. 
Fixes N/A
=> chore: use 1.14.7 follow-redirects

ci/build/build-release.sh
VS Code moves this as part of their packaging task.  We will probably
want to look into using theirs instead of replicating it.
Fixes https://github.com/coder/code-server/issues/4721
=> fix: package bin/helper directory in the right spot

.github/workflows/ci.yaml, .github/workflows/npm-brew.yaml, .github/workflows/npm-dev.yaml, ci/steps/publish-npm.sh, package.json, test/unit/node/settings.test.ts
This PR makes two major changes to how we release the npm package.
When a PR is opened into `main`, we publish the npm package under a tag with the PR number. For example, you could install code-server based on #4768 and the commit 1a44d9b8839642b048fe5816946208a9e910f132 by running:
```shell
yarn global add code-server@4768
```
If you needed to install a previous commit on the same PR, you can get more specific and run this:
```shell
yarn global add code-server@4768-1a44d9b8839642b048fe5816946208a9e910f132
```
This allows developers to test PR changes in a _production setting_ by installing code-server locally with a specific tag.
Anytime a PR is merged into the `main` branch, it triggers a GitHub Actions workflow to publish those changes as an npm package tagged with `beta`. 
This …
=> feat: publish beta and development tags on npm

.github/workflows/npm-dev.yaml
I didn't think it through in my previous PR but since this workflow only runs on a merge into `main`, there is no PR number. So instead, we use the word "beta" and then we also have to grab a different SHA since there is no PR SHA.
Prevents this from happening again: https://www.npmjs.com/package/code-server/v/4.0.1--
https://github.com/coder/code-server/runs/4903294989?check_suite_focus=true#step:3:16
Fixes N/A
=> fix: update npm-dev.yaml

.github/ISSUE_TEMPLATE/bug-report.yml
Fix `OS/Web Information` section and don't render as Markdown.
This will fix this issue:
We don't want it to render as Markdown, but rather the default (HTML I believe).
It also adds a "Steps to Reproduce" section that I forgot and marks a few sections as required.
Fixes N/A
=> chore: update bug-report.yaml

.github/workflows/ci.yaml, .github/workflows/npm-beta.yaml, .github/workflows/npm-brew.yaml
This extracts the publish on npm workflow from ci.yaml and adds a new workflow
called `npm-beta.yaml`.
Now we have three workflows that publish to npm.
- `npm-beta.yaml` only runs on pushes and merges into `main`
- `npm-dev.yaml` only runs on PRs into `main` with approval from
code-server-reviewers team
- `npm-brew.yaml` only runs on releases
This should fix problems we had previously where anyone could open a PR and
publish under the code-server namespace. It also separates out the workflows
based on environment and when they should run.
I've also added the Environment `npm` which requires approval from one member of the code-server-reviewers team in order to run. This allows us to control which PRs publish to npm.
Fixes N/A
Fixes this issue: …
=> refactor(ci): clean up npm workflows

package.json, yarn.lock
This fixes two vulnerabilities that were identified as part of our audit workflow. 
Fixes N/A
=> chore(deps): update node-fetch and nanoid

ci/build/build-release.sh
Surprisingly it does not come already executable like the dev-bin
scripts.
Much to my shame I did not actually test a release with the helper
change.  This time I did and can confirm it works.
Truly fixes https://github.com/coder/code-server/issues/4721
However while it no longer errors it does not actually open a browser
window...so I will look into that separately.
=> fix: make browser helper executable

ci/build/build-standalone-release.sh, ci/build/npm-postinstall.sh, package.json, src/node/util.ts, test/package.json, test/unit/node/util.test.ts, test/yarn.lock, yarn.lock
This reverts part of the changes introduced in refactor: migrate from argon2 ->
@node-rs/argon2 (#4733)
Switching to @node-rs/argon2 introduced bugs that we couldn't solve due to
limitations in npm.
see here
https://github.com/coder/code-server/issues/4804#issuecomment-1030338395
Fixes #4804
=> revert: @node-rs/argon2 -> node-argon2

ci/helm-chart/Chart.yaml, ci/helm-chart/templates/ingress.yaml, ci/helm-chart/values.yaml
Fixes #NA - No issue created due to minor nature of change. 
This adds an optional parameter to the ingress object for `ingressClassName` which is available in K8s 1.18+. More information on `ingressClassName` can be found [here](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/).
Please let me know if you need any more information or other changes. I did a minor version bump for the chart, but happy to remove that if needed.
=> feat: Add support for ingressClassName in Helm Chart

ci/steps/docker-buildx-push.sh
Allow Docker images to be overwritten, which is required to update
dependencies in the base image when the upstream vendor resolves
security issues.
=> chore: allow overwriting Docker images

ci/release-image/entrypoint.sh
dumb-init needs to run as PID 1, otherwise it doesn't do anything.
exec dumb-init so it takes over PID 1 once the entrypoint script is done.
=> fix: Make dumb-init PID 1

src/node/util.ts, test/unit/node/update.test.ts, test/utils/helpers.ts
This PR adds more tests for  `update.ts`.
Fixes #4831
=> feat: add tests for update.ts

ci/helm-chart/templates/deployment.yaml, ci/helm-chart/values.yaml
Fixes #
No issue created. Fix is very minor, but I can open an issue if needed.
Adds support for `imagePullSecrets`, which is defined as a top-level key in the values.yaml, but not previously used in the deployment template.
This PR adds support for `imagePullSecrets` into the deployment template, which is useful for users that may need to extend the default code-server image (installing additional language support, etc.) and as such may need to pull an image from a private container registry.
This should be a non-breaking change, as `imagePullSecrets` is defaulted to an empty array in the values.yaml
=> feat: Add support for imagePullSecrets to Helm chart

docs/MAINTAINING.md
Minor additions to the "Syncing with Upstream VS Code" docs.
Fixes N/A
=> docs: update sync vscode instructions

.github/workflows/ci.yaml, .github/workflows/docs-preview.yaml
This PR adds a check to the `npm` and Docs Preview workflows to only run if base is coder/code-server repo. It will not run them on PRs from forks. 
- add check to `preview` job in `docs-preview.yaml`
- add check to `npm` job in `ci.yaml`
- remove approval required for `npm` job
- https://github.community/t/how-to-detect-a-pull-request-from-a-fork/18363/3?u=jsjoeio
- https://github.community/t/make-secrets-available-to-builds-of-forks/16166/17
Fixes #4027
=> fix: skip docs/npm workflows on forks

test/e2e/codeServer.test.ts, test/e2e/models/CodeServer.ts, vendor/package.json, vendor/yarn.lock
VS Code names their databases after the workspace but if two workspaces share the same path (for example if they are on different virtual machines) but they share the same domain (since IndexedDB is scoped to domain) then those two states will have a naming collision.
Blocked on https://github.com/coder/vscode/pull/46.
=> fix: state collision

test/unit/node/cli.test.ts
This PR adds a test to ensure we have coverage for this block:
https://github.com/coder/code-server/blob/main/src/node/cli.ts#L358-L360
Fixes #4885
=> feat(testing): add new test for cli.ts

src/node/constants.ts, test/unit/node/constants.test.ts
Introduce helper functions for getting human- and machine-readable
version strings from the constants package, and cover it in unit
tests.
This is a first step to resolving #4874.
=> feat: add version string functions to constants

src/node/http.ts
While troubleshooting #4900, we got a nice smile from this typo ;)
=> style: cookie doman => cookie domain

package.json, yarn.lock
Fixes #4900
Since [`express@5.0.0-beta.1` was released on 2022-02-14](https://www.npmjs.com/package/express/v/5.0.0-beta.1), any new install was bumped to use that version. That's because [the way `semver`'s caret works, and how `beta` > `alpha`](https://github.com/npm/node-semver#prerelease-tags). And it just so happens that there's a breaking change in there apparently.
When developing, the `yarn.lock` file is used, which itself was [pinning to `express@5.0.0-alpha.8` ](https://github.com/coder/code-server/blob/a989e0c3879e5a7cd52011a4de929e4d1e3faad3/yarn.lock#L1732)which led to everything working well.
But when a package gets published, [the lockfile gets ignored by `yarn publish`](https://classic.yarnpkg.com/lang/en/docs/yarn-lock/#toc-check-into-source-control) (see the missing …
=> fix: Pin express to 5.0.0-alpha.8

src/node/http.ts, test/package.json, test/unit/node/http.test.ts, test/yarn.lock
When a user opens code-server at a url like `localhost:8080` without the `-e` (ignore last opened flag), we redirect to that workspace and append the folder as a query param. 
Before, it would encode the url to something like: `localhost:8080/?folder=%2FUsers%2Fjp%2Fdev%2Fcoder`
Now, it maintains the slashes and redirects to: `localhost:8080/?folder=/Users/p/Fdev/coder`
Fixes this issue https://github.com/coder/vscode/pull/45#issuecomment-1050236578 identified in the VS Code 1.64 update.
=> feat(http): keep slashes in queryParams in redirects

src/node/constants.ts, src/node/entry.ts, test/unit/node/constants.test.ts
Show the bundled version of Code OSS in the text-based output
for --version and --help, in addition to the JSON output
(--version --json)
Closes: #4874
---
Help output:
```
$ node . --help
code-server 4.0.2 development with Code 1.63.0
Usage: code-server [options] [path]
- Opening a directory: code-server ./path/to/your/project
- Opening a saved workspace: code-server ./path/to/your/project.code-workspace
```
Output of --version:
```
$ node . --version
4.0.2 development with Code 1.63.0
```
Output of --version --json:
```
$ node . --version --json
{"codeServer":"4.0.2","commit":"development","vscode":"1.63.0"}
```
=> feat: add version of Code OSS to output

.github/workflows/ci.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/docker.yaml, .github/workflows/docs-preview.yaml, .github/workflows/installer.yml, .github/workflows/npm-brew.yaml, .github/workflows/scripts.yml
* Configure build jobs to cancel previous builds when new changes
are pushed to a pull request branch, and serialize builds when
running in a branch from a push event
* Reduce privileges of GitHub token for scripts workflow
=> chore: limit concurrency for build jobs

src/node/cli.ts, test/e2e/baseFixture.ts, test/e2e/codeServer.test.ts, test/e2e/extensions.test.ts, test/e2e/github.test.ts, test/e2e/globalSetup.test.ts, test/e2e/login.test.ts, test/e2e/logout.test.ts, test/e2e/models/CodeServer.ts, test/e2e/openHelpAbout.test.ts, test/e2e/terminal.test.ts, test/unit/node/cli.test.ts, vendor/package.json, vendor/yarn.lock
This will allow injecting credentials into code-server if you already
have them.
Blocked by https://github.com/coder/vscode/pull/48
=> feat: github-auth flag

src/node/cli.ts, src/node/routes/vscode.ts, test/unit/node/cli.test.ts, test/unit/node/routes/vscode.test.ts, vendor/package.json, vendor/yarn.lock
Since we handle this in the vscode.ts route, we no longer need to pass it to VS
Code as a CLI arg since it's deprecated on that side.
This adds logic to our `vscode` route handler to handle both folder and workspace paths passed in via the CLI
Fixes an issue related to https://github.com/coder/vscode/pull/45
Blocked by https://github.com/coder/vscode/pull/49
=> refactor: remove folder/workspace from vsCodeCliArgs

src/node/app.ts, src/node/cli.ts, test/unit/node/app.test.ts, test/unit/node/cli.test.ts
Fixes #1466
Add a cli option `--socket-permission`, and set file mode accordingly when listening a socket.
=> feat: cli arg for file permission of socket

test/e2e/baseFixture.ts, test/e2e/codeServer.test.ts, test/e2e/models/CodeServer.ts, vendor/package.json, vendor/yarn.lock
Contains a test for migrating from an older version of code-server.
=> feat: migrate state to new database name

.github/workflows/ci.yaml, .github/workflows/trivy-docker.yaml
This PR re-enables the trivy Docker scan as part of our CI pipeline. With this, we will have trivy do a security check on our Docker image tagged `latest` so that we can catch any security vulnerabilities.
Example scan: https://github.com/coder/code-server/runs/5428919398?check_suite_focus=true
@code-asher I were chatting about this. We want the scan to run on `latest` instead of the local build since the local build will use the newest dependencies. Instead, we want to check what's in production and ensure that it has no issues. We'll run this new workflow nightly (once a day) and check for any issues. This way, we can stay on top of the Docker image and fix things sooner.
Fixes #4903
=> fix: re-enable trivvy docker scan

test/unit/node/cli.test.ts
This adds a test to ensure that setting the log level with `process.env.LOG_LEVEL` to `error` sets it as expected. 
Fixes #4916
=> testing: add new test for logLevels

.github/workflows/trivy-docker.yaml
Looks like I didn't give this workflow the right permissions: https://github.com/coder/code-server/runs/5432361797?check_suite_focus=true
I am not sure if `actions` needs `write` permissions or if `security` needs `write` permissions so I added it to both.
Fixes N/A
=> chore: add permissions trivy-docker

.github/workflows/docs-preview.yaml
Updates:
- No need to deploy a website preview
- Supports commit hashes in the URL
- Probably it will work good with forks
=> docs: update docs preview

src/node/cli.ts, test/unit/node/cli.test.ts
This PR adds a test for `optionDescriptions`.
Fixes #4915
=> feat(testing): add test for optionDescriptions

.github/workflows/ci.yaml, .github/workflows/docker.yaml, .github/workflows/npm-brew.yaml, ci/build/release-github-assets.sh, ci/steps/docker-buildx-push.sh, ci/steps/publish-npm.sh, docs/MAINTAINING.md
This PR fixes the npm and docker workflows that runs on a release to correctly download artifacts so it can publish it to the npm and Docker registries. 
https://github.com/coder/code-server/blob/main/.github/workflows/npm-brew.yaml#L21-L37
The default [`download-artifact`](https://github.com/actions/download-artifact) assumes that you're downloading artifacts from the running workflow. The problem is [`npm-brew.yaml`](https://github.com/coder/code-server/blob/main/.github/workflows/npm-brew.yaml#L21-L37) runs on [`released` events](https://github.com/coder/code-server/blob/main/.github/workflows/npm-brew.yaml#L8-L9).
Example: maintainer creates release branch `v4.1.0` ➡️ opens PR ➡️ team approves PR ➡️ maintainer merges PR into `main` ➡️ `npm` job from `npm-brew.yaml` and the …
=> fix(ci): correctly download npm/docker artifacts

.github/workflows/npm-brew.yaml, ci/steps/brew-bump.sh
This fixes the `brew-bump.sh` script by using the correct logic. It also moves a `git clone` line from the script to a step in the `homebrew` job.
1. Fork `coder/code-server`
2. hard-code `VERSION` to `4.1.0-4970-6afc87b46dfa70adc0afe164a89662aac1a0b0cd` (otherwise it will fail) and disable `npm` job
3. Push up this change to a new branch
4. Add `HOMEBREW_GITHUB_API_TOKEN` as secret to fork (using my own token).
5. Manually dispatch action
6. See that it opens a PR upstream in homebrew-core
✅ tested this with @cdr-oss account on Coder workspace
✅ tested with @cdrci account and it worked: https://github.com/Homebrew/homebrew-core/pull/97235 (oops, should have just used the `--dry-run` option)
🔑 Updated the `HOMEBREW_GITHUB_API_TOKEN` under secrets with a PAT generated by @deansheather from …
=> refactor: checkout homebrew-core in action instead of script

.github/workflows/docker.yaml, .github/workflows/npm-brew.yaml
Uses raw output when using `jq` so branch name isn't in quotes and adds workflow for artifact download.
Fixes N/A
=> fix: use -r with jq and add workflow for artifacts

ci/steps/docker-buildx-push.sh
I didn't realize the Docker workflow needed `VERSION` to publish a tag. This fixes that workflow. 
See https://github.com/coder/code-server/issues/5022#issuecomment-1076869631 for more context
Todos
Fixes #5022
=> fix: source lib.sh in docker-buildx-push for tagging version

.github/ISSUE_TEMPLATE/bug-report.yml, ci/build/build-release.sh, ci/steps/publish-npm.sh, docs/android.md, docs/install.md, docs/manifest.json, docs/npm.md, install.sh, package.json, yarn.lock
Fixes #4927
Tried multiple ideas/approaches, this is the least worst I could find. Happy to amend/change things, and at least this will get the discussion going.
Here's a diff from an npm install before the change (left - installing from the public repos) and after (right - installing from the tar.gz generated by the build): https://editor.mergely.com/8tpzCXG6/
As expected, some versions have been bumped down, to actually follow what the yarn.lock had:
* `rotating-file-stream@3.0.3` => `rotating-file-stream@3.0.0` as per the [yarn.lock](https://github.com/coder/code-server/blob/be727871f6f7f0af48e9e3d0039d59aa46c855b5/yarn.lock#L3627)
* `argon2@0.28.5` => `argon2@0.28.4` as per the [yarn.lock](https://github.com/coder/code-server/blob/be727871f6f7f0af48e9e3d0039d59aa46c855b5/yarn.lock#L698 …
=> feat: Add a shrinkwrap file to the NPM release

ci/build/build-release.sh, patches/last-opened.diff
See commits for list of fixes.
=> fix: minor build fixes

.github/workflows/npm-brew.yaml, ci/steps/brew-bump.sh, ci/steps/docker-buildx-push.sh
This PR _should_ fix the `brew-bump` script that runs when we publish releases.
I tested this in a separate PR with the `--dry-run` flag and [received no errors](https://github.com/coder/code-server/runs/5667729416?check_suite_focus=true#step:3:182). I didn't try without `--dry-run` but can separately if requested.
Here is how I tested: https://github.com/coder/code-server/pull/5023/files 
Fixes #4950
=> refactor(brew-bump): fix homebrew bump script

ci/build/build-release.sh, ci/build/npm-postinstall.sh, patches/display-language.diff, patches/integration.diff, patches/series, patches/sourcemaps.diff
These issues were caused when I switched Code's packaged build instead of putting it together ourselves.
See individual commits for more information.
=> fix: add missing package.json and source maps

ci/helm-chart/values.yaml
Fixes #199
Hi, I see there's an example of docker in docker in `extraContainers` 
but in order to use it, you need to set `DOCKER_HOST` in code-server too
I think it a good idea to add more since we already had dind in `extraContainers` 
Working in my RKE cluster v1.21.10
=> docs(helm): add required env for docker-in-docker

renovate.json
Disables auto-updates of `express` dependency so things like https://github.com/coder/code-server/pull/5013 don't happen.
Fixes N/A
=> chore(rennovate): ignore updates for express

.github/workflows/docs-preview.yaml
Sadly, https://github.com/coder/code-server/pull/5042 did not fix the issue with forks. Disabling until myself or @BrunoQuaresma has time to look into this.
Fixes N/A
=> chore(ci): disable docs-preview on forks

ci/steps/publish-npm.sh
Accidentally [removed the part](https://github.com/coder/code-server/pull/4972/commits/c2c78456d0cedb029e7dc4a772b82f25a22ddde1) that writes the `jq` change to the `package.json` which means we weren't actually publishing to `@coder/code-server-pr`. Oops. 
Fixes N/A
=> fix(npm): write npm package name to file

.gitignore, docs/CONTRIBUTING.md, patches/base-path.diff, patches/display-language.diff, patches/integration.diff, patches/last-opened.diff, patches/local-storage.diff, patches/logout.diff, patches/marketplace.diff, patches/node-version.diff, patches/proposed-api.diff, patches/proxy-uri.diff, patches/series, patches/service-worker.diff, patches/sourcemaps.diff, patches/unique-db.diff, patches/update-check.diff, patches/webview.diff
=> chore(Code): upgrade to 1.65

ci/release-image/Dockerfile
Currently, the `codercom/code-server` Docker image includes a copy of the release's .deb package files, even though they're only used in an intermediate layer. What's more, it includes packages from every architecture, not just the one being released.
This patch fixes this by updating the Dockerfile to use a multi-stage build. First, the packages are copied from the local build context into a temporary directory in a "scratch" build stage. Then, this directory is mounted into the main build, so that the appropriate .deb file can be installed without ever being actually stored in the image.
In my testing (with the 4.2.0 packages for linux-amd64) this reduces the total compressed and uncompressed size by a fairly substantial amount:
| | Before | After | Change |
| --- | ---: | ---: | ---: | …
=> fix: Exclude .deb files from release Docker image

docs/ios.md
Fixes #
NodeJS and NPM say "Illegal Instruction" if repositories are not downgraded
=> docs: Update ios.md

.github/workflows/ci.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/installer.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

docs/termux.md
1) Updated information to use PRoot (simpler than Andronix and the way supported by Termux) to create and access the Debian distro.
2) Added helpful information on using PRoot with your dev environment.
3) Cleaned up spelling, grammar, and made documentation more consistent between sections.
Fixes #
=> docs: simplify termux installation process

.github/ISSUE_TEMPLATE/bug-report.yml, ci/steps/publish-npm.sh, docs/android.md, docs/install.md, docs/manifest.json, docs/npm.md
We tried to switch from `yarn` to `npm` because `yarn` ignores lockfiles
but learned that we missed a few key things.
For now, we are reverting docs and a few other changes that suggested
using `npm` instead of `yarn` until we fully remove `yarn` from the
codebase.
Related to https://github.com/coder/code-server/pull/5071
=> revert(docs): partially revert 326a1d1862872955cec062030df2bd103799a1eb

patches/webview.diff
Code added in 1.65.0 broke webviews when you are hosting them from the
same domain.
Really should add an e2e test as well but I do not have the time right now.
=> fix: webviews failing to load the iframe HTML

patches/base-path.diff
This makes it work behind a rewriting proxy as well as make it use the
correct remote authority.
=> fix: use current location for web extension resource endpoint

.github/workflows/docker.yaml, package.json
We had an issue publishing v4.0.3 where the action couldn't find the artifacts to download. This changes that flow to download the release assets from the release for the Docker workflow.
=> chore: attempt to fix docker

test/unit/node/update.test.ts
Using the toBe* functions will let us know what the actual values are
rather than just telling us true does not equal false.
Hopefully when this flakes again this helps us devise a fix.
=> chore: provide details when `update.checked` tests fail

src/node/app.ts, test/unit/node/app.test.ts
Wrap IPv6 addresses in square brackets for URL in ensureAddress.
Fixes #1582 (regression)
Thanks ;-)
=> fix: listening on IPv6 address not possible

src/node/cli.ts, test/unit/node/cli.test.ts
After some feedback, we realized it is more intuitive to disable file
downloads by setting the environment variable
`CS_DISABLE_FILE_DOWNLOADS` to `true` than `1`. This commit adds support
for both.
Fixes N/A
=> feat(cli): support true for CS_DISABLE_FILE_DOWNLOADS

patches/series, patches/telemetry.diff
This seems to have been dropped in the rewrite.
=> fix: patch telemetry

test/unit/node/update.test.ts
Fixes a flaky test in `update.test.ts`
=> fix(update): add OrEqual to update.checked test

.github/workflows/docker.yaml
The action actually does not support wildcards but it does support * for
downloading all artifacts.
=> fix: Docker push

.github/workflows/npm-brew.yaml
This should fix this issue we ran into with the 4.4.0 release.
https://github.com/coder/code-server/runs/6329089421?check_suite_focus=true#step:5:182
=> chore: configure git globally for brew publish

src/node/cli.ts
=> chore: update --help for disable-file-downloads

test/unit/node/util.test.ts
This adds an additional test for the `isFile` utility function to ensure
it returns `false` in the event of an error.
Related to #5153 [#5149](https://github.com/coder/code-server/issues/5149)
=> feat: add test for isFile when error

src/node/util.ts
Jest reported uncovered code for this function block. I did a search and couldn't find it used anywhere so decided we should remove it.
Related to #5149 #5153
=> refactor(util): remove unused isObject function

.github/workflows/docker.yaml, ci/release-image/docker-bake.hcl
=> Push code-server image to GHCR

.tours/contributing.tour, .tours/start-development.tour, ci/build/npm-postinstall.sh
This pr:
1. rename master to main on all github doc links 
2. correct node requirement from 14+ to 16+
3. correct link to contributing tour
=> docs: rename master to main in all github doc links

package.json, yarn.lock
=> chore(deps): upgrade typescript to v4.6

docs/guide.md
Applies Caddy installations documentation fixes and also resolves the following issue when trying to install Caddy:
W: GPG error: https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABA1F9B8875A6661
Related Caddy issues: caddyserver/dist#83
Reference to Caddy's docs commit history:
- https://github.com/caddyserver/website/commit/930109ec3399035c4870a6c6a673537ca4813960
- https://github.com/caddyserver/website/commit/2e255b1ee39c36919e913466489c205e47a7a8f2
- https://github.com/caddyserver/website/commit/0f4885e59214a2d08a775051b587bb3363c7453c
=> Fix caddy installation docs

.github/workflows/ci.yaml
install.goreleaser.com appears to no longer be available.
=> fix: install nfpm straight from GitHub

test/unit/node/util.test.ts
This adds an additional test for `handlePassowrdValidation` to ensure the correct behavior happens when passing in an invalid `passwordMethod`. Although it shouldn't happen, the new test ensurs that `default` case in the switch statement has coverage.
Related to #5153
=> feat: add additional test for handlePassswordValidation

.github/ISSUE_TEMPLATE/bug-report.yml
I forgot to update the `description` too.
Fixes N/A
=> chore: update bug report template description

test/unit/node/util.test.ts
This PR adds a test  for `open`.
Related to https://github.com/coder/code-server/issues/5153
=> feat: add test for open

src/node/util.ts, test/unit/node/util.test.ts
This PR refactors `open` to remove some unnecessary things and make it easier to test.
Related https://github.com/coder/code-server/issues/5153
=> refactor: open function

.github/workflows/docker.yaml
Thanks to @ricklambrechts `release-downloader` now supports wildcards for `fileName`. 
https://github.com/robinraju/release-downloader/issues/422
=> chore: only download .deb in docker release

ci/build/build-release.sh, ci/build/build-vscode.sh, patches/base-path.diff, patches/connection-type.diff, patches/disable-builtin-ext-update.diff, patches/disable-downloads.diff, patches/display-language.diff, patches/github-auth.diff, patches/integration.diff, patches/local-storage.diff, patches/log-level.diff, patches/logout.diff, patches/marketplace.diff, patches/proposed-api.diff, patches/proxy-uri.diff, patches/series, patches/service-worker.diff, patches/sourcemaps.diff, patches/telemetry.diff, patches/update-check.diff, patches/webview.diff, src/node/routes/vscode.ts, test/unit/node/routes/vscode.test.ts
Closes #5165 
I had a bit of trouble going straight to 1.68 (had some weird webview issues) so I went to 1.67 first then 1.68 and then it went smoothly.  Not sure if that is a coincidence but seems like updating one version at a time might be the way to go.
=> chore: update Code to 1.68

.github/workflows/ci.yaml, package.json, test/integration/listExtensions.test.ts, yarn.lock
codecov deprecated their Node wrapper for uploading coverage reports.
This removes that and uses their new uploaded along with the v2 GitHub
Action they maintain.
Fixes N/A
=> refactor: switch to codecov-uploader GitHub Action

patches/base-path.diff
We made a change in `workbench-dev.html` but forgot to make it in `workbench.html`. This fixes the Integrated Terminal to work when code-server is served NOT on the root path (i.e. accessed at `/vscode` instead of `/`).
Fixes https://github.com/coder/code-server/issues/5321
=> fix(terminal): use window.location to work when served NOT on root path

.prettierignore, .prettierrc.yaml
We were using an overrides command in our `.prettierrc.yaml` which
quickly became out of sync with Code's Prettier styles.
Instead, we simply tell Prettier to ignore `lib/vscode`.
This way, if you have `formatOnSave` on and you save inside
`lib/vscode`, you won't convert the file to use code-server's styles.
Fixes #
=> chore(prettier): ignore lib/vscode

src/node/wrapper.ts
Having NODE_OPTIONS set is unexpected and although the later flag should
override the previous flag it is not certain that will always be the
case.
Also some users are having issues with the 2 GB limit.
=> fix: remove default memory limit

ci/helm-chart/values.yaml
otherwise custom values will not be picked up by Flux/Helm
=> define extraInitContainers

.github/workflows/ci.yaml
I noticed the npm job wasn't running on merge actions.
See example: https://github.com/coder/code-server/actions/runs/2715111141
This should fix that. 
Fixes N/A
=> chore(ci): run npm job on pr merge

src/node/routes/vscode.ts
I noticed that the regex would match other strings than manifest.json such as manifest-json or something-manifest.json
=> fix regex for manifest route

test/integration/installExtension.test.ts, test/utils/runCodeServerCommand.ts
This refactors our integration test helper to allow you to pass environment variables. I also add a new integration test to ensure `EXTENSIONS_GALLERY` is used when passed in.
- refactor: add env arg to runCodeServerCommand
- feat: add EXTENSIONS_GALLERY integration test
Fixes #5364
=> feat: add test for EXTENSIONS_GALLERY

test/integration/help.test.ts
Previously, we added the `--install-extension` test to ensure that native modules worked as expected with the binary.
However, that relies on a network connection (see https://github.com/microsoft/vscode/issues/142812#issuecomment-1194155328). Instead, I propose this new integration test which checks the `--help` flag
which fails if used on the wrong platform.
Fixes #5369
=> feat: add --help integration test

.github/workflows/ci.yaml
Originally, I thought https://github.com/coder/code-server/pull/5429 would fix the issue of the npm job not running on merges into `main`. However, that didn't work. Turns out the action/workflow we were trying to fix is not a `pull_request` event but instead a `push` event. 
Therefore, we modified the logic to run on PRs into `main` (logic unchanged in file) and added logic to run on all other events besides `pull_request`. This protects it from running on PRs from forks but also allows it to run on `push` into `main`. We went with this approach instead of explicitly writing `main` in the logic so that it doesn't break if we change the default branch name.
- https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
- …
=> chore(ci): fix when npm job runs

patches/heartbeat.diff, patches/series
Fixes https://github.com/coder/code-server/issues/5378
=> fix: socket disconnections behind reverse proxies

docs/guide.md, test/e2e/extensions.test.ts
This adds docs on how to proxy to an Angular app
- docs(guide): add proxying to Angular app
- fixup: formatting
Fixes #
=> docs: add proxying to angular app

.github/workflows/npm-brew.yaml
This automates part of the release process for updating [code-server AUR package](https://aur.archlinux.org/packages/code-server). After the npm package is published, it will run this job which will update some files and open a PR to code-server-aur.
- add new `aur` job to npm/brew workflow which runs on releases
I was able to test this by adding a temporary job to `ci.yaml` and it successfully [opened a PR](https://github.com/coder/code-server-aur/pull/12).
https://github.com/coder/code-server-aur/issues/13
Fixes #5366
=> feat(ci): semi-automate code-server-aur update

test/e2e/extensions.test.ts, test/e2e/extensions/test-extension/extension.ts, test/e2e/extensions/test-extension/package.json, test/e2e/models/CodeServer.ts
This PR modifies our e2e test to reduce flakiness in the extension tests.
Fixes #5472
=> fix(testing): reduce flakiness in extension e2e tests

ci/build/build-release.sh, ci/build/npm-postinstall.sh, package.json, yarn.lock
Fixes #5056 #5174
> **Why are we removing `synp` after all?**
Because it only takes care of putting in the package-lock/shrinkwrap file the first level of dependencies, not the nested dependencies which we have from the yarn lockfile.
See the contents of https://unpkg.com/browse/code-server@4.2.0-5047-90c9adcded65d10004a9db71d0717cd90565baa3/npm-shrinkwrap.json, and how for example, `@mapbox/node-pre-gyp` is listed as a dependency of `argon2` - but is not present anywhere in the shrinkwrap file.
> **Why are we adding packages from `resolutions` in `devDependencies` too?**
What initially drove me to use `synp` was the fact that the `npm shrinkwrap` command would generate a lockfile that wasn't usable. Trying to install the package with that lockfile would fail with the following exception: …
=> fix: Generate shrinkwraps for the bundled vscode

ci/steps/publish-npm.sh
After this landed https://github.com/npm/cli/pull/5035, it broke our script. This PR catches the error thrown if the version is missing and handles it accordingly. I also cleaned up some of the output so the logs are easier to read.
=> chore: fix npm publish logic

patches/exec-argv.diff, patches/heartbeat.diff, patches/series, src/node/wrapper.ts
This allows us to use `--prof` to profile code-server.
=> fix: propagate execArgv

patches/disable-builtin-ext-update.diff, patches/heartbeat.diff, patches/telemetry.diff, patches/unique-db.diff, test/e2e/codeServer.test.ts
This drops the patch and also the tests (which were flakey and our longest running e2e tests).
- refactor: remove database migration patch & test
- chore: refresh patches
Fixes https://github.com/coder/code-server/issues/5482
=> refactor: drop db migration patch

ci/build/build-standalone-release.sh, ci/build/npm-postinstall.sh, package.json, test/unit/node/test-plugin/package.json
- fix: update npm-postinstall.sh script
- fix: use npm in release-standalone
- chore: update package.json
=> fix(npm): use correct flags and update version for npm

ci/build/npm-postinstall.sh
- chore: use npm ci in build-standalone-release
- docs: add comment to npm-postinstall.sh
followup from https://github.com/coder/code-server/pull/5533
=> chore: add npm followup comment

docs/install.md
The install instructions weren't copy-pastable: `$VERSION_foo` is the same as `${VERSION_foo}`, not `${VERSION}_foo`.
```sh
$ VERSION=4.6.1
$ curl -fOL https://github.com/coder/code-server/releases/download/v$VERSION/code-server_$VERSION_amd64.deb
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
$ echo curl -fOL https://github.com/coder/code-server/releases/download/v$VERSION/code-server_$VERSION_amd64.deb
curl -fOL https://github.com/coder/code-server/releases/download/v4.6.1/code-server_.deb
```
Fixes #
=> Fix deb install instructions: ${VERSION}_foo

.github/workflows/ci.yaml, patches/cli-window-open.diff, patches/disable-builtin-ext-update.diff, patches/heartbeat.diff, patches/insecure-notification.diff, patches/proposed-api.diff, patches/proxy-uri.diff, patches/safari-console.diff, patches/series, patches/sourcemaps.diff, patches/telemetry.diff
As a first attempt the required fixes/changes for the code version 1.71.
- The telemetry fix required some adjustments. I also included a fix that was recently merged upstream (https://github.com/microsoft/vscode/commit/b108bc8294ce920fcf2ee8d53f97c3bcf3316e1c) 
- The CLI changes seem to be included in the upstream version now. Feel free to remove the remaining changes...
To test this locally:
1. run this:
```shell
gh pr checkout 5535 && git submodule update --init && quilt push -a && yarn && yarn watch --port 3000
```
2. navigate to [localhost:3000](http://localhost:3000)
The following patches were tested locally:
Fixes #5528
=> Update to 1.71

patches/exec-argv.diff, patches/telemetry.diff
- docs: explain how to test exec-argv
- docs: update heartbeat.diff testing
- Revert "docs: update heartbeat.diff testing"
- docs: explain how to test telemetry patch
=> docs: update patch testing instructions

CHANGELOG.md, ci/build/release-prep.sh, ci/helm-chart/Chart.yaml, docs/MAINTAINING.md, docs/collaboration.md, docs/helm.md, docs/manifest.json, package.json, src/node/cli.ts, test/e2e/extensions/test-extension/package.json, test/unit/node/test-plugin/package.json, yarn.lock
This PR is to generate a new release of `code-server` at `4.7.0`.
=> release: 4.7.0

.github/workflows/publish.yaml
I've noticed the last two times the `aur` job runs and opens a PR into `code-server-aur`, there are conflicts. It seems like it's not getting the latest commits. Based on [this](https://github.com/actions/checkout/issues/439#issuecomment-830862188), I think specifying `ref` may help.
I do not see any downsides to adding this even if this doesn't fix it.
=> fix(ci): specify ref in aur publish job

docs/CONTRIBUTING.md, patches/disable-builtin-ext-update.diff, patches/logout.diff, patches/service-worker.diff, patches/update-check.diff
This updates Code to 1.71 and makes a small doc change.
- chore: update Code to 1.71.1
- chore: refresh patches
- docs: add quilt refresh tip
Fixes #5554
=> chore: update Code to 1.71.1

.github/workflows/installer.yaml
=> fix: installer tests

install.sh
Fixes #5383, RPM installs should use the -U flag instead of -i because -U will upgrade instead of failing if code-server is already installed.
=> Set RPM Upgrade Flag

patches/telemetry.diff
This adds instructions on how to test the telemetry patch. Eventually we
will add a test for it but for now, this makes it 10x easier to test.
=> docs: update telemetry patch

install.sh
In freebsd, su -c expects a login class argument instead of a command, if -c is preceded by a username, then -c and the arguments that follow will be passed as shell arguments
Fixes #5594
=> fix: fix can't run it as expected in freebsd

.github/workflows/build.yaml, ci/build/build-standalone-release.sh, ci/build/build-vscode.sh, ci/build/code-server.sh, src/node/wrapper.ts
- fix: remove deprecated symlink
- refactor: remove deprecation notice
- fixup! refactor: remove deprecation notice
- fix: add node to path
=> fix: add node to path

install.sh
Some people may have some reason to drop sudo and switch to doas
Fixes #5599
=> feat: add doas support

src/node/main.ts, src/node/util.ts, test/unit/node/util.test.ts
=> Allow opening files at a specific line and column (fixes #5619)

docs/guide.md
=> Update the cloudflare tunnel description.

src/node/cli.ts, test/e2e/codeServer.test.ts, test/e2e/displayLang.test.ts, test/e2e/downloads.test.ts, test/e2e/extensions.test.ts, test/e2e/github.test.ts, test/e2e/login.test.ts, test/e2e/logout.test.ts, test/e2e/models/CodeServer.ts, test/e2e/openHelpAbout.test.ts, test/e2e/terminal.test.ts, test/e2e/trust.test.ts
Add CLI flag to disable workspace trust feature, as described in documentation:
https://code.visualstudio.com/docs/editor/workspace-trust
Fixes #5288
=> add CLI argument `--disable-workspace-trust`

src/node/routes/vscode.ts
This was breaking the automatic opening of links in GIT_ASKPASS on a git clone. I've tried to execute this script manually, and it does indeed work!
=> fix: Enable the `BROWSER` environment variable

ci/release-image/Dockerfile, ci/release-image/docker-bake.hcl
=> add docker image release for Ubuntu based image

CHANGELOG.md, ci/helm-chart/Chart.yaml, ci/helm-chart/values.yaml, docs/helm.md, docs/manifest.json, package.json, patches/telemetry.diff, test/unit/node/test-plugin/package.json
This PR is to generate a new release of `code-server` at `4.8.0`
=> release: 4.8.0

.github/workflows/build.yaml
Due to https://github.com/Azure/setup-helm/issues/99, this pins the
version to v3.10.1 as a temporary fix.
=> fix: pin azure/setup-helm to v3.10.1

CHANGELOG.md, ci/helm-chart/Chart.yaml, ci/helm-chart/values.yaml, package.json, test/unit/node/test-plugin/package.json
This PR is to generate a new release of `code-server` at `4.8.1`
TODO
=> release: 4.8.1

.github/workflows/build.yaml, .prettierignore
- chore: update prettierignore
- chore: upgrade setup-helm 3.4
=> chore: prettierignore updates and setup-helm upgrade

.github/workflows/publish.yaml
This ensures that the branch is up-to-date with coder/code-server-aur
before opening a PR.
=> fix: merge in master from coder/code-server-aur

.github/workflows/publish.yaml, .github/workflows/release.yaml, docs/MAINTAINING.md, test/unit/node/test-plugin/package.json
This makes some minor changes to progress us towards a smoother release.
1. try on my fork of code-server (see build here: https://github.com/jsjoeio/code-server/actions/runs/3348696732/jobs/5548022068)
2. run draft-release: double-check npm-package is in release assets ([successful download/upload](https://github.com/jsjoeio/code-server/actions/runs/3348850297/jobs/5548330976))
3. publish release
4. ensure that the npm job successfully downloaded the right asset: https://github.com/jsjoeio/code-server/actions/runs/3364354246/jobs/5578605147
Fixes https://github.com/coder/code-server/issues/5148
=> fix: minor fixes related to release

test/e2e/webview.test.ts
This adds a test to ensure webviews work by rendering the Markdown Preview.
=> feat: add test for markdown webview

ci/build/build-vscode.sh
This adds a check to ensure `VERSION` is set if running `build:vscode` locally.
Fixes #5795
=> chore: add VERSION check in build-vscode.sh

install.sh
This patch fixes installation on coder.com on a kubernetes installation. Without the `--noconfirm` the install.sh script warns about that the package has not been installed. With this parameter set the installation succeed.
This is log message which suddly gets truncated
If I download install.sh via wget and run it with:
```
cat install.sh | sh | tee code-server-install.log
```
The warning was caused while there is no confirmation.
Steps to confirm patch is working:
- Spawn a manjaro based image up (without install.sh in template)
- wget current version of this script
- append parameter `--noconfirm`
- cat install.sh | sh | tee code-server-install.log
- now pacman installs the code-server package and no warning is printed out
My template uses the same installation as in coder examples. …
=> fix installing code-server on manjaro image

.github/workflows/build.yaml, .github/workflows/release.yaml, .prettierignore, CHANGELOG.md, ci/build/build-vscode.sh, ci/helm-chart/Chart.yaml, ci/helm-chart/values.yaml, package.json, src/node/wrapper.ts, test/unit/node/wrapper.test.ts
Published as a release candidate which can be installed via:
```shell
curl -fsSL https://code-server.dev/install.sh | sh -s -- --edge --standalone
```
=> release: 4.9.0

ci/build/build-standalone-release.sh, ci/build/npm-postinstall.sh
- refactor: default to npm in postinstall.sh
- refactor: exclude yarn.lock in standalone
=> refactor: use npm in build steps and postinstall.sh

.github/workflows/release.yaml
Tested locally and verified this works
=> fix: quote VERSION in jq command in release

.github/workflows/release.yaml
Double check I'm seeing this right here but the latest is lower in number...
Latest - https://github.com/goreleaser/nfpm/releases/tag/v2.22.2
The version we use - https://github.com/goreleaser/nfpm/releases/tag/v2.3.1
=> chore(nfpm): bump to latest version

.github/workflows/release.yaml
A while back, @code-asher and I discussed improving the "Download artifacts" step in the `release.yaml` workflow. 
These changes make it more "sturdy" because we now `fail` if no artifact found in the latest `completed` `build.yaml` workflow. 
- ensures the latest workflow must have the artifact and be completed
- fails if artifacts missing
- means doing a release might be slower because you have to wait for their to be a completed workflow
=> chore: update download artifacts in release

.github/workflows/publish.yaml
When I did the last release, `VERSION` wasn't defined which lead to a
blank string in the PR title and the commit message here:
https://github.com/coder/code-server-aur/pull/24
This should fix that.
=> fix: add VERSION to env in publish.yaml

.github/workflows/release.yaml, ci/build/build-release.sh, ci/build/build-standalone-release.sh, ci/build/npm-postinstall.sh
- refactor: remove keytar dep in cross-compile
- refactor: try other keytar package
=> fix: use npm and yarn consistently in build and release

.github/workflows/release.yaml
We believe this is causing issues with the 4.9.1 release we're doing right now so we've decide to remove caching in the release workflow for now.
=> refactor: rm node_mods caching in release workflow

.github/workflows/release.yaml
Fixes https://github.com/actions/runner-images/issues/6002
=> chore(ci): update linux cross-compile runner 20.04

ci/README.md, ci/build/nfpm.yaml
Found by @welove42 in https://github.com/coder/code-server/discussions/5810
Testing to see if this fixes the issue in releasing on Linux. See https://github.com/coder/code-server/issues/5874
=> fix: dst path in nfpm

docs/FAQ.md
=> Added how to disable file downloads in faq

.github/workflows/publish.yaml
This uses the `env.VERSION` which should fix the issue with version being blank.
Fixes N/A
=> chore: update aur job in publish.yaml

docs/termux.md
=> docs: add new termux installation method

docs/CONTRIBUTING.md
- docs: update section in troubleshooting
- docs: add section on standalone release
Fixes #5825
=> docs(CONTRIBUTING): add standalone release section

renovate.json
=> chore: use matchUpdateTypes

.github/workflows/build.yaml
This adds a new job to the Build CI pipeline to lint our GitHub Actions.
By doing this, we can prevent typos from slipping in.
Fixes #5776
=> feat(ci): add lint-actions step to build.yaml

docs/README.md
This was navigating to the relative markdown file, which is confusing when some links go to the docs.
=> chore: fix requirements so it navigates to docs

docs/guide.md
=> docs: add port-forwarding

docs/FAQ.md, docs/coder.md, docs/manifest.json
- docs: add difference between Coder
- fixup
- docs: add new doc coder.md under Install
- refactor: move coder docs to usage
Fixes #5508
=> docs: add usage in Coder

ci/helm-chart/Chart.yaml, ci/helm-chart/templates/deployment.yaml, ci/helm-chart/templates/service.yaml, ci/helm-chart/values.yaml
This allows the code server that lives within the cluster to be reached by other services in the cluster. Say, for example, a proxy server for Minecraft.
=> feature: add ability to attach ports to code server

patches/base-path.diff, patches/disable-downloads.diff, patches/display-language.diff, patches/getting-started.diff, patches/integration.diff, patches/local-storage.diff, patches/logout.diff, patches/marketplace.diff, patches/proposed-api.diff, patches/proxy-uri.diff, patches/service-worker.diff, patches/sourcemaps.diff, patches/telemetry.diff, patches/update-check.diff, patches/webview.diff
- worker-src already contains blob so we can avoid patching that.
- localeService moved.
- Remaining changes were just line changes.
- Make language extensions installable again.
- Remove broken "install in browser" for language packs.
- Replace new locale import.
Closes #6050
=> Update Code to 1.76.1

src/node/routes/vscode.ts
Fixes #
if I have multiple instances for code-server running for every user and I want to install the PWA the name currently defaults to "code-server" which overrides the desktop shortcut.
This fix allows multiple instances to be installed with customizable names.
=> Allow app-name configuration to change the name of the PWA

src/node/cli.ts, test/unit/node/cli.test.ts
This will make the ports panel use it instead of the default path-based proxy.
Closes #5311
=> Set proxy URI to domain proxy when possible

patches/base-path.diff, patches/disable-downloads.diff, patches/display-language.diff, patches/getting-started.diff, patches/integration.diff, patches/local-storage.diff, patches/logout.diff, patches/proposed-api.diff, patches/proxy-uri.diff, patches/service-worker.diff, patches/telemetry.diff, patches/update-check.diff, patches/webview.diff
=> Update Code to 1.77.1

ci/build/build-vscode.sh, flake.lock, flake.nix, patches/base-path.diff, patches/cli-window-open.diff, patches/disable-downloads.diff, patches/display-language.diff, patches/getting-started.diff, patches/integration.diff, patches/local-storage.diff, patches/logout.diff, patches/marketplace.diff, patches/proxy-uri.diff, patches/service-worker.diff, patches/sourcemaps.diff, patches/telemetry.diff, patches/update-check.diff, patches/webview.diff
No changes needed in the patches other than moving some lines around and updating the CSP hash as usual.
The flake had to be updated as it was using Node 16.16 and 16.17 is required at minimum now.  Also `python` seems to install Python 2 which is marked as deprecated so explicitly install `python3`.
Also had to update the environment variable used to provide the commit during build.
Closes #6190
=> Update to 1.78.2

patches/proxy-uri.diff, src/node/cli.ts, src/node/http.ts, src/node/main.ts, src/node/routes/domainProxy.ts, test/unit/node/cli.test.ts
Fixes #6218
Fixes #6195
this enables support for VSCODE_PROXY_URIs like https://code-{{port}}.{{host}}
=> use VSCODE_PROXY_URI for domainProxy, allow {{host}} replacement

patches/store-socket.diff, src/node/app.ts, src/node/cli.ts, src/node/main.ts, src/node/vscodeSocket.ts, test/unit/node/app.test.ts, test/unit/node/cli.test.ts, test/unit/node/vscodeSocket.test.ts, test/utils/helpers.ts
Fixes #5709
`readSocketPath` is now replaced by `VscodeSocketResolver` which will prefer editor sessions that match the files being opened.
How it works:
- Every newly created editor session now registers not just its socket path but also workspace data associated with the session, most notably the folders associated with the workspace. This data is encoded as JSON and appended to `vscode-ipc`.
- On CLI file open:
- Read `vscode-ipc`
- Return the first active socket, in order of "relevance". An editor session is more relevant if 1) one of the files being opened starts with one of the folders of the workspace, and otherwise if 2) the session was more recently registered to `vscode-ipc`
- If there were any sockets that failed to connect, we write back to `vscode-ipc` with those sockets …
=> Prefer matching editor sessions when opening files.

patches/base-path.diff, patches/disable-downloads.diff, patches/display-language.diff, patches/getting-started.diff, patches/integration.diff, patches/local-storage.diff, patches/marketplace.diff, patches/proxy-uri.diff, patches/sourcemaps.diff, patches/store-socket.diff, patches/telemetry.diff, patches/webview.diff
Mostly just the usual shifting or changing of the surrounding context but I did refactor the getting started block we insert because it keeps getting mangled on each update.  Instead of shifting things around the columns I just prepend it to the right column.
Closes https://github.com/coder/code-server/issues/6257
=> Update Code to 1.79.1

src/node/main.ts, src/node/vscodeSocket.ts, test/unit/node/vscodeSocket.test.ts
=> Use unique socket per user for managing editor sessions

CHANGELOG.md, patches/store-socket.diff, src/node/app.ts, src/node/cli.ts, src/node/entry.ts, src/node/vscodeSocket.ts, test/e2e/models/CodeServer.ts, test/e2e/terminal.test.ts, test/unit/node/cli.test.ts, test/unit/node/plugin.test.ts, test/unit/node/vscodeSocket.test.ts
While I was at it I added a CLI flag to override the default.  I also swapped the default to --user-data-dir.
The value is set on an environment variable so it can be used by the extension host similar to VSCODE_IPC_HOOK_CLI.
Continuation of a fix for https://github.com/coder/code-server/issues/6275.
=> Set session socket into environment variable

docs/guide.md
Added a guide on proxying to a Svelte app since there wasn't one already. Used the vue and angular guides as a template and included a link to an issue post on sveltekits website which adds some context.
Fixes: #6270
=> Added Svelte to guide.md

.github/workflows/build.yaml, patches/base-path.diff, patches/cli-window-open.diff, patches/disable-downloads.diff, patches/display-language.diff, patches/getting-started.diff, patches/integration.diff, patches/local-storage.diff, patches/logout.diff, patches/marketplace.diff, patches/proxy-uri.diff, patches/service-worker.diff, patches/sourcemaps.diff, patches/telemetry.diff, patches/update-check.diff, patches/webview.diff
=> Update Code to 1.80.1

src/node/cli.ts, src/node/http.ts, test/unit/node/http.test.ts
=> add trusted-origins cli argument

docs/FAQ.md, src/node/cli.ts, src/node/http.ts, src/node/routes/domainProxy.ts, src/node/routes/pathProxy.ts, test/unit/node/cli.test.ts, test/unit/node/proxy.test.ts
Fixes # https://github.com/coder/code-server/issues/6348
This change adds a `disable-proxy` option (set by `--disable-proxy`  flag, `CS_DISABLE_PROXY=1`  or
`CS_DISABLE_PROXY=true`, or `disable-proxy` config), which disables the proxy routes to forwarded ports, including
the domain and path proxy routes over HTTP and WebSockets.
Note, it does not patch VS Code itself to block the auto port forwarding, but that can be disabled with `remote.autoForwardPorts=false`. Generally, these two features would be used together, but I didn't want to tightly couple them.
=> Add --disable-proxy option

docs/guide.md
Added missing curly brackets in Caddyfile configuration example.
=> Update Caddyfile syntax

src/node/cli.ts, src/node/main.ts, src/node/routes/login.ts, src/node/util.ts, test/unit/node/util.test.ts
The tilde is ambiguous and it can be helpful to know exactly what paths code-server is trying to use, especially if it is running as a different user than you expected.
May help with https://github.com/coder/code-server/discussions/6388, https://github.com/coder/code-server/issues/6389, and https://github.com/coder/code-server/issues/6380
=> Remove humanPath

yarn.lock
This gets rid of the unused peer dependency that was pulling in protobufjs.  Seems yarn ignores it but not npm.
Partially addresses https://github.com/coder/code-server/issues/6392
=> Upgrade @coder/logger

src/node/cli.ts, test/unit/node/cli.test.ts
Hi!
I added the "HOST" environment variable. It works the same way as the "PORT".
I also added tests for it depending on "PORT" tests.
Fixes #6422
=> "HOST" environment variable

.github/workflows/build.yaml, .github/workflows/release.yaml, .github/workflows/security.yaml, ci/build/npm-postinstall.sh, docs/CONTRIBUTING.md, docs/android.md, docs/npm.md, docs/termux.md, flake.nix, install.sh, package.json, patches/base-path.diff, patches/cli-window-open.diff, patches/disable-builtin-ext-update.diff, patches/disable-downloads.diff, patches/display-language.diff, patches/getting-started.diff, patches/integration.diff, patches/local-storage.diff, patches/logout.diff, patches/marketplace.diff, patches/proxy-uri.diff, patches/safari.diff, patches/series, patches/service-worker.diff, patches/sourcemaps.diff, patches/telemetry.diff, patches/update-check.diff, patches/webview.diff, yarn.lock
=> Update to VS Code 1.82.2

.github/workflows/release.yaml, docs/install.md
At least, for the standalone and for anyone running on default Node 18.
If support for 2.17 is needed then one would need to build Node 18 with 2.17 and then build code-server with that version (specifically, the native npm modules).
=> Bump minimum glibc to 2.28

docs/install.md
Updated `docker` documentation to use correct path locations.
=> 🔧 Change config directory from `.config` to `.local`

src/node/i18n/index.ts, src/node/i18n/locales/ur.json
Added new Language Locale Urdu
=> feat(lang): Add Urdu Locale

.github/workflows/release.yaml, ci/build/build-packages.sh, ci/build/build-standalone-release.sh
I removed building from source because the comment said it was due to CentOS 7, which we no longer use.
However, it seems that the real issue is that argon2 is pulling the wrong binary for cross-builds?  So we need to force building from source instead.  This should fix https://github.com/coder/code-server/issues/6446 and fix https://github.com/coder/code-server/issues/6448.
Unfortunately building from source is causing the new Kerberos module to fail on arm64.  To fix that we will need to install the arm64 version of the library.
Additionally, building from source is causing keytar to fail (a longstanding issue that previously was accidentally ignored when it failed in CI).  It seems unique to GitHub's VM; I cannot reproduce it in a Docker container.  So, switch to a Docker container.
=> Fix incorrect argon2 target in arm builds

src/node/routes/vscode.ts
Since the release of code-server v4.17.0 (Code 1.82), "Command Center" has become a default option. However, the current code-server PWA app lacks support for the Windows control overlay, resulting in an untidy appearance of the title bar. This commit introduces modifications to the manifest file to enable support for the window control overlay.
Fixes #3884
[Prior to patch]
[After the patch]
=> Modify manifest for window control overlay support

docs/guide.md
update nginx config to avoid wss error when expose code-server using a custom domain and a custom port via nginx.
see also: 
* [issue of code-server](https://github.com/coder/code-server/issues/4443) 
* [different between `$host` and `$http_host`](https://stackoverflow.com/a/76875724)
Fixes # https://github.com/coder/code-server/issues/4443
=> Update default nginx config in guide.md

patches/disable-downloads.diff, patches/display-language.diff, patches/getting-started.diff, patches/integration.diff, patches/local-storage.diff, patches/proposed-api.diff, patches/safari.diff, patches/telemetry.diff
Fixes https://github.com/coder/code-server/issues/6475
=> Update Code to 1.83.1

.github/workflows/release.yaml
See https://github.com/coder/code-server/pull/6524 and https://github.com/nodejs/node-gyp/issues/2869
This only affects the macOS release right now, but it will might eventually affect them all.
=> Fix node-gyp failure on macOS

docs/termux.md
I ran into this issue immediately on Android, solution from:
https://github.com/coder/code-server/issues/6480
=> Update termux information on how to enable keyboard shortcuts and tab key

ci/helm-chart/values.yaml
Helm error:
* `cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string`
Must wrap any `true` or `false` into quotes when passing values to `env` object.
=> Helm boolean fix

docs/CONTRIBUTING.md, docs/README.md, docs/requirements.md
The original call out was a bit salesy.
=> Improve README callout to coder/coder

ci/release-image/Dockerfile
- Use `man-db` instead of `man` *(as proposed by `apt`)*
- Use `vim-tiny` instead of `vim.tiny` *(as proposed by `apt`)*
- Sort requirements alphabetically
- Update `fixuid` version
- Add `wget` to the base package list as it is widely used and available by default on many Linux distros.
--- 
Regarding the suggestion to use `--no-install-recommends` from #6574, the difference between the two installs is minor:
```diff
- 1 upgraded, 74 newly installed, 0 to remove and 5 not upgraded.
+ 1 upgraded, 53 newly installed, 0 to remove and 5 not upgraded.
- After this operation, 200 MB of additional disk space will be used.
+ After this operation, 190 MB of additional disk space will be used.
```
As a conclusion, it is not worth the `~10MB` to possibly cause regressions.
=> ⬆ Update and organize `apt` packages

patches/base-path.diff, patches/disable-builtin-ext-update.diff, patches/display-language.diff, patches/external-file-actions.diff, patches/getting-started.diff, patches/integration.diff, patches/local-storage.diff, patches/proposed-api.diff, patches/proxy-uri.diff, patches/safari.diff, patches/unique-db.diff, patches/webview.diff
Fixes https://github.com/coder/code-server/issues/6572
=> Update Code to 1.85.0

ci/release-image/docker-bake.hcl
The `docker-bake.hcl` was not updated with references to Debian 12 *(Bookwork)*.
Related #6574
=> ⚙ Add Debian bookworm config to bakefile

docs/MAINTAINING.md
registry.hub.docker.com leads to an blank white page removing "registry' from the URL fixes it and takes the user to the correct page
=> Fix non-functional docker link

patches/disable-builtin-ext-update.diff, patches/display-language.diff, patches/external-file-actions.diff, patches/getting-started.diff, patches/local-storage.diff, patches/logout.diff, patches/proxy-uri.diff, patches/sourcemaps.diff, patches/store-socket.diff, patches/update-check.diff
Fixes https://github.com/coder/code-server/issues/6639
=> Update Code to 1.86.0

patches/sourcemaps.diff
=> Update Code to 1.86.1

.github/workflows/publish.yaml, ci/release-image/Dockerfile.fedora, ci/release-image/Dockerfile.opensuse, ci/release-image/docker-bake.hcl, ci/release-image/entrypoint-catatonit.sh
Fixes #6661
Please review after CI passes and produces working images
=> docker: add Fedora 39 and openSUSE Tumbleweed based images

ci/release-image/Dockerfile.fedora
Dnf will pull caches if invoked for local file install and is also unnecessary
Fixes #
=> Use rpm to install in Fedora image

.github/workflows/build.yaml
=> Update Code to 1.88.1

patches/base-path.diff, patches/disable-builtin-ext-update.diff, patches/external-file-actions.diff, patches/getting-started.diff, patches/integration.diff, patches/local-storage.diff
Fixes https://github.com/coder/code-server/issues/6782
=> Update Code to 1.89.0

patches/clipboard.diff, patches/series
This PR adds support for pasting to clipboard from STDIN. This is especially useful from the integrated terminal.
Use like this:
```bash
echo -n "HELLO CODE-SERVER!" | code-server --stdin-to-clipboard
alias xclip="code-server --stdin-to-clipboard"
echo -n "HELLO FROM ALIAS!" | xclip
sudo tee /usr/local/bin/xclip << EOF
#!/bin/sh
code-server --stdin-to-clipboard
EOF
sudo chmod +x /usr/local/bin/xclip
echo -n "HELLO FROM executable!" | xclip
``` 
Fixes #6175
=> clipboard support: code-server --stdin-to-clipboard

ci/helm-chart/templates/deployment.yaml, ci/helm-chart/values.yaml
=> Allow emptyDir type volume mounts

ci/release-image/docker-bake.hcl
Adds new ubuntu release as base image #6709
=> added ubuntu noble as base image

.github/workflows/build.yaml
Experimenting with fixing the segfault happening when building VS Code in CI.
=> Fix segfault in CI

CHANGELOG.md, patches/disable-builtin-ext-update.diff, patches/display-language.diff, patches/getting-started.diff, patches/proposed-api.diff, patches/sourcemaps.diff, patches/store-socket.diff, patches/webview.diff
Closes https://github.com/coder/code-server/issues/6857
=> Update to Code 1.91.0

.github/workflows/build.yaml
This should support checking for any newly added syntax in GitHub actions.
=> ci: updates actionlint to 1.7.1 version

docs/guide.md, src/node/cli.ts, src/node/routes/index.ts, src/node/routes/pathProxy.ts, test/unit/node/cli.test.ts, test/unit/node/proxy.test.ts
- Allows proxy traffic to be properly routed when `code-server` is served under a path.
- Introduces a new switch `abs-proxy-base-path`.
- When specified, `absproxy` requests will be forwarded using the value as prefix
- Code server is hosted at: `my-codeserver.com/user/123`
- React App is started at port 8080 under `PUBLIC_PATH` `/user/123`
- `abs-proxy-base-path` set to `/user/123`
- A `GET` request to `my-codeserver.com/user/123/absproxy/8080/app` will properly reach the app.
Fixes #6770
=> feat: introduce --abs-proxy-base-path that allows app proxying while code-server is not server at the root

install.sh, test/scripts/install.bats
Fixes part of https://github.com/coder/code-server/issues/6659#issuecomment-2318943559
Ever since [v4.89.0-rc.1](https://github.com/coder/code-server/releases/tag/v4.89.0-rc.1), there's only macos-arm64 but no more amd64. This fixes the script to align with the actual release artifacts.
In the long run, if we ever add back macos-amd64, the check can be removed entirely.
=> Fix install.sh refusing to download macos-arm64 standalone.

ci/release-image/entrypoint.sh
[Cannot start stopped docker container, user 'coder' does not exist](https://github.com/coder/code-server/issues/2767)
=> Re-fix #2767

.git-blame-ignore-revs, .github/workflows/build.yaml, package-lock.json, package.json, src/node/cli.ts
According to the `Prettier` [documentation](https://prettier.io/docs/en/install#summary), we should always install an **exact version**:
> Install an **exact version** of Prettier locally in your project. This makes sure that everyone in the project gets the exact same version of Prettier. Even a patch release of Prettier can result in slightly different formatting, so you wouldn’t want different team members using different versions and formatting each other’s changes back and forth.
That is, in `package.json` it should look like `"prettier": "3.0.3"` instead of `"prettier": "^3.0.3"`.
Don’t forget the `--save-exact` parameter when installing or updating the `prettier`:
```sh
npm install --save-dev --save-exact prettier@3.4.2
```
Otherwise, following the [Development …
=> chore: update and pinned prettier to version 3.4.2 and fix ci

src/browser/pages/error.css, src/browser/pages/error.html, src/browser/pages/global.css, src/browser/pages/login.css, src/browser/pages/login.html
Partially fixes the issue mentioned in #7077.
Using vscode theme colors is proposed in #3019, that would be nice. But until it is implemented, it might still be helpful as a fallback for browser adaptation in the absence of user preferences.
The problem is that this PR only solves the color scheme of login page, error pages.
I haven't found out how to modify the vscode page, so the FOUC is still there.
It seems that vscode page needs to be modified in `lib/vscode`? I.e. is this also an upstream issue?
I tested https://vscode.dev and it seems to have the same FOUC issue.
- But it seems to only appear when opening first time or pressing Enter in the address bar.
- i.e. it doesn't seem to happen when refreshing the page. (But happens in this project)
Or should actually compare to …
=> style: add dark theme color scheme

docs/npm.md
While trying to set up code-server on Alpine, I ran into build errors. To solve them, I had to add Kerberos development libs. Also, it looks like npm config doesn't work in recent version of Node and doesn't seem to be necessary. These instructions were tested in the Docker `node:20-alpine` image.
Fixes #
=> Update Alpine instructions

src/node/main.ts, src/node/routes/vscode.ts
Fixes #7089
On Windows, ESM loader only accept a valid `file://` URLs when it's a absolute path.
So add `file://` prefix and replace `\` to '/' to make it a valid URL.
=> fix: invalid ESM module path on Windows

docs/guide.md
Outdated upstream documentation urls
Updating the url for the upstream documentation of Pomerium, OAuth2-Proxy and Cloudflare Access
=> doc: update upstream documentation urls

flake.lock, patches/base-path.diff, patches/clipboard.diff, patches/disable-builtin-ext-update.diff, patches/display-language.diff, patches/external-file-actions.diff, patches/getting-started.diff, patches/integration.diff, patches/local-storage.diff, patches/logout.diff, patches/marketplace.diff, patches/proxy-uri.diff, patches/service-worker.diff, patches/sourcemaps.diff, patches/telemetry.diff, patches/update-check.diff, patches/webview.diff, test/e2e/routes.test.ts
Fixes https://github.com/coder/code-server/issues/7184
=> Update Code to 1.97.0

src/browser/pages/global.css, src/browser/pages/login.css
the new dark mode contrast is kind of strong, this makes it softer
=> softer dark mode

ci/helm-chart/Chart.yaml, ci/helm-chart/templates/deployment.yaml, ci/helm-chart/values.yaml
=> [Helm Chart] fix replicas and existingSecret. bump to 3.25.3

.github/workflows/release.yaml
As per the [Supported Runners and Hardware Resources](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) documentation, use the macos-13 workflow label to build the macOS amd64 package.
=> Add back macOS amd64 release

ci/release-image/Dockerfile
- Resolve https://github.com/coder/code-server/issues/7232
=> Fix issue 7232

src/node/cli.ts, src/node/main.ts, src/node/routes/domainProxy.ts, src/node/routes/pathProxy.ts, test/unit/node/cli.test.ts, test/unit/node/proxy.test.ts
Fixes #7283
I believe the fix is as simple as allowing OPTIONS requests to pass through the proxy without authentication. Then the service behind the proxy should respond with 200 or 204.
=> Allow OPTIONS requests through domain proxy

docs/README.md
The change is in "getting started" section and lists using the devcontainer feature of code-server (a separate GH project) as a potential method of using code-server in one's projects.
=> Adding a mention of code-server devcontainer feature

.github/workflows/security.yaml, .github/workflows/trivy-docker.yaml
GHA `ubuntu-20.04` image is fully deprecated:
https://github.com/actions/runner-images/issues/11101
Updating to `ubuntu-20.04` as per:
https://github.com/actions/runner-images?tab=readme-ov-file#available-images
Closes https://github.com/coder/security/issues/85
=> fix: update GitHub Actions Runner images

ci/build/build-vscode.sh, patches/base-path.diff, patches/clipboard.diff, patches/display-language.diff, patches/external-file-actions.diff, patches/getting-started.diff, patches/logout.diff, patches/proxy-uri.diff, patches/sourcemaps.diff, patches/store-socket.diff, patches/telemetry.diff, patches/trusted-domains.diff, patches/update-check.diff
Fixes https://github.com/coder/code-server/issues/7414
=> Update Code to 1.102.0

ci/helm-chart/values.yaml, docs/FAQ.md
See issue: https://github.com/coder/code-server/issues/7429
This PR updates the commented out defaults in the `values.yaml` to support docker-in-docker when deploying code-server on kubernetes. 
The existing values were too out of date and no longer worked. By using these values, in a vanilla cluster, one can run `docker ps` and `docker run hello-world` without any other additional setup.
=> [Helm Chart] Update values.yaml to better support docker
