coder/code-server

README.md
There is a grammatical error on the README page. This PR corrects grammar.
=> Update grammar on README

.travis.yml
=> ci: enable travis npm cache

README.md
It is quite annoying when Ctrl-C does not stop the container
=> Add -t flag to docker example

doc/self-hosted/index.md
I added a guide for people that want to use nginx to reverse proxy code-server for subdomain support and ssl.
#80
=> Add nginx reverse proxy guide for selfhosted

doc/admin/install/aws.md
Just adding minus to flag 'i' to ssh command and new line to aws.md
No
=> Adding minus to flag '-i'

doc/admin/install/google_cloud.md
`it's` is a contraction of `it is`, `its` is the possessive form.
No
=> Doc: fix typo

doc/self-hosted/index.md
In addition to capitalizing, I also reworded a sentence for improved grammar.
=> Capitalized first letters in headings to be consistent

doc/admin/install/aws.md
code-server-linux should be only code-server
=> Changed executable name

doc/admin/install/google_cloud.md
=> doc: fixed name of binary to match latest release

.gitignore
=> Changed "lib" to "/lib" at .gitignore

packages/server/src/cli.ts, packages/server/src/server.ts
Add better error handling and informative error message for when a port is in use
#408
=> Add port in use message

Dockerfile
=> Reduce layers in Dockerfile

Dockerfile
=> Add common utilities to Dockerfile

doc/admin/install/digitalocean.md
=> Updated digitalocean.md

doc/self-hosted/index.md
Realized after PR [519](https://github.com/codercom/code-server/pull/519) was merged that it had also missed removing one -h flag that had previously been removed from PR [422](https://github.com/codercom/code-server/pull/422) before it was closed
No open issue.
=> Fix self hosted flags

packages/protocol/src/browser/modules/node-pty.ts
Not sure the cleanest way to handle this. Gave it a shot :golfing_man:
=> Resize terminals after reconnect

README.md
Digital Ocean mentioned in the quick start section, corrected to our active trademark, DigitalOcean 
Unsure
=> Fix typo for DigitalOcean

Dockerfile
=> Remove chmod on project dir

doc/self-hosted/index.md
- Old Version contained a deprecated flag
- No
=> Updated Data Directory Flag

doc/admin/install/google_cloud.md
Link on google_cloud.md to ssl.md was wrong.
Cound't find it.
=> Updated google_cloud to have proper link to ssl.md

README.md, doc/assets/do-new-droplet-btn.svg
Adds a "Create a Droplet" button to the top of the getting started section in the README. Was originally going to put it as a badge at the top of the README, but the button doesn't look good when it's small.
Closes #877
=> Add DigitalOcean button to README

README.md
This is based user feedback and testing. This may expand if need be
=> [README] add Requirements section

Dockerfile
Decreases the size of the final docker image
No, but this doc https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run
=> Delete apt lists from final image

src/media/manifest.json
=> Revert "Updates manifest.json"

.travis.yml
Reverts cdr/code-server#1334
We should keep it until the next major release.
=> Revert "Decomission Travis"

Dockerfile
The Dockerimages pulls to many layers and now it has one less.
no
=> Dockerfile: Combine two runs

ci/release-image/Dockerfile
This PR combines some RUNs to reduce the layer count and also really delte the apt cache in all layers.
=> Optimize release Docker Image

README.md
=> chore: update README link (as no longer redirects)

README.md
Add link to contributing in README.md. I didn't know how to build the project and I didn't know it existed until I searched reddit on how to contribute.
=> Add link to contributing

src/browser/pages/app.html, src/browser/pages/error.html, src/browser/pages/home.html, src/browser/pages/login.html, src/browser/pages/update.html, src/browser/pages/vscode.html
Apple touch icon was lost in this commit 
https://github.com/cdr/code-server/commit/eef2ed0e786ebd49c6b1bd870dbe7e2662c9f004#diff-572499db0fdc38d27195448b4fa2d2c6
=> Returns back apple touch icon

package.json, yarn.lock
“devDependencies” already contains “@types/tar-fs”
=> Remove duplication in dependencies

ci/image/Dockerfile
"Yarn is fully deterministic as long as all your teammates are using the same Yarn version." (https://classic.yarnpkg.com/blog/2017/05/31/determinism/)
=> Peg yarn version to ensure deterministic builds

ci/dev/vscode.patch
1.46 isn't released yet and has bugs.
Closes #1667
=> Pin to vscode 1.45.1

README.md
=> Mention yarn as another installation option

README.md
=> Document AUR install instructions

README.md, ci/README.md
=> Update AUR docs

doc/FAQ.md
Removed apostrophe used for pluralization
server's -> servers
=> Fixed grammar error

src/node/entry.ts
=> Fix extension install path for CLI

doc/FAQ.md
Update --data-dir flag to --user-data-dir
=> Update --data-dir flag to --user-data-dir

README.md
=> Mention we're hiring in the README.md

ci/dev/vscode.patch
Looks like this will also fix #1866 as I am able to run tasks again.
=> Update VS Code to 1.46.1

README.md
=> Add enterprise context to README

src/node/wrapper.ts
This will allow code-server to be replaced and restarted by an external process.
=> Hotswap on SIGUSR1

.github/pull_request_template.md, doc/CONTRIBUTING.md
=> Document release branches

test/update.test.ts
We don't use auto updating anymore so no point fixing whatever's wrong.
=> Skip update tests

.eslintrc.yaml, src/node/http.ts
See https://stackoverflow.com/a/34881585/4283659
Closes #1538
=> Unlink socket before using

ci/build/npm-postinstall.sh
=> Adjust npm package postinstall to install extension dependencies

ci/build/release-github-draft.sh
=> ci: Improve release template

src/node/routes/index.ts
I managed to lose this in the rewrite.
Fixes #2327.
=> Skip heartbeat on /healthz endpoint

src/browser/pages/login.css, src/browser/pages/login.html
Not sure why Safari does these things...
Closes #2247
=> login.css: Disable webkit appearance for input elements 

ci/dev/lint.sh, ci/dev/vscode.patch, ci/steps/fmt.sh, ci/steps/lint.sh
=> vscode: Make eslint pass

doc/guide.md, doc/ipad.md
Builds upon the previous commit.
Thanks @AckerApple
=> doc/ipad.md: Add Servediter iPad App

ci/release-image/entrypoint.sh
=> release-image: Ignore $DOCKER_USER on restart

src/node/cli.ts, src/node/vscode.ts
Added --no-project or -empty option to code-server
Fixes #1951
=> Add --ignore-last-opened option

doc/npm.md
Fixes https://github.com/cdr/code-server/issues/2474.
=> doc/npm.md: Update docs for Alpine Linux

.gitignore, ci/build/build-release.sh, ci/build/npm-postinstall.sh, ci/dev/postinstall.sh, ci/lib.sh, lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcessSetup.ts, package.json
=> Symlink node_modules.asar to node_modules in lib/vscode

install.sh
=> Fixed bug in install script that broke it on recent Debian setups without sudo

doc/FAQ.md
=> doc/FAQ.md: Link to VSCodium's extension marketplace docs as well

docs/FAQ.md, docs/install.md
=> chore: Format docs

.github/CODEOWNERS
=> Add reviewer group as a codeowner

docs/CONTRIBUTING.md
Resolves: #2771
Merge after: #2774
=> docs: Update contributing requirements

lib/vscode/src/vs/server/node/channel.ts
I missed this one during the 1.53 update.
=> Implement missing terminal method

README.md
This PR updates the Hiring section in the `README.md`. H/T to @jawnsy for flagging this.
[Click here](https://github.com/cdr/code-server/tree/update-hiring-section#hiring) to see a full preview.
cc @cami333
Related:
- https://github.com/cdr/code-server/pull/2906#issuecomment-800757362
=> docs: update hiring section in readme

README.md, ci/helm-chart/Chart.yaml, ci/helm-chart/README.md, ci/helm-chart/values.yaml, docs/install.md, install.sh, package.json
This PR is to generate a new release of `code-server` at `3.9.2`
https://user-images.githubusercontent.com/3806031/112514732-d8427200-8d52-11eb-8f25-39f0d389174e.mov
=> release: 3.9.2

.github/PULL_REQUEST_TEMPLATE/release_template.md, ci/build/release-github-draft.sh
This PR updates the `release_template.md` and the release notes based on our latest release.
=> refactor: reorganize release notes draft format

.github/ranger.yml
This PR adds an action + comment for issues that are marked with `upstream`.
=> dev(ranger): add action for upstream issues

yarn.lock
This PR fixes a few vulnerabilities in code-server.
H/T to @PatrickDerichs for pointing them out 🎉
- update `yarn.lock` using `yarn upgrade parcel-bundler` and `yarn upgrade proxy-agent`
Fixes #2964
=> fix(deps): update and fix vulnerabilities

ci/dev/update-vscode.sh, docs/CONTRIBUTING.md
=> fix(update-vscode): add check/docs for git-subtree

lib/vscode/yarn.lock
Update netmask to address recent CVEs. See #3185.
=> chore(lib/vscode): update netmask

ci/build/build-vscode.sh
=> chore(build): compile vscode+extensions in parallel

lib/vscode/build/package.json, lib/vscode/build/yarn.lock
Clean up some dependencies with security issues that we never touch in our build process, and also update `vsce`. Tested locally, fingers crossed it all works :crossed_fingers:
=> chore(lib/vscode): cleanup/update build deps

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md, CHANGELOG.md, ci/dev/fmt.sh
This PR adds a `CHANGELOG.md` to the root. The goal of this is to reduce the amount of time spent putting together the release notes.
- add `CHANGELOG.md`
- update PR template
=> docs: add changelog

.github/dependabot.yml
This PR limits updates to `limiter`.
=> fix(dependabot): limit limiter updates

package.json, yarn.lock
This PR fixes the `ws` vulnerabilities in `parcel-bundler`.
=> fix: ws vulnerabilities

README.md
Updating the link desc to be clearer about where the URL goes/why it's of interest
=> Update link desc to Coder.com in README

install.sh
Fixes https://github.com/cdr/code-server/pull/3707#discussion_r663162999
=> chore: fix broken link in install.sh

docs/manifest.json
Adds the manifest.json, which is the configuration file to generate the navigation of code-server docs in https://coder.com/docs/code-server/latest.
=> chore: add docs manifest

.github/ISSUE_TEMPLATE/bug-report.md
Adds note to bug-report template about installation logs.
Fixes N/A
Related: https://github.com/cdr/code-server/issues/3870#issuecomment-889985417
=> docs: note about installation logs to bug report

docs/link.md
This PR changes the formatting of the code block to an accepted value.
=> change code block formatting

docs/collaboration.md
Fixes #4157 
cc @toddewilliams who may be able to help with messaging
=> add CodeTogether docs

test/package.json, test/yarn.lock
Fixes a security vulnerability reported by trivy in `set-value`
=> fix(security): update set-value

.github/workflows/ci.yaml, vendor/package.json, vendor/yarn.lock
Updates to ac74ac1220ad3016159c65ed5d6581ab88ab43be commit in fork.
Fixes N/A
=> chore(vscode): update to latest commit of fork

src/node/cli.ts, src/node/main.ts, src/node/routes/login.ts, src/node/util.ts, test/unit/node/util.test.ts
This PR refactors `humanPath` to be pure (i.e. no side effects) and it adds two tests for the function.
Fixes N/A
#TestingMondays
=> feat(testing): refactor humanPath and add tests

ci/helm-chart/templates/NOTES.txt
Fixes #4504
Currently fetching Pod, but I think it is better to use Service directly.
=> fix NOTE.txt

ci/release-image/Dockerfile
=> support git-lfs default

docs/ios.md, docs/manifest.json
This PR is based off #4614. It cleans up a few things.
=> docs: add section for iOS

vendor/package.json, vendor/yarn.lock
Fixes https://github.com/cdr/code-server/issues/3410
Fixes https://github.com/cdr/code-server/issues/4604
Fixes https://github.com/cdr/code-server/issues/4607
Fixes https://github.com/cdr/code-server/issues/4608
Fixes https://github.com/cdr/code-server/issues/4609
Also has the foundation for
https://github.com/cdr/code-server/issues/4619.
=> Update VS Code

.github/workflows/docs-preview.yaml, install.sh
=> fix: Update install.sh to use "coder" GitHub organization

.github/workflows/docker.yaml, ci/steps/docker-buildx-push.sh
* Use official action to log in to Docker Hub
* Run using pinned ubuntu-20.04 environment
=> chore: update Docker image publish workflow

package.json, yarn.lock
This PR addressees a vulnerability found by our audit script: https://github.com/coder/code-server/runs/5192448546?check_suite_focus=true#step:6:22
Fixes N/A
=> chore: update follow-redirects resolution

docs/guide.md
=> docs: Update guide.md

package.json, yarn.lock
Solution based on this: https://github.com/substack/minimist/issues/164#issuecomment-1074349919
Fixes https://github.com/advisories/GHSA-xvch-5gv4-984h
=> chore: update to minimist-list

.github/ISSUE_TEMPLATE/bug-report.yml
Add an additional checkbox to the bug report template asking folks to check if this issue occurs in GitHub Codespaces
Fixes N/A
=> chore: update bug report template

package.json, yarn.lock
=> chore(ci): update glob-parent

ci/lib.sh
This should have been part of https://github.com/coder/code-server/pull/5352 but I forgot it.
=> fix: update branch for release assets download

.github/workflows/docs-preview.yaml
=> chore(ci): only run docs preview on docs changes

docs/guide.md
Minor Fixes #
Changing the caddy installation steps 
Because of this Caddy's issue from the official repo
https://github.com/caddyserver/dist/issues/83
=> Changing the caddy installation steps

docs/requirements.md
Fixes #
Trial length in requirements.md was mistakenly at 1 year.
=> Correct trial length

docs/README.md
Originally opened by @BelphegorPrime in https://github.com/coder/code-server/pull/5375
Fixes https://github.com/coder/code-server/issues/5374
=> docs: clean up requirements

patches/logout.diff, patches/proxy-uri.diff, patches/service-worker.diff
Fixes https://github.com/coder/code-server/issues/5448
=> fix: logout appearing with auth=none

flake.lock, flake.nix
If anyone uses Nix this allows reproducibility.
I saw we added one for coder/coder so thought I would add the one I have been using for code-server.
=> chore: add flake for development with Nix

package.json, yarn.lock
Fixes https://github.com/coder/code-server/actions/runs/3147165815/jobs/5116399731
=> chore: update vm2 to 3.9.11

.github/PULL_REQUEST_TEMPLATE/release_template.md, CHANGELOG.md, ci/helm-chart/Chart.yaml, ci/helm-chart/values.yaml, docs/MAINTAINING.md, docs/helm.md, docs/manifest.json, package.json, patches/telemetry.diff, test/unit/node/test-plugin/package.json
This PR is to generate a new release of `code-server` at 4.7.1
=> release: 4.7.1

package.json, yarn.lock
fixes https://github.com/coder/code-server/actions/runs/3314022177/jobs/5472766433
=> chore: update minimatch

.github/workflows/publish.yaml, .github/workflows/release.yaml, docs/MAINTAINING.md, test/unit/node/test-plugin/package.json
=> Test branch

.github/workflows/publish.yaml, .github/workflows/release.yaml, docs/MAINTAINING.md, test/unit/node/test-plugin/package.json
Reverts coder/code-server#5733
I did not mean to merge, I thought I was on my fork!
=> Revert "Test branch"

CHANGELOG.md, ci/helm-chart/Chart.yaml, ci/helm-chart/values.yaml, package.json
=> release: v4.8.3

package.json, yarn.lock
Fixes https://github.com/coder/code-server/actions/runs/3631210986/jobs/6125542306
=> chore: update qs version

CHANGELOG.md, ci/helm-chart/Chart.yaml, ci/helm-chart/values.yaml
- chore: add 4.9.1 to changelog
- chore: bump Helm to 4.9.1
Closes #5874
=> release: v4.9.1

ci/helm-chart/templates/deployment.yaml, ci/helm-chart/values.yaml
=> feat(helm-chart): Add support for extraSecretMounts subPath (#5960)

install.sh
=> docs: fix extras dash in prefix instructions in install.sh

docs/npm.md
Closes #6045
Allow edits by maintainers
=> docs: Correction of a mistake in documentation

patches/getting-started.diff
=> Update to Code 1.77.3

CHANGELOG.md, ci/helm-chart/Chart.yaml, ci/helm-chart/values.yaml
Update the changelog and Helm chart for the new version.
=> Release v4.12.0

ci/README.md
=> fix: relative path in markdown

ci/helm-chart/templates/deployment.yaml
Fixes https://github.com/coder/code-server/issues/6431
=> add podAnnotaions to Helm

patches/disable-downloads.diff, patches/display-language.diff, patches/getting-started.diff, patches/sourcemaps.diff, patches/telemetry.diff
Fixes https://github.com/coder/code-server/issues/6516
=> Update Code to 1.84.2

ci/release-image/Dockerfile
=> ⬆ Update Debain version of base image

patches/proxy-uri.diff
=> Update Code to 1.86.2

docs/coder.md
add coder module as an installation method
=> docs: add coder module as an installation method for Coder workspaces

patches/base-path.diff, patches/cli-window-open.diff, patches/disable-builtin-ext-update.diff, patches/display-language.diff, patches/external-file-actions.diff, patches/getting-started.diff, patches/integration.diff, patches/local-storage.diff, patches/logout.diff, patches/marketplace.diff, patches/proxy-uri.diff, patches/service-worker.diff, patches/sourcemaps.diff, patches/telemetry.diff, patches/update-check.diff, patches/webview.diff
Fixes https://github.com/coder/code-server/issues/6744
=> Update Code to 1.88.0

patches/display-language.diff
=> Update Code to 1.89.1

.github/workflows/build.yaml
Testing to see if this is still necessary with the Node update.
=> Remove node-gyp install

patches/integration.diff
=> Update Code to 1.97.1

patches/external-file-actions.diff
=> Update Code to 1.97.2

patches/telemetry.diff
=> Update Code to 1.104.1
